export type Category = "all" | "pixel" | "frequency" | "statistical" | "metadata" | "sensor";
export type MediaType = "all" | "image" | "video" | "text";

/* ── SVG Icon paths per category (same icon for same category) ── */
export const CAT_ICON_PATHS: Record<Category, string> = {
    all: "",
    pixel: "M3 3h7v7H3z M14 3h7v7h-7z M14 14h7v7h-7z M3 14h7v7H3z",
    frequency: "M22 12L18 12L15 21L9 3L6 12L2 12",
    statistical: "M18 3h4v18h-4z M10 8h4v13h-4z M2 13h4v8H2z",
    metadata: "M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z M14 2v6h6 M16 13H8 M16 17H8 M10 9H8",
    sensor: "M12 12a10 10 0 110 0z M22 12h-4 M6 12H2 M12 6V2 M12 22v-4",
};

/* ── Category hex colors for icons ── */
export const CAT_HEX: Record<Category, string> = {
    all: "#888",
    pixel: "#4285F4",
    frequency: "#9C27B0",
    statistical: "#FBBC04",
    metadata: "#34A853",
    sensor: "#EA4335",
};

/* ── Media Type icon paths ── */
export const MEDIA_ICON_PATHS: Record<MediaType, string> = {
    all: "",
    image: "M21 15V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10l4-4 3 3 4-4 7 7z",
    video: "M23 7l-7 5 7 5V7z M16 3H2a2 2 0 00-2 2v14a2 2 0 002 2h14a2 2 0 002-2V5a2 2 0 00-2-2z",
    text: "M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z M14 2v6h6 M16 13H8 M16 17H8 M10 9H8",
};

export const MEDIA_HEX: Record<MediaType, string> = {
    all: "#888",
    image: "#4285F4",
    video: "#EA4335",
    text: "#34A853",
};

export const MEDIA_COLORS: Record<MediaType, string> = {
    all: "",
    image: "media-image",
    video: "media-video",
    text: "media-text",
};

export interface Method {
    id: string;
    category: Category;
    mediaType: MediaType;
    weight: number;
    year?: number;
}

export const METHODS: Method[] = [
    // Image + Video: metadata methods apply to both
    { id: "metadata", category: "metadata" as Category, mediaType: "image" as MediaType, weight: 0.07, year: 2003 },
    { id: "spectral", category: "frequency" as Category, mediaType: "image" as MediaType, weight: 0.06, year: 2007 },
    { id: "reconstruction", category: "pixel" as Category, mediaType: "image" as MediaType, weight: 0.05, year: 2018 },
    { id: "noise", category: "pixel" as Category, mediaType: "image" as MediaType, weight: 0.05, year: 2002 },
    { id: "edge", category: "pixel" as Category, mediaType: "image" as MediaType, weight: 0.04, year: 2007 },
    { id: "gradient", category: "pixel" as Category, mediaType: "image" as MediaType, weight: 0.04, year: 2016 },
    { id: "benford", category: "statistical" as Category, mediaType: "image" as MediaType, weight: 0.04, year: 2007 },
    { id: "chromatic", category: "sensor" as Category, mediaType: "image" as MediaType, weight: 0.05, year: 2010 },
    { id: "texture", category: "pixel" as Category, mediaType: "image" as MediaType, weight: 0.04, year: 2012 },
    { id: "cfa", category: "sensor" as Category, mediaType: "image" as MediaType, weight: 0.06, year: 2005 },
    { id: "dct", category: "frequency" as Category, mediaType: "image" as MediaType, weight: 0.04, year: 2009 },
    { id: "color", category: "pixel" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 2008 },
    { id: "prnu", category: "sensor" as Category, mediaType: "image" as MediaType, weight: 0.04, year: 2006 },
    { id: "ela", category: "pixel" as Category, mediaType: "image" as MediaType, weight: 0.06, year: 2007 },
    { id: "copymove", category: "pixel" as Category, mediaType: "image" as MediaType, weight: 0.04, year: 2010 },
    { id: "splicing", category: "pixel" as Category, mediaType: "image" as MediaType, weight: 0.04, year: 2017 },
    { id: "histogram", category: "statistical" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 2004 },
    { id: "wavelet", category: "frequency" as Category, mediaType: "image" as MediaType, weight: 0.04, year: 2011 },
    { id: "jpeg_ghost", category: "frequency" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 2008 },
    { id: "chi_square", category: "statistical" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 2001 },
    { id: "entropy", category: "statistical" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 2003 },
    { id: "gan_fingerprint", category: "sensor" as Category, mediaType: "image" as MediaType, weight: 0.05, year: 2019 },
    { id: "diffusion", category: "sensor" as Category, mediaType: "image" as MediaType, weight: 0.04, year: 2023 },
    { id: "noiseprint", category: "sensor" as Category, mediaType: "image" as MediaType, weight: 0.04, year: 2018 },
    { id: "upscaling", category: "pixel" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 2019 },
    { id: "frequency_band", category: "frequency" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 2015 },
    { id: "face_landmark", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.04, year: 2019 },
    { id: "lighting", category: "pixel" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 2015 },
    { id: "shadow", category: "pixel" as Category, mediaType: "image" as MediaType, weight: 0.02, year: 2013 },
    { id: "perspective", category: "pixel" as Category, mediaType: "image" as MediaType, weight: 0.02, year: 2016 },
    { id: "reflection", category: "pixel" as Category, mediaType: "image" as MediaType, weight: 0.02, year: 2018 },
    { id: "double_jpeg", category: "statistical" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 2010 },
    { id: "patchforensics", category: "sensor" as Category, mediaType: "image" as MediaType, weight: 0.04, year: 2020 },
    { id: "clip_detection", category: "sensor" as Category, mediaType: "image" as MediaType, weight: 0.04, year: 2021 },
    { id: "fourier_ring", category: "frequency" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 2013 },
    { id: "resnet_classifier", category: "sensor" as Category, mediaType: "image" as MediaType, weight: 0.04, year: 2020 },
    { id: "vit_detection", category: "sensor" as Category, mediaType: "image" as MediaType, weight: 0.04, year: 2022 },
    { id: "gram_matrix", category: "pixel" as Category, mediaType: "image" as MediaType, weight: 0.02, year: 2016 },
    { id: "srm_filter", category: "pixel" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 2012 },
    { id: "autocorrelation", category: "statistical" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 2008 },
    { id: "pixel_cooccurrence", category: "pixel" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 2014 },
    { id: "tamura_texture", category: "pixel" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 1978 },
    { id: "lpq_analysis", category: "pixel" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 2012 },
    { id: "fractal_dimension", category: "statistical" as Category, mediaType: "image" as MediaType, weight: 0.02, year: 2003 },
    { id: "bilateral_symmetry", category: "pixel" as Category, mediaType: "image" as MediaType, weight: 0.02, year: 2015 },
    { id: "histogram_gradient", category: "statistical" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 2009 },
    { id: "color_coherence", category: "pixel" as Category, mediaType: "image" as MediaType, weight: 0.02, year: 1997 },
    { id: "mutual_information", category: "statistical" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 2006 },
    { id: "laplacian_edge", category: "pixel" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 2004 },
    { id: "median_filter", category: "pixel" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 2013 },
    { id: "resampling", category: "statistical" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 2005 },
    { id: "contrast_enhancement", category: "statistical" as Category, mediaType: "image" as MediaType, weight: 0.02, year: 2015 },
    { id: "brisque", category: "statistical" as Category, mediaType: "image" as MediaType, weight: 0.02, year: 2012 },
    { id: "demosaicing", category: "sensor" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 2014 },
    { id: "steganalysis", category: "pixel" as Category, mediaType: "image" as MediaType, weight: 0.02, year: 2006 },
    { id: "thumbnail_analysis", category: "metadata" as Category, mediaType: "image" as MediaType, weight: 0.02, year: 2011 },
    { id: "perceptual_hash", category: "statistical" as Category, mediaType: "image" as MediaType, weight: 0.02, year: 2009 },
    { id: "illuminant_map", category: "pixel" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 2015 },
    { id: "radon_transform", category: "frequency" as Category, mediaType: "image" as MediaType, weight: 0.02, year: 1917 },
    { id: "zernike_moments", category: "statistical" as Category, mediaType: "image" as MediaType, weight: 0.02, year: 1934 },
    { id: "camera_model", category: "sensor" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 2006 },
    { id: "image_phylogeny", category: "statistical" as Category, mediaType: "image" as MediaType, weight: 0.02, year: 2012 },
    { id: "blocking_artifact", category: "frequency" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 2009 },
    { id: "efficientnet_detection", category: "sensor" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 2020 },
    { id: "attention_consistency", category: "sensor" as Category, mediaType: "image" as MediaType, weight: 0.02, year: 2021 },
    { id: "style_transfer", category: "sensor" as Category, mediaType: "image" as MediaType, weight: 0.02, year: 2016 },
    { id: "color_temperature", category: "pixel" as Category, mediaType: "image" as MediaType, weight: 0.02, year: 2017 },
    { id: "sift_forensics", category: "pixel" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 2004 },
    { id: "neural_compression", category: "sensor" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 2020 },
    // Spatial Domain
    { id: "local_binary_pattern", category: "pixel" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 2002 },
    { id: "hog_anomaly", category: "pixel" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 2005 },
    { id: "glcm", category: "pixel" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 1973 },
    { id: "local_variance_map", category: "pixel" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 2011 },
    { id: "morphological_gradient", category: "pixel" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 2008 },
    { id: "weber_descriptor", category: "pixel" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 2010 },
    // Frequency Domain
    { id: "gabor_response", category: "frequency" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 1996 },
    { id: "power_spectral_density", category: "frequency" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 2007 },
    { id: "phase_congruency", category: "frequency" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 1998 },
    { id: "radial_spectrum", category: "frequency" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 2016 },
    // Statistical
    { id: "higher_order_statistics", category: "statistical" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 2003 },
    { id: "zipf_law", category: "statistical" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 1935 },
    { id: "markov_transition", category: "statistical" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 2010 },
    { id: "saturation_distribution", category: "statistical" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 2019 },
    // Compression
    { id: "quantization_fingerprint", category: "frequency" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 2014 },
    { id: "color_banding", category: "pixel" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 2018 },
    // Generative
    { id: "upsampling_artifact", category: "sensor" as Category, mediaType: "image" as MediaType, weight: 0.03, year: 2019 },
    // Advanced Color
    { id: "color_gamut", category: "pixel" as Category, mediaType: "image" as MediaType, weight: 0.02, year: 2012 },
    { id: "white_balance", category: "pixel" as Category, mediaType: "image" as MediaType, weight: 0.02, year: 2017 },
    // Metadata Analysis (supports both image + video)
    { id: "exif_integrity", category: "metadata" as Category, mediaType: "image" as MediaType, weight: 0.02, year: 2003 },
    { id: "xmp_provenance", category: "metadata" as Category, mediaType: "image" as MediaType, weight: 0.02, year: 2004 },
    { id: "iptc_verification", category: "metadata" as Category, mediaType: "image" as MediaType, weight: 0.02, year: 2005 },
    { id: "gps_consistency", category: "metadata" as Category, mediaType: "image" as MediaType, weight: 0.02, year: 2010 },
    { id: "timestamp_forensics", category: "metadata" as Category, mediaType: "image" as MediaType, weight: 0.02, year: 2011 },
    { id: "file_structure", category: "metadata" as Category, mediaType: "image" as MediaType, weight: 0.02, year: 2008 },
    { id: "color_profile_meta", category: "metadata" as Category, mediaType: "image" as MediaType, weight: 0.02, year: 2004 },
    { id: "c2pa_verification", category: "metadata" as Category, mediaType: "image" as MediaType, weight: 0.02, year: 2022 },
    { id: "resolution_consistency", category: "metadata" as Category, mediaType: "image" as MediaType, weight: 0.02, year: 2016 },
    { id: "software_fingerprint", category: "metadata" as Category, mediaType: "image" as MediaType, weight: 0.02, year: 2014 },
    // Video Analysis Methods
    { id: "temporal_consistency", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.04, year: 2018 },
    { id: "lip_sync_analysis", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.04, year: 2020 },
    { id: "frame_interpolation", category: "frequency" as Category, mediaType: "video" as MediaType, weight: 0.03, year: 2019 },
    { id: "optical_flow_anomaly", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.04, year: 2015 },
    { id: "audio_visual_sync", category: "sensor" as Category, mediaType: "video" as MediaType, weight: 0.03, year: 2020 },
    { id: "deepfake_artifact", category: "sensor" as Category, mediaType: "video" as MediaType, weight: 0.04, year: 2019 },
    { id: "scene_transition", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.03, year: 2017 },
    { id: "motion_blur_consistency", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.03, year: 2016 },
    { id: "background_stability", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.03, year: 2018 },
    { id: "gaze_direction", category: "sensor" as Category, mediaType: "video" as MediaType, weight: 0.03, year: 2019 },
    { id: "facial_reenactment", category: "sensor" as Category, mediaType: "video" as MediaType, weight: 0.04, year: 2020 },
    { id: "video_compression_trace", category: "frequency" as Category, mediaType: "video" as MediaType, weight: 0.03, year: 2015 },
    { id: "flicker_analysis", category: "frequency" as Category, mediaType: "video" as MediaType, weight: 0.03, year: 2014 },
    { id: "hand_gesture_consistency", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.03, year: 2020 },
    { id: "body_proportion", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.03, year: 2019 },
    // Video Analysis Methods v2 - Advanced detection methods
    { id: "speech_cadence", category: "sensor" as Category, mediaType: "video" as MediaType, weight: 0.03, year: 2021 },
    { id: "ear_consistency", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.03, year: 2019 },
    { id: "hair_dynamics", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.03, year: 2020 },
    { id: "skin_texture_temporal", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.03, year: 2021 },
    { id: "shadow_consistency_video", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.03, year: 2018 },
    { id: "reflection_consistency_video", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.03, year: 2019 },
    { id: "pupil_dynamics", category: "sensor" as Category, mediaType: "video" as MediaType, weight: 0.03, year: 2021 },
    { id: "head_pose_estimation", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.03, year: 2018 },
    { id: "video_noise_pattern", category: "sensor" as Category, mediaType: "video" as MediaType, weight: 0.03, year: 2016 },
    { id: "heartbeat_detection", category: "sensor" as Category, mediaType: "video" as MediaType, weight: 0.04, year: 2020 },
    { id: "micro_expression", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.03, year: 2017 },
    { id: "clothing_consistency", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.03, year: 2020 },
    { id: "face_3d_reconstruction", category: "sensor" as Category, mediaType: "video" as MediaType, weight: 0.04, year: 2019 },
    { id: "video_codec_analysis", category: "frequency" as Category, mediaType: "video" as MediaType, weight: 0.03, year: 2015 },
    { id: "inter_frame_forgery", category: "statistical" as Category, mediaType: "video" as MediaType, weight: 0.03, year: 2017 },
    // Video Analysis Methods v3 - Extended detection (50 new)
    { id: "color_temporal_shift", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2020 },
    { id: "frame_drop", category: "frequency" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2019 },
    { id: "blink_rate", category: "sensor" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2020 },
    { id: "video_noise", category: "sensor" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2017 },
    { id: "skin_texture", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2021 },
    { id: "hair_detail", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2021 },
    { id: "eye_reflection", category: "sensor" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2020 },
    { id: "jawline", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2021 },
    { id: "ear_symmetry", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2020 },
    { id: "expression", category: "sensor" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2020 },
    { id: "pupil_dilation", category: "sensor" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2021 },
    { id: "facial_wrinkle", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2021 },
    { id: "nose_geometry", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2021 },
    { id: "forehead_texture", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2022 },
    { id: "teeth", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2021 },
    { id: "eyebrow", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2022 },
    { id: "neck_transition", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2022 },
    { id: "shoulder", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2021 },
    { id: "clothing_fold", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2022 },
    { id: "finger_geometry", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2022 },
    { id: "bg_perspective", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2019 },
    { id: "reflection_physics", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2020 },
    { id: "shadow_temporal", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2019 },
    { id: "watermark", category: "metadata" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2018 },
    { id: "motion_vector", category: "frequency" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2017 },
    { id: "head_pose_v2", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2020 },
    { id: "micro_expression_v2", category: "sensor" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2019 },
    { id: "face_alignment_v", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2019 },
    { id: "depth_consistency", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2020 },
    { id: "bokeh", category: "sensor" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2021 },
    { id: "lens_distortion_v", category: "sensor" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2019 },
    { id: "stabilization", category: "frequency" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2020 },
    { id: "edge_ringing", category: "frequency" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2018 },
    { id: "chroma_bleed", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2019 },
    { id: "pixel_repetition_v", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2021 },
    { id: "video_hash", category: "statistical" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2018 },
    { id: "face_boundary_blend", category: "sensor" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2020 },
    { id: "color_quant_v", category: "statistical" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2017 },
    { id: "spatial_freq_temporal", category: "frequency" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2019 },
    { id: "video_blockiness", category: "frequency" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2014 },
    { id: "temporal_noise", category: "sensor" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2016 },
    { id: "frame_energy", category: "statistical" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2018 },
    { id: "video_sharpness", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2017 },
    { id: "object_boundary", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2019 },
    { id: "texture_flow", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2020 },
    { id: "video_grain", category: "sensor" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2018 },
    { id: "contrast_temporal", category: "statistical" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2019 },
    { id: "video_saturation", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2018 },
    { id: "face_illumination", category: "pixel" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2020 },
    { id: "video_artifact_grid", category: "frequency" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2017 },
    // Text Analysis Methods
    { id: "perplexity_analysis", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.04, year: 2023 },
    { id: "burstiness_detection", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.03, year: 2023 },
    { id: "vocabulary_diversity", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.03, year: 2020 },
    { id: "stylometric_analysis", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.04, year: 2019 },
    { id: "ngram_frequency", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.03, year: 2004 },
    { id: "repetition_pattern", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.03, year: 2023 },
    { id: "coherence_analysis", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.03, year: 2020 },
    { id: "entropy_distribution", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.03, year: 2019 },
    { id: "sentence_length_variance", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.03, year: 2019 },
    { id: "readability_score", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 1948 },
    { id: "punctuation_pattern", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 2023 },
    { id: "topic_consistency", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.03, year: 2020 },
    { id: "word_frequency_rank", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.03, year: 1935 },
    { id: "semantic_density", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.03, year: 2021 },
    { id: "writing_rhythm", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 2023 },
    // Text Analysis Methods v2 - Additional NLP-based methods
    { id: "pos_tag_analysis", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.03, year: 2019 },
    { id: "discourse_markers", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.03, year: 2004 },
    { id: "coreference_chain", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.03, year: 2017 },
    { id: "named_entity_consistency", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.03, year: 2020 },
    { id: "hedging_language", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.03, year: 2023 },
    { id: "type_token_ratio", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 1957 },
    { id: "syntactic_complexity", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.03, year: 2019 },
    { id: "passive_voice_frequency", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 2023 },
    { id: "lexical_sophistication", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.03, year: 2020 },
    { id: "text_compression_ratio", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.03, year: 2023 },
    { id: "function_word_distribution", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.03, year: 2012 },
    { id: "pronoun_usage_pattern", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 2020 },
    { id: "clause_depth_analysis", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.03, year: 2019 },
    { id: "collocation_strength", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.03, year: 2010 },
    { id: "temporal_expression", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 2023 },
    // Text Analysis Methods v3 - Extended NLP analysis (35 new)
    { id: "adverb_frequency", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 2023 },
    { id: "contraction_usage", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 2023 },
    { id: "sentence_opener", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 2023 },
    { id: "emotional_tone", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 2018 },
    { id: "metaphor_density", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 2020 },
    { id: "question_frequency", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 2023 },
    { id: "paragraph_structure", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 2019 },
    { id: "transition_quality", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 2021 },
    { id: "idiom_detection", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 2020 },
    { id: "abstract_concrete", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 2005 },
    { id: "first_person_usage", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 2023 },
    { id: "technical_jargon", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 2021 },
    { id: "redundancy_detection", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 2023 },
    { id: "word_length_dist", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 2005 },
    { id: "hapax_legomena", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 1957 },
    { id: "conjunction_density", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 2023 },
    { id: "preposition_pattern", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 2023 },
    { id: "modal_verb_frequency", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 2023 },
    { id: "subordinate_clause", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 2019 },
    { id: "argument_structure", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 2021 },
    { id: "text_formality", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 2019 },
    { id: "negation_pattern", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 2023 },
    { id: "comparative_structure", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 2020 },
    { id: "quantifier_usage", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 2023 },
    { id: "referential_density", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 2020 },
    { id: "logical_connector", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 2021 },
    { id: "topic_shift_analysis", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 2020 },
    { id: "information_density", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 2021 },
    { id: "sentiment_variance", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 2019 },
    { id: "lexical_chain_repetition", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 2020 },
    { id: "genre_conformity", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 2019 },
    { id: "conclusion_pattern", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 2023 },
    { id: "vocab_complexity", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 2005 },
    { id: "sentence_connectivity", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 2020 },
    { id: "text_coherence", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 2019 },
];

export const CATEGORIES: { key: Category; labelKey: string }[] = [
    { key: "all", labelKey: "methods.catAll" },
    { key: "pixel", labelKey: "methods.catPixel" },
    { key: "frequency", labelKey: "methods.catFrequency" },
    { key: "statistical", labelKey: "methods.catStatistical" },
    { key: "metadata", labelKey: "methods.catMetadata" },
    { key: "sensor", labelKey: "methods.catSensor" },
];

export const MEDIA_TYPES: { key: MediaType; labelKey: string }[] = [
    { key: "all", labelKey: "methods.mediaAll" },
    { key: "image", labelKey: "methods.mediaImage" },
    { key: "video", labelKey: "methods.mediaVideo" },
    { key: "text", labelKey: "methods.mediaText" },
];

export const CAT_COLORS: Record<Category, string> = {
    all: "",
    pixel: "cat-pixel",
    frequency: "cat-frequency",
    statistical: "cat-statistical",
    metadata: "cat-metadata",
    sensor: "cat-sensor",
};
