export type Category = "all" | "pixel" | "frequency" | "statistical" | "metadata" | "sensor";

/* ── SVG Icon paths per category (same icon for same category) ── */
export const CAT_ICON_PATHS: Record<Category, string> = {
    all: "",
    pixel: "M3 3h7v7H3z M14 3h7v7h-7z M14 14h7v7h-7z M3 14h7v7H3z",
    frequency: "M22 12L18 12L15 21L9 3L6 12L2 12",
    statistical: "M18 3h4v18h-4z M10 8h4v13h-4z M2 13h4v8H2z",
    metadata: "M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z M14 2v6h6 M16 13H8 M16 17H8 M10 9H8",
    sensor: "M12 12a10 10 0 110 0z M22 12h-4 M6 12H2 M12 6V2 M12 22v-4",
};

/* ── Category hex colors for icons ── */
export const CAT_HEX: Record<Category, string> = {
    all: "#888",
    pixel: "#4285F4",
    frequency: "#9C27B0",
    statistical: "#FBBC04",
    metadata: "#34A853",
    sensor: "#EA4335",
};

export const METHODS = [
    { id: "metadata", category: "metadata" as Category, weight: 0.07 },
    { id: "spectral", category: "frequency" as Category, weight: 0.06 },
    { id: "reconstruction", category: "pixel" as Category, weight: 0.05 },
    { id: "noise", category: "pixel" as Category, weight: 0.05 },
    { id: "edge", category: "pixel" as Category, weight: 0.04 },
    { id: "gradient", category: "pixel" as Category, weight: 0.04 },
    { id: "benford", category: "statistical" as Category, weight: 0.04 },
    { id: "chromatic", category: "sensor" as Category, weight: 0.05 },
    { id: "texture", category: "pixel" as Category, weight: 0.04 },
    { id: "cfa", category: "sensor" as Category, weight: 0.06 },
    { id: "dct", category: "frequency" as Category, weight: 0.04 },
    { id: "color", category: "pixel" as Category, weight: 0.03 },
    { id: "prnu", category: "sensor" as Category, weight: 0.04 },
    { id: "ela", category: "pixel" as Category, weight: 0.06 },
    { id: "copymove", category: "pixel" as Category, weight: 0.04 },
    { id: "splicing", category: "pixel" as Category, weight: 0.04 },
    { id: "histogram", category: "statistical" as Category, weight: 0.03 },
    { id: "wavelet", category: "frequency" as Category, weight: 0.04 },
    { id: "jpeg_ghost", category: "frequency" as Category, weight: 0.03 },
    { id: "chi_square", category: "statistical" as Category, weight: 0.03 },
    { id: "entropy", category: "statistical" as Category, weight: 0.03 },
    { id: "gan_fingerprint", category: "sensor" as Category, weight: 0.05 },
    { id: "diffusion", category: "sensor" as Category, weight: 0.04 },
    { id: "noiseprint", category: "sensor" as Category, weight: 0.04 },
    { id: "upscaling", category: "pixel" as Category, weight: 0.03 },
    { id: "frequency_band", category: "frequency" as Category, weight: 0.03 },
    { id: "face_landmark", category: "pixel" as Category, weight: 0.04 },
    { id: "lighting", category: "pixel" as Category, weight: 0.03 },
    { id: "shadow", category: "pixel" as Category, weight: 0.02 },
    { id: "perspective", category: "pixel" as Category, weight: 0.02 },
    { id: "reflection", category: "pixel" as Category, weight: 0.02 },
    { id: "double_jpeg", category: "statistical" as Category, weight: 0.03 },
    { id: "patchforensics", category: "sensor" as Category, weight: 0.04 },
    { id: "clip_detection", category: "sensor" as Category, weight: 0.04 },
    { id: "binary_pattern", category: "pixel" as Category, weight: 0.03 },
    { id: "fourier_ring", category: "frequency" as Category, weight: 0.03 },
    { id: "resnet_classifier", category: "sensor" as Category, weight: 0.04 },
    { id: "vit_detection", category: "sensor" as Category, weight: 0.04 },
    { id: "gram_matrix", category: "pixel" as Category, weight: 0.02 },
    { id: "srm_filter", category: "pixel" as Category, weight: 0.03 },
    { id: "autocorrelation", category: "statistical" as Category, weight: 0.03 },
    { id: "pixel_cooccurrence", category: "pixel" as Category, weight: 0.03 },
    { id: "tamura_texture", category: "pixel" as Category, weight: 0.03 },
    { id: "lpq_analysis", category: "pixel" as Category, weight: 0.03 },
    { id: "fractal_dimension", category: "statistical" as Category, weight: 0.02 },
    { id: "bilateral_symmetry", category: "pixel" as Category, weight: 0.02 },
    { id: "histogram_gradient", category: "statistical" as Category, weight: 0.03 },
    { id: "color_coherence", category: "pixel" as Category, weight: 0.02 },
    { id: "mutual_information", category: "statistical" as Category, weight: 0.03 },
    { id: "laplacian_edge", category: "pixel" as Category, weight: 0.03 },
    { id: "copy_move_forensics", category: "pixel" as Category, weight: 0.04 },
    { id: "double_jpeg_detection", category: "statistical" as Category, weight: 0.03 },
    { id: "median_filter", category: "pixel" as Category, weight: 0.03 },
    { id: "resampling", category: "statistical" as Category, weight: 0.03 },
    { id: "contrast_enhancement", category: "statistical" as Category, weight: 0.02 },
    { id: "brisque", category: "statistical" as Category, weight: 0.02 },
    { id: "demosaicing", category: "sensor" as Category, weight: 0.03 },
    { id: "steganalysis", category: "pixel" as Category, weight: 0.02 },
    { id: "thumbnail_analysis", category: "metadata" as Category, weight: 0.02 },
    { id: "perceptual_hash", category: "statistical" as Category, weight: 0.02 },
    { id: "illuminant_map", category: "pixel" as Category, weight: 0.03 },
    { id: "radon_transform", category: "frequency" as Category, weight: 0.02 },
    { id: "zernike_moments", category: "statistical" as Category, weight: 0.02 },
    { id: "camera_model", category: "sensor" as Category, weight: 0.03 },
    { id: "image_phylogeny", category: "statistical" as Category, weight: 0.02 },
    { id: "blocking_artifact", category: "frequency" as Category, weight: 0.03 },
    { id: "efficientnet_detection", category: "sensor" as Category, weight: 0.03 },
    { id: "attention_consistency", category: "sensor" as Category, weight: 0.02 },
    { id: "style_transfer", category: "sensor" as Category, weight: 0.02 },
    { id: "color_temperature", category: "pixel" as Category, weight: 0.02 },
    { id: "sift_forensics", category: "pixel" as Category, weight: 0.03 },
    { id: "neural_compression", category: "sensor" as Category, weight: 0.03 },
];

export const CATEGORIES: { key: Category; labelKey: string }[] = [
    { key: "all", labelKey: "methods.catAll" },
    { key: "pixel", labelKey: "methods.catPixel" },
    { key: "frequency", labelKey: "methods.catFrequency" },
    { key: "statistical", labelKey: "methods.catStatistical" },
    { key: "metadata", labelKey: "methods.catMetadata" },
    { key: "sensor", labelKey: "methods.catSensor" },
];

export const CAT_COLORS: Record<Category, string> = {
    all: "",
    pixel: "cat-pixel",
    frequency: "cat-frequency",
    statistical: "cat-statistical",
    metadata: "cat-metadata",
    sensor: "cat-sensor",
};
