import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "SourceVerify — AI-Generated Content Detector",
  description:
    "Advanced AI detection tool that analyzes images and videos to determine if they were generated by artificial intelligence. Free, fast, and privacy-focused.",
  keywords: [
    "AI detection",
    "deepfake detection",
    "AI-generated image",
    "fake image detector",
    "AI content verification",
    "source verify",
  ],
  openGraph: {
    title: "SourceVerify — AI-Generated Content Detector",
    description:
      "Detect AI-generated images and videos with advanced analysis techniques.",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&family=JetBrains+Mono:wght@400;500;600&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="bg-noise bg-grid">{children}</body>
    </html>
  );
}
