import type { Metadata, Viewport } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-jetbrains",
  weight: ["400", "500", "600"],
});

export const viewport: Viewport = {
  themeColor: "#0a0a0f",
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
};

export const metadata: Metadata = {
  metadataBase: new URL("https://sourceverify.app"),
  title: {
    default: "SourceVerify — AI-Generated Content Detector",
    template: "%s | SourceVerify",
  },
  description:
    "Advanced AI detection tool that analyzes images and videos to determine if they were generated by artificial intelligence. Free, fast, privacy-first — all processing runs locally in your browser.",
  keywords: [
    "AI detection",
    "deepfake detection",
    "AI-generated image",
    "fake image detector",
    "AI content verification",
    "source verify",
    "AI image checker",
    "deepfake checker",
  ],
  authors: [{ name: "SourceVerify" }],
  creator: "SourceVerify",
  publisher: "SourceVerify",
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  openGraph: {
    title: "SourceVerify — AI-Generated Content Detector",
    description:
      "Detect AI-generated images and videos with advanced multi-signal analysis. Free, fast, and privacy-first.",
    type: "website",
    siteName: "SourceVerify",
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: "SourceVerify — AI-Generated Content Detector",
    description:
      "Detect AI-generated images and videos with advanced multi-signal analysis. Free, fast, and privacy-first.",
  },
  alternates: {
    canonical: "https://sourceverify.app",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${jetbrainsMono.variable}`}>
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "WebApplication",
              name: "SourceVerify",
              description:
                "Advanced AI detection tool that analyzes images and videos to determine if they were generated by artificial intelligence.",
              url: "https://sourceverify.app",
              applicationCategory: "Utility",
              operatingSystem: "Web Browser",
              offers: {
                "@type": "Offer",
                price: "0",
                priceCurrency: "USD",
              },
              featureList: [
                "Multi-signal AI detection",
                "Image and video analysis",
                "Client-side processing",
                "Privacy-first — no data uploaded",
              ],
            }),
          }}
        />
      </head>
      <body className="bg-noise bg-grid">{children}</body>
    </html>
  );
}
