/**
 * Fix TEMPLATE_MECH - Video methods batch 2 (C-D)
 */
const fs = require('fs');
const path = require('path');

const mechanisms = {
  'video/cheek_texture': `This method analyzes cheek skin texture patterns across video frames for deepfake detection:\n\n1. **Cheek Region Extraction**: Using facial landmarks, the cheek regions (below the zygomatic bone, lateral to the nose, above the jawline) are precisely segmented per frame. The regions are geometrically normalized to compensate for head pose variations, enabling consistent texture comparison across frames.\n\n2. **Micro-Texture Analysis**: High-frequency texture features — pores, fine wrinkles, skin grain, and sebaceous patterns — are extracted using Gabor filters and Local Binary Pattern (LBP) descriptors. Real human cheek skin exhibits a characteristic multi-scale texture hierarchy determined by dermatological structure.\n\n3. **Texture Temporal Consistency**: The micro-texture signature of cheek regions is tracked across consecutive frames. In authentic video, skin micro-texture remains stable (pores don't move or disappear between frames). Deepfake generators often produce inconsistent frame-to-frame micro-texture — pores may appear, disappear, or shift position as the generator independently synthesizes each frame.\n\n4. **Skin Rendering Quality Assessment**: The statistical properties of cheek texture (histogram of oriented gradients, spatial frequency distribution) are compared against natural skin models. AI-generated cheeks tend to be either over-smoothed (lacking natural pore detail) or show artificial texture patterns with repetitive structures uncommon in real skin.\n\n5. **Illumination-Independent Texture Scoring**: Texture features are computed in illumination-invariant color spaces to separate genuine texture from illumination effects. The final score quantifies the deviation of cheek texture from expected natural skin characteristics and its temporal stability across frames.`,

  'video/chin_jaw_detail': `This method analyzes chin and jawline detail for deepfake detection:\n\n1. **Jawline Contour Extraction**: Facial landmarks along the mandible and chin are tracked per frame to extract the jawline contour. The contour is parameterized using curvature measures, capturing the anatomical shape signature unique to each individual.\n\n2. **Sub-Mandibular Region Analysis**: The region beneath the chin and along the jawline is examined for anatomical detail — skin folds, adipose tissue distribution, and the chin-neck junction. These areas are challenging for deepfake generators because they occur at the boundary of the face-swap region and often exhibit generation artifacts.\n\n3. **Temporal Contour Stability**: The jawline contour is tracked across frames during speech and head movement. Natural jawlines deform smoothly according to musculoskeletal constraints — the mandible rotates on the temporomandibular joint with predictable kinematics. Deepfake-generated jawlines may exhibit unnatural deformations, warping, or contour instability.\n\n4. **Jaw-Neck Boundary Coherence**: The boundary between the face-generated region and the original neck/body is a critical artifact location for face-swap deepfakes. The method analyzes texture, color, and geometric continuity at this boundary — discontinuities indicate where the generated face mesh fails to blend seamlessly with the original body.\n\n5. **Detail Resolution Assessment**: Fine details along the jawline (stubble, skin texture, moles) are analyzed for rendering quality and temporal consistency. Deepfake generators often produce lower-resolution detail in peripheral face regions (chin, jaw) compared to central regions (eyes, nose), creating a detectable detail gradient.`,

  'video/chroma_bleed': `This method detects chroma bleeding artifacts for video forensic analysis:\n\n1. **Chroma Subsampling Analysis**: Video codecs (H.264/H.265) use chroma subsampling (4:2:0, 4:2:2) where chrominance has lower resolution than luminance. The method analyzes whether chroma-luma relationships follow the expected subsampling pattern. Manipulated or AI-generated regions may exhibit chroma bleeding inconsistent with the video's declared subsampling scheme.\n\n2. **Color Channel Edge Alignment**: At sharp edges, the luma (Y) channel shows a precise boundary while chroma channels (Cb, Cr) show slightly broader edges due to subsampling. The method measures the spatial offset between luminance and chrominance edges. Natural video shows consistent chroma spread matching the codec's subsampling. Deepfake insertion may produce regions with different chroma edge characteristics.\n\n3. **Cross-Channel Correlation**: In authentic video, chroma bleeding patterns are consistent across the entire frame (same codec pipeline). The method computes local cross-channel correlations and flags regions where chroma-luma relationships differ from the frame average — indicating content from a different encoding pipeline.\n\n4. **Temporal Chroma Stability**: Chroma bleeding characteristics should remain temporally consistent. The method tracks chroma-luma edge relationships across frames. AI-generated content may produce temporally varying chroma artifacts as the generator independently renders chrominance without modeling the encoding pipeline's subsampling behavior.\n\n5. **Re-Encoding Detection**: Double-encoded video (original + manipulation + re-encoding) produces characteristic double-chroma-bleeding artifacts. The method detects these compound artifacts by analyzing the spectral signature of chroma bleeding, which differs between single-pass and multi-pass encoding chains.`,

  'video/clothing_edge_blend': `This method analyzes clothing-body edge blending for deepfake detection following Rossler et al. (2019):\n\n1. **Clothing Boundary Detection**: The boundary between clothing and body/face regions is detected per frame using semantic segmentation. Clothing edges (collar-neck junction, sleeve-arm boundary, neckline) are extracted and parameterized.\n\n2. **Edge Blend Zone Analysis**: In authentic video, clothing-body boundaries show physically correct transitions — fabric partially occluding skin, compression of fabric at pressure points, natural draping creating soft shadows. The method measures the blend zone width, gradient profile, and shadow consistency at clothing boundaries.\n\n3. **Face-Swap Boundary Detection**: Face-swap deepfakes must blend the generated face with the original body/clothing. The method specifically examines the collar-neck-jawline junction where this blending occurs. Artifacts include: unnatural alpha blending gradients, color temperature discontinuities, and resolution mismatches between generated face and original clothing.\n\n4. **Temporal Edge Coherence**: Clothing-body edges should move coherently with body motion. The method tracks edge positions across frames and measures temporal consistency. Deepfake artifacts may cause clothing edges to flicker, teleport, or exhibit motion decoupled from the body's physical movement.\n\n5. **Occlusion Consistency**: Natural clothing creates consistent occlusion patterns — a collar always covers the same neck region from a given angle. The method checks whether occlusion relationships between clothing and body remain physically consistent across frames and head pose changes. Deepfakes may produce impossible occlusion states where generated face regions incorrectly overlap with original clothing.`,

  'video/clothing_fold': `This method analyzes clothing fold physics for deepfake detection following Zheng et al. (2021):\n\n1. **Fold Pattern Detection**: Clothing folds (wrinkles, creases, draping patterns) are detected using oriented gradient analysis and ridge/valley detection. Each fold is characterized by its orientation, depth (shadow intensity), and spatial extent.\n\n2. **Physical Plausibility Analysis**: Clothing fold patterns should be physically consistent with fabric properties and body pose. The method verifies: (a) folds radiate from stress points (elbows, shoulders, waistband), (b) fold orientation follows fabric grain direction, (c) fold depth corresponds to fabric weight. AI-generated clothing may produce physically implausible fold patterns.\n\n3. **Temporal Fold Dynamics**: As the body moves, clothing folds should evolve according to fabric physics — new folds form at flexion points, existing folds shift and merge. The method tracks fold evolution across frames. Deepfake generators may produce clothing folds that appear/disappear abruptly or don't respond naturally to body movement.\n\n4. **Fold-Body Coordination**: Clothing fold changes should correlate with body motion — arm movement creates shoulder/sleeve folds, torso rotation shifts front panel draping. The method measures temporal correlation between detected body motion and fold pattern changes. Low correlation indicates AI generation where clothing is rendered independently of body dynamics.\n\n5. **Rendering Consistency Scoring**: The spatial frequency content of clothing fold regions is analyzed. Real fabric folds show consistent texture quality with the rest of the image. AI-generated folds may show resolution disparities, unnatural smoothness, or repetitive patterns absent in real fabric. The score combines physical plausibility, temporal dynamics, and rendering quality assessments.`,

  'video/color_bleeding': `This method detects color bleeding artifacts in video for forensic manipulation detection:\n\n1. **Color Channel Decomposition**: The video is decomposed into YCbCr color space, separating luminance from chrominance. Color bleeding — where color information \"leaks\" across sharp boundaries — is analyzed by examining chrominance gradients at luminance edges.\n\n2. **Boundary Color Spread Measurement**: At high-contrast edges, the spatial spread of color transitions is measured. Natural color bleeding follows predictable patterns determined by the camera's sensor (Bayer demosaicing) and lens (chromatic aberration). AI-generated content may produce color bleeding that doesn't match any physical imaging model.\n\n3. **Codec-Consistent Bleeding Verification**: Video compression produces characteristic color bleeding through chroma subsampling and DCT block boundaries. The method verifies that observed color bleeding is consistent with the video's codec and encoding parameters. Manipulated regions encoded separately may show different bleeding characteristics.\n\n4. **Temporal Color Bleeding Consistency**: Color bleeding patterns should remain stable across frames for static edges and change predictably with motion. The method tracks color bleeding signatures temporally — deepfake insertion may cause temporal variations in bleeding patterns at manipulation boundaries.\n\n5. **Cross-Region Bleeding Comparison**: Color bleeding characteristics should be uniform across the frame (same imaging pipeline). The method compares bleeding patterns between face regions and background. Composited deepfake faces may exhibit different color bleeding than the original background footage, indicating content from different sources.`,

  'video/color_hist_shift': `This method detects temporal color histogram shifts for video deepfake detection following Zheng et al. (2021):\n\n1. **Per-Frame Color Histogram Computation**: For each frame, color histograms are computed in multiple color spaces (RGB, HSV, Lab) across face and background regions separately. Histograms capture the overall color distribution with bin resolution tuned to detect subtle shifts.\n\n2. **Inter-Frame Histogram Comparison**: Consecutive frame histograms are compared using Earth Mover's Distance (EMD), chi-squared distance, and Bhattacharyya distance. Natural video shows smooth, gradual histogram evolution. Deepfakes may produce frame-to-frame color distribution jumps, especially when the face generator's color model differs from the source video.\n\n3. **Face-Background Color Coherence**: The color histogram relationship between face regions and background is analyzed per frame. In authentic video, face and background share the same white balance and color grading. Deepfake face insertion may introduce subtle color distribution mismatches — the generated face may have different color temperature or saturation characteristics than the background.\n\n4. **Temporal Color Stability Analysis**: Long-term color histogram trends are tracked. Natural illumination changes produce smooth, physically motivated color shifts (gradual, affecting all regions similarly). Deepfakes may produce oscillating or jerky color histogram changes as the generator struggles to maintain consistent color rendering across frames.\n\n5. **Histogram Anomaly Scoring**: Statistical tests detect frames with significant color histogram deviations from temporal neighbors. The score combines inter-frame stability, face-background coherence, and long-term trend analysis, quantifying the likelihood of color manipulation or AI generation artifacts.`,

  'video/color_quant_v': `This method analyzes color quantization patterns in video for forensic detection:\n\n1. **Color Precision Analysis**: The effective number of distinct colors per frame is measured and compared to the expected color depth of the video format. Natural video captured at 8-bit depth shows characteristic color quantization patterns including smooth gradient banding. AI-generated content may exhibit different quantization characteristics — either smoother (floating-point internal representation posterized to 8-bit) or with artificial color clustering.\n\n2. **Quantization Step Detection**: Color channel histograms are analyzed for quantization artifacts — periodic gaps or peaks in the histogram indicate specific quantization step sizes. Double-quantization from re-encoding produces characteristic paired histogram features detectable via spectral analysis of the histogram signal.\n\n3. **Spatial Quantization Consistency**: Quantization patterns should be spatially uniform (same encoding pipeline). The method compares quantization characteristics between face regions and background. Deepfake composites may show different quantization in the generated face (from the generator's output pipeline) versus the original background footage.\n\n4. **Gradient Banding Analysis**: Smooth gradients in the image reveal quantization characteristics. Natural camera capture plus compression produces specific banding patterns. AI-generated gradients may show finer or coarser banding inconsistent with the declared bit depth and codec, revealing post-processing or generation artifacts.\n\n5. **Temporal Quantization Tracking**: Color quantization characteristics are tracked across frames. Authentic video maintains consistent quantization throughout. AI-generated content may show varying quantization quality across frames, particularly in face regions where the generator's output precision may fluctuate.`,

  'video/color_temporal_shift': `This method detects temporal color shifts in video for deepfake detection following Zheng et al. (2021):\n\n1. **Color Channel Signal Extraction**: Per-frame mean values of R, G, B channels (and derived Lab, HSV values) are extracted separately for face and background regions. These form temporal color signals tracking the color evolution of each region over time.\n\n2. **Drift Rate Analysis**: The rate of color change across frames is computed. Natural video shows either stable colors (controlled lighting) or smooth drifts (changing daylight). Deepfakes may introduce subtle but detectable frame-to-frame color oscillations as the generator independently determines color for each frame.\n\n3. **Face-Background Color Coupling**: In authentic video, face and background color signals are physically coupled — both respond to the same illumination changes. The method measures temporal correlation between face and background color channels. Low correlation indicates the face is generated independently, lacking physical illumination coupling with the background.\n\n4. **Color Temperature Consistency**: The correlated color temperature (CCT) of illumination is estimated per frame from color channel ratios. Natural lighting produces consistent CCT across all scene regions. Deepfake faces may be rendered with different effective color temperature than the background, creating detectable inter-region CCT disagreement.\n\n5. **Spectral Analysis of Color Signals**: The temporal color signals are analyzed via FFT. Natural color variation shows specific spectral characteristics (low-frequency illumination changes, camera AGC periodicity). AI-generated color variation may show different spectral signatures — higher-frequency fluctuations from frame-independent rendering or aliased patterns from the generation process.`,

  'video/contour_continuity': `This method analyzes facial contour continuity for deepfake detection following Li et al. (2020) Face X-ray:\n\n1. **Facial Contour Extraction**: The complete facial contour — forehead hairline, temple, cheekbone, jawline, chin — is traced per frame using high-resolution edge detection and facial landmark interpolation. The contour is parameterized as a smooth curve with measured curvature at each point.\n\n2. **Curvature Continuity Analysis**: Natural facial contours are C² continuous (smooth second derivative) except at anatomical feature boundaries (chin point, jaw angle). The method detects breaks in curvature continuity — deepfake face swaps may produce contour kinks or unnaturally straight segments where the generated face mesh interfaces with the original face boundary.\n\n3. **Contour-Skin Boundary Analysis**: Following Li et al.'s Face X-ray approach, the method examines the blending boundary between the face and surrounding area. Authentic faces have seamless continuation from face to neck/hair. Deepfakes create a detectable blending boundary where the generated face patch meets the original footage, visible as subtle texture or color discontinuities along the contour.\n\n4. **Temporal Contour Tracking**: The facial contour is tracked across frames. Natural contours deform smoothly according to facial muscles and head rotation. Deepfake contours may exhibit temporal jitter — small frame-to-frame fluctuations in contour position inconsistent with smooth physical motion, caused by independent per-frame face generation.\n\n5. **Multi-Scale Contour Scoring**: Contour continuity is analyzed at multiple scales: coarse (overall shape), medium (local curvature), and fine (pixel-level edge quality). Natural faces show consistent quality at all scales. Deepfakes may show good coarse continuity but poor fine-scale continuity at blending boundaries, yielding a graded forensic score.`,

  'video/contrast_temporal': `This method detects temporal contrast anomalies for video deepfake detection:\n\n1. **Local Contrast Mapping**: Per frame, local contrast (RMS contrast, Michelson contrast) is computed in sliding windows across the image. This creates a contrast map revealing spatial distribution of image contrast — bright/dark transitions, texture contrast, and edge strength.\n\n2. **Temporal Contrast Signal Extraction**: The mean and distribution statistics of local contrast are tracked across frames. Natural video shows smooth contrast evolution governed by illumination changes and scene dynamics. The contrast temporal signal captures how overall and regional contrast varies over time.\n\n3. **Face-Background Contrast Coherence**: Contrast characteristics of face regions and background are compared temporally. In authentic video, both regions respond identically to illumination changes. Deepfake face insertion may create contrast mismatches — the generated face may have different dynamic range or contrast characteristics than the background, detectable as divergent contrast temporal signals.\n\n4. **Contrast Flicker Detection**: Frame-to-frame contrast variations are analyzed for abnormal flicker. Natural contrast changes are slow (illumination) or physically motivated (object motion). AI-generated video may produce micro-contrast fluctuations as the generator independently determines contrast per frame, creating a detectable temporal frequency signature.\n\n5. **Histogram-Based Contrast Analysis**: Per-frame histograms are analyzed for dynamic range utilization across time. Natural video maintains consistent histogram shape evolution. Generated content may show abrupt histogram changes or unnatural histogram shapes (e.g., truncated dynamic range, bimodal distributions) indicating AI generation.`,

  'video/depth_consistency': `This method analyzes depth consistency across video frames for deepfake and manipulation detection:\n\n1. **Monocular Depth Estimation**: Per-frame relative depth maps are estimated using monocular depth cues: texture gradients, defocus, atmospheric perspective, relative size, and occlusion relationships. Each pixel receives a relative depth value consistent with the scene geometry.\n\n2. **Temporal Depth Stability**: Depth maps across consecutive frames should show smooth, physically motivated changes. The method tracks depth map evolution — natural scene depth changes are caused by camera motion (smooth, globally coherent) or object motion (local, bounded). Deepfakes may produce temporally unstable depth maps, especially at face-swap boundaries where generated face depth differs from the original face geometry.\n\n3. **Face-Scene Depth Integration**: The depth relationship between the face and surrounding scene must be consistent. The method checks: (a) face depth varies correctly with camera distance, (b) face depth matches nearby objects at similar distances, (c) face depth changes are consistent with measured face scale changes. Composited deepfake faces may show depth inconsistencies with the scene.\n\n4. **Depth-Defocus Consistency**: Estimated depth should correlate with defocus blur — objects at similar depths should show similar focus. The method cross-validates depth estimates against local defocus measures. AI-generated faces may show incorrect depth-defocus relationships, appearing sharp at depths where the background is blurred (or vice versa).\n\n5. **3D Geometric Consistency Scoring**: The implied 3D geometry is checked for physical plausibility. Face orientation (from landmarks) should produce consistent depth gradients. Perspective distortion should match the estimated camera parameters. Violations of geometric consistency indicate manipulation, yielding an elevated forensic score.`
};

let fixed = 0;
for (const [methodPath, newMechanism] of Object.entries(mechanisms)) {
  const enPath = path.join('src/app/methods', methodPath, 'i18n', 'en.json');
  try {
    const data = JSON.parse(fs.readFileSync(enPath, 'utf8'));
    data.mechanism = newMechanism;
    fs.writeFileSync(enPath, JSON.stringify(data, null, 2), 'utf8');
    fixed++;
    console.log(`✓ ${methodPath}`);
  } catch (err) {
    console.log(`✗ ${methodPath}: ${err.message}`);
  }
}
console.log(`\nFixed: ${fixed}/${Object.keys(mechanisms).length}`);
