/**
 * Fix TEMPLATE_MECH - Video methods batch 8a (spatial through tongue)
 */
const fs = require('fs');
const path = require('path');

const mechanisms = {
  'video/spatial_freq_temporal': `This method analyzes the temporal behavior of spatial frequency content across video frames for deepfake detection:\n\n1. **Per-Frame Spatial Frequency Decomposition**: Each frame is decomposed into spatial frequency bands via 2D FFT or wavelet transform. The energy at each spatial frequency is tracked over time, creating a 3D representation (spatial frequency × orientation × time).\n\n2. **Frequency Stability Analysis**: For static regions, the spatial frequency content should remain stable across frames. The method measures temporal variance at each spatial frequency. Deepfake generation may produce temporally varying frequency content — particularly at high frequencies where generation artifacts fluctuate frame-to-frame.\n\n3. **Face-Background Frequency Coherence**: The temporal behavior of spatial frequencies in face regions vs. background should be similar (same imaging pipeline). The method compares temporal frequency stability between regions. Different temporal stability characteristics indicate different generation/capture sources.\n\n4. **Spectral Flicker Detection**: The method detects temporal oscillations in specific spatial frequency bands. These \"spectral flickers\" can arise from: (a) GAN training instabilities producing oscillating artifacts, (b) autoencoder quantization varying between frames, (c) frame-rate conversion creating frequency-domain beating patterns.\n\n5. **Natural Image Statistics Temporal Consistency**: Natural images follow the 1/f spatial frequency power spectrum (scale invariance). This relationship should hold consistently across frames. The method tracks the spectral slope over time — systematic temporal variations in the 1/f exponent indicate processing artifacts from AI generation.`,

  'video/spectral_flicker_v': `This method detects spectral flicker artifacts for video deepfake detection:\n\n1. **Frequency-Domain Temporal Analysis**: The spatial frequency spectrum is computed per frame, and frame-to-frame spectral changes are quantified. Spectral flicker is defined as temporal oscillation in the energy of specific spatial frequency bands that doesn't correspond to scene content changes.\n\n2. **Band-Specific Flicker Detection**: Different spatial frequency bands are monitored independently. The method detects oscillating energy in specific bands — GANs may produce characteristic flicker at their architecture-specific frequencies (related to upsampling layers), while diffusion models may show flicker in mid-frequency bands during denoising step transitions.\n\n3. **Flicker Periodicity Analysis**: The temporal periodicity of detected spectral flicker is analyzed via autocorrelation. Periodic flicker (at regular intervals) indicates systematic generation artifacts. Natural spectral variation is aperiodic (random scene changes) or very low frequency (illumination changes).\n\n4. **Flicker Spatial Localization**: Spectral flicker is analyzed per image region. The method maps flicker intensity across the frame — flicker concentrated in face regions but absent in background strongly indicates face generation artifacts. Whole-frame flicker may indicate post-processing artifacts.\n\n5. **Flicker Frequency Scoring**: The detected flicker is scored based on: (a) temporal frequency of flicker (physiologically irrelevant frequencies indicate artifacts), (b) spatial frequency bands affected, (c) spatial localization to face region, (d) periodicity strength. High scores indicate AI generation.`,

  'video/specular_highlight': `This method analyzes specular highlights for deepfake detection:\n\n1. **Highlight Detection**: Specular highlights (bright spots from direct light reflection) are detected across the frame on all surfaces — skin, eyes, glasses, jewelry, objects. Highlights are identified by local maximum intensity exceeding neighbors by a threshold.\n\n2. **Highlight-Light Source Consistency**: All specular highlights in the scene should be consistent with the same light source configuration. Using highlight positions and surface geometry, the method estimates implied light directions. All highlights should point to consistent light source positions. Deepfakes may produce highlights with inconsistent implied light directions.\n\n3. **Highlight Shape Analysis**: The shape of specular highlights encodes surface curvature — highlights on flat surfaces appear as points, on curved surfaces as elongated reflections following surface curvature. The method checks highlight shapes against estimated surface geometry. AI-generated highlights may have shapes inconsistent with the underlying geometry.\n\n4. **Highlight Intensity & Physics**: Specular highlight intensity follows the Fresnel equations — brighter at grazing angles, with material-dependent characteristics. The method verifies highlight intensity follows physical reflectance models. AI generators may produce highlights with incorrect intensity patterns.\n\n5. **Temporal Highlight Dynamics**: As objects move, specular highlights should move according to the changing reflection angle. The method tracks highlight motion — highlights should move faster than texture features for convex surfaces (virtual image effect). Incorrect highlight dynamics indicate AI generation without proper reflectance modeling.`,

  'video/stabilization': `This method detects video stabilization artifacts for forensic analysis:\n\n1. **Camera Motion Estimation**: Global camera motion is estimated from background feature tracking — translation, rotation, and zoom components per frame. The raw (unstabilized) camera motion trajectory is reconstructed.\n\n2. **Stabilization Artifact Detection**: Video stabilization smooths camera motion by applying compensating transforms. This produces characteristic artifacts: (a) cropped borders (stabilization reduces effective field of view), (b) warping residuals from rolling shutter correction, (c) motion blur inconsistent with the displayed (stabilized) motion.\n\n3. **Double Stabilization Detection**: If a deepfake video is stabilized and then the original footage was also stabilized, double-stabilization produces characteristic artifacts: excessive border cropping, over-smoothed motion (unnatural zero jitter), and cumulative warping residuals.\n\n4. **Face-Background Motion Consistency**: After de-stabilization, the apparent motion of the face and background should be consistent with the same camera motion. If the face was generated and composited, its motion may not match the camera motion recovered from the background, creating a detectable motion inconsistency.\n\n5. **Stabilization History Analysis**: The method estimates whether and how many times the video was stabilized. Each stabilization pass leaves a characteristic imprint on the motion trajectory (reduced high-frequency components). Multiple stabilization passes indicate the video has been processed multiple times — consistent with a manipulation → re-stabilization pipeline.`,

  'video/teeth': `This method analyzes teeth rendering and consistency for deepfake detection:\n\n1. **Teeth Detection & Segmentation**: When the mouth is open during speech or smiling, visible teeth are detected and segmented. Individual teeth boundaries, alignment, and arrangement are analyzed per frame.\n\n2. **Dental Anatomy Verification**: The method checks dental anatomy: (a) correct tooth count for visible region, (b) proper tooth shapes (incisors, canines, premolars with distinct morphology), (c) realistic tooth size and spacing, (d) gum line contour. AI generators often produce blurred, merged, or anatomically incorrect teeth — too many, too few, or with impossible shapes.\n\n3. **Teeth Texture & Color**: Real teeth show characteristic features: translucency at the incisal edge, varying color (slightly yellow body, whiter enamel surface), surface texture (microlines, stain patterns). The method evaluates teeth rendering quality. Generated teeth are often unrealistically white, uniformly colored, or lacking surface detail.\n\n4. **Temporal Teeth Stability**: Teeth structure is completely rigid — tooth positions, sizes, and arrangement cannot change between frames. The method tracks teeth geometry frame-to-frame. Changes in visible tooth arrangement (teeth appearing/disappearing, changing shape) indicate AI generation where teeth are rendered independently per frame.\n\n5. **Teeth-Lip Interaction**: During speech, lips interact with teeth in specific ways — upper teeth visible during /f/ and /v/ sounds, teeth edges visible during particular articulations. The method checks teeth-lip coordination. Deepfakes may show teeth visibility that doesn't correlate with the spoken phonemes.`,

  'video/temporal_coherence_map': `This method creates temporal coherence maps for deepfake detection:\n\n1. **Feature Tracking Across Frames**: Dense feature correspondences are established between consecutive frames using optical flow, and long-range correspondences across multiple frames using feature matching. This creates a spatio-temporal feature trajectory map.\n\n2. **Local Coherence Computation**: For each pixel, temporal coherence is computed as the consistency of its feature trajectory — smooth, physically plausible trajectories have high coherence, while erratic or discontinuous trajectories have low coherence. The coherence map reveals regions with temporal instability.\n\n3. **Coherence Map Spatial Analysis**: Natural video shows uniformly high coherence for static regions and physically motivated coherence patterns for moving objects. The method analyzes the coherence map for anomalous low-coherence regions — deepfake-generated areas often show reduced temporal coherence, particularly at face boundaries and in texture regions.\n\n4. **Face-Background Coherence Comparison**: The average coherence in face regions vs. background provides a diagnostic ratio. In authentic video, both show similar coherence levels. Deepfakes typically show lower coherence in the generated face (per-frame independent generation) compared to the naturally captured background.\n\n5. **Coherence Temporal Trends**: The per-frame average coherence is tracked over time. Natural video maintains high, stable coherence. Deepfake videos may show coherence drops correlated with challenging face poses, expressions, or lighting conditions where the generator produces more temporally inconsistent output.`,

  'video/temporal_color_histogram': `This method analyzes temporal color histogram evolution for deepfake detection:\n\n1. **Regional Color Histograms**: Per-frame color histograms are computed for multiple regions: face, skin, hair, background, and clothing. Histograms use perceptually uniform color bins (Lab color space) for meaningful color comparison.\n\n2. **Histogram Temporal Smoothness**: The evolution of color histograms over time should be smooth. The method measures frame-to-frame histogram distance (EMD, chi-squared) and detects anomalous spikes. Deepfake generation may produce frame-to-frame color distribution jumps as the generator's color output varies.\n\n3. **Inter-Region Histogram Correlation**: Color changes in different regions should be correlated (same illumination affects all regions similarly). The method checks temporal correlation between regional histograms. Low face-background histogram correlation indicates the face color evolves independently from scene lighting — a deepfake signature.\n\n4. **Histogram Shape Analysis**: The shape of color histograms encodes content characteristics. The method tracks histogram shape metrics (modes, spread, skewness) over time. Authentic video maintains consistent histogram shapes within the same scene. Deepfake generation may produce fluctuating histogram shapes.\n\n5. **Long-Range Histogram Consistency**: The method compares histograms between frames separated by longer intervals. Scenes with stable lighting should show consistent histograms regardless of temporal distance. Systematic histogram drift without lighting change indicates gradual color shift from AI generation artifacts.`,

  'video/temporal_face_embedding': `This method analyzes temporal face embedding drift for deepfake detection:\n\n1. **Face Embedding Extraction**: A face recognition embedding vector is computed per frame using a pre-trained face recognition network. The embedding captures identity-discriminative features in a high-dimensional space.\n\n2. **Embedding Trajectory Analysis**: The face embedding trajectory through the embedding space is tracked over time. In authentic video, the embedding remains near a fixed point (same identity) with small perturbations from expression, pose, and illumination changes.\n\n3. **Drift Detection**: The method detects systematic embedding drift — gradual movement of the embedding centroid over time. In authentic video, the centroid is stationary. Deepfake generators may produce slowly drifting identity characteristics as the model's latent space traversal creates gradual identity shifts.\n\n4. **Embedding Variance Analysis**: The variance of embeddings across frames is analyzed. Authentic video shows low variance (consistent identity). Deepfakes may show elevated variance — the generated face may fluctuate in identity space, sometimes closer to the source identity, sometimes to the target identity, creating detectable identity instability.\n\n5. **Embedding-Pose Correlation**: Embedding should be pose-invariant for a fixed identity (good face recognition models achieve this). The method checks whether embedding changes correlate with head pose — deepfake quality may be pose-dependent (better at frontal, worse at profile), causing embedding to shift with pose in ways that don't occur with authentic faces.`
};

let fixed = 0;
for (const [methodPath, newMechanism] of Object.entries(mechanisms)) {
  const enPath = path.join('src/app/methods', methodPath, 'i18n', 'en.json');
  try {
    const data = JSON.parse(fs.readFileSync(enPath, 'utf8'));
    data.mechanism = newMechanism;
    fs.writeFileSync(enPath, JSON.stringify(data, null, 2), 'utf8');
    fixed++;
    console.log(`✓ ${methodPath}`);
  } catch (err) {
    console.log(`✗ ${methodPath}: ${err.message}`);
  }
}
console.log(`\nFixed: ${fixed}/${Object.keys(mechanisms).length}`);
