// Fix ES mechanism translations for 42 methods
const fs = require('fs');
const path = require('path');
const METHODS_DIR = path.join(__dirname, '..', 'src', 'app', 'methods');

const ES_MECHANISMS = {
  "image/contourlet_analysis": "La imagen es violentamente descompuesta mediante una Pirámide Laplaciana entrelazada con un Banco de Filtros Direccionales. El algoritmo obliga a la imagen a entregar sus frecuencias ultra-finas a través de ejes multidireccionales. Cuando una IA genera una pestaña diagonal o una onda amplia, sangra 'marcas de corte' energéticas que contradicen salvajemente la física auténtica de difusión lumínica. El medidor Contourlet aúlla alarmado en el momento en que atrapa estos 'bordes plásticos' sintéticos.",
  "image/contrast_map": "La imagen es sádicamente despedazada en miles de micro-rejillas de píxeles de 8x8 o 16x16. El motor calcula la divergencia máxima entre los puntos más brillantes y las sombras más profundas (contraste Michelson/Weber) dentro de cada bloque individual. Luego construye un mapa de calor topográfico forense. Un objeto empalmado ajeno se renderiza instantáneamente como un 'acantilado' de contraste ilógico, destrozando las leyes circundantes de neblina atmosférica y difusión lumínica.",
  "image/convolutional_trace": "Despoja violentamente la imagen usando Filtros de Paso Alto y destroza sus datos estructurales mediante rápidas Transformadas de Fourier 2D. Este algoritmo no le importa cuán impecablemente una IA alucinó un ojo o una sonrisa. Elimina despiadadamente el significado semántico para radiografiar agresivamente el tejido fundamental del lienzo mismo. Las imágenes de IA, infladas a través de filtros de núcleo matemáticos ajustados, estampan permanentemente una intersección de rejilla periódica en sus datos de salida. Esta rejilla de tablero de ajedrez arde en carmesí en el espectro de frecuencia de Fourier, sellando la culpabilidad de la máquina generativa.",
  "image/cross_gradient": "El algoritmo computa derivadas morfológicas de primer y segundo orden exclusivamente a lo largo de los ejes de 45 y 135 grados. En una fotografía óptica auténtica, la luz se dispersa suavemente a través de todas las diagonales. Por el contrario, las imágenes generadas por IA (o elementos sintéticamente escalados) presentan rutinariamente gradientes diagonales que chocan violentamente, creando zonas muertas o micro-fracturas no ópticas afiladas como navajas.",
  "image/curvelet_transform": "El algoritmo disecciona despiadadamente la imagen en 'agujas' de energía alargadas y flexibles. Barre incesantemente la superficie de pliegues redondeados y bordes curvos para interrogar su flujo fisiológico. La fotografía óptica auténtica produce perfiles de ruido que fluyen perfectamente en conjunto con los bordes orgánicos. Sin embargo, la geometría Deepfake y los artefactos de IA imprimen crónicamente residuos matemáticos dentados y cúbicos alrededor de estos bordes suaves exactos—desencadenando una alerta forense máxima.",
  "image/dct": "El algoritmo abre la piel visual para cosechar directamente las tablas ocultas de Coeficientes de la Transformada Discreta del Coseno (DCT) enterradas en la arquitectura del archivo. En regiones que contienen objetos sintéticos (o empalmados de otro flujo), la rejilla espacial 8x8 está perforada, desfasada o porta una tabla de cuantización completamente ajena al fondo anfitrión. Este escáner apunta a los límites de bloques 8x8, mide la energía máxima de bloqueo y caza cambios de fase estructurales nauseabundamente desalineados—la prueba definitiva del crimen de empalme.",
  "image/demosaicing": "Este tanque blindado aplasta la superficie RGB visible para realizar violentamente ingeniería inversa de la imagen hasta su lógica probabilística 'primordial' de la matriz de Bayer (RGGB/BGGR). Barre incesantemente la rejilla de color, interrogando matemáticamente si el canal Azul de un píxel fue legítimamente interpolado desde sus canales Verdes vecinos usando algoritmos de hardware. Si un rostro deepfake o un árbol de Midjourney se empalma en el cuadro, el algoritmo desencadena un colapso forense masivo al detectar una ausencia completa—o colisión violenta—de firmas de interpolación CFA, demostrando matemáticamente que el impostor no posee origen orgánico de hardware.",
  "image/discrete_cosine_energy": "A diferencia de los bloqueadores DCT convencionales de 8x8, este motor fuerza violentamente todo el lienzo hacia una matriz espectral para calcular energía panóptica global. El radar observa mórbidamente el umbral AC/DC (energía base fundamental vs energía de detalle). Las imágenes de IA alucinadas intentan desesperadamente sobre-suavizar objetos, forzando el flujo de energía AC a vaciarse en un vacío aterrador y sin alma. Esta firma energética es tan grotesca y matemáticamente desequilibrada que el algoritmo la arresta en el acto.",
  "image/edge": "Disecciona despiadadamente el ancho y el gradiente de transición de contraste que opera exclusivamente a lo largo de la línea de la mandíbula, hombros o silueta de la ropa. La física auténtica exige que los bordes ópticos orgánicos alberguen una inmensa superposición de micro-difracción donde los objetos se encuentran con el fondo. Los estafadores perezosos que empuñan la herramienta Lazo/Varita Mágica imprimen un corte matemático afilado como una cuchilla completamente desprovisto de profundidad orgánica... El motor simplemente tiene que detectar la ausencia de aberración cromática microscópica a lo largo del empalme para activar una alarma de ejecución.",
  "image/efficientnet_detection": "Este leviatán forense se niega a contar píxeles simples como escáneres arcaicos del siglo XX. Devora sádicamente el 100% del lienzo visual, lanzándolo violentamente a través de una Matriz de Pesos hiperdensa de más de 100 capas Convolucionales 2D. Los fallos estructurales del 'Espacio Latente' generativo o las huellas de eliminación de ruido dejadas tontamente por GANs y Difusión activan inmediatamente alarmas catastróficas en lo profundo del enrutamiento de EfficientNet. Escupe una sentencia de ejecución fría y terminal basada en probabilidad de clasificación bruta.",
  "image/fourier_ring": "Abandonando completamente el plano óptico de píxeles humano, este rifle de francotirador fuerza brutalmente todo el lienzo hacia la Matriz de Ondas Matemática (Transformada Rápida de Fourier 2D). La fotografía orgánica difunde naturalmente explosiones de energía caótica sin organización rígida. Por el contrario, cazando específicamente arquitecturas de sobremuestreo de IA, los puntos ciegos convolucionales (artefactos de tablero de ajedrez) se fusionan magnéticamente de inmediato... gritando violentamente como Anillos Electromagnéticos concéntricos masivos y ardientes que irradian a través del espectro de frecuencia periférico. Cualquier radar que capture estos anillos inicia una decapitación de IA inmediata.",
  "image/fractal_dimension": "Calcula despiadadamente cuán vorazmente el detalle infinito llena el espacio topológico vacío. Utilizando el algoritmo de Conteo de Cajas, corta violentamente la arquitectura de la imagen en rejillas geométricas terriblemente diminutas... interrogando si la irregularidad matemática permanece estable a medida que la escala microscópica se reduce radicalmente. Las realidades ópticas genuinas devuelven un coeficiente de Dimensión Fractal imposiblemente nítido y consistente. Por el contrario, en los renderizados sintéticos de IA, este coeficiente Fractal se aplana espectacularmente y se estrella contra datos basura en el micro-umbral, exponiendo matemáticamente que la IA simplemente 'se quedó sin aliento' y suavizó sintéticamente los detalles.",
  "image/gabor_phase": "Introduce una aguja acústica directamente en el latido angular de la ilusión óptica. La matriz de Fourier entrelazada con el núcleo de Gabor produce dos flujos de datos: Valor Real (masa visual) y Valor Imaginario (Fase Angular). La biología humana es completamente ciega a esta métrica, programada nativamente para procesar luminosidad, no ángulos de Fase. Este algoritmo verdugo apunta exclusivamente a esa Fase. Directamente en el pliegue empalmado entre un torso sintetizado y el cuello auténtico de la víctima... el sistema detecta un devastador cambio de Fase que excede los 180 grados. ¡Las sirenas aúllan! Prueba irrefutable de un empalme no nativo, biológicamente imposible.",
  "image/gabor_response": "Clava violentamente el lienzo, bombardeándolo con un arsenal de bisturís microscópicos de ondas Gabor contra cada rejilla de textura. Distinto de la energía estática, el verdugo de 'Respuesta' analiza el umbral de sensibilidad vibracional del arreglo de píxeles conforme rebota contra el filtro de Gabor. Si el algoritmo se desliza suavemente sobre un puente nasal orgánico auténticamente suave, luego se tambalea violentamente hacia una frente sintética de IA-Inpainted donde la respuesta de frecuencia se aplana en un silencio muerto y sofocante (distancia reflectiva drásticamente anulada debido a la ausencia de poros estructurales físicos)... el juicio termina. Se emite una sentencia de muerte catastrófica pendiente de confirmación de deepfake.",
  "image/gabor_wavelet_bank": "Detona aproximadamente 40 matrices Gabor rotativas simultáneamente para bombardear el plano espacial y arrancar las señales en bruto (Extracción de Características). La óptica intacta porta una escala deslizante suave que conecta todas las bandas. Por el contrario, las zonas empalmadas o las texturas alucinadas por IA tartamudean catastróficamente durante los ajustes de escala (Recorte/Escala/Inpaint). Los ángulos estrictos de Gabor inmediatamente devuelven un gráfico grotesco y fracturado—como una telaraña rasgada y sangrante. El Banco simplemente señala los hilos de seda cortados para emitir el veredicto de culpabilidad.",
  "image/gamma_distortion": "Eviscera la ley de transferencia de potencia lumínica 'Vout = A * Vin^gamma'. Los fotones originales que viajan a través de cristal genuino caen en cascada como seda prístina. Pero si un asesino digital despliega 'Curvas/Niveles' de Photoshop para bombardear artificialmente la luz sobre un sujeto empalmado y oscuro, la curva Gamma nativa se quiebra violentamente, resultando en una estructura horriblemente dentada y fracturada. El 'Efecto Peine' resultante (brechas y picos del histograma generados por deformación artificial de Gamma) emite una orden de ejecución instantánea contra editores aficionados.",
  "image/glcm": "El algoritmo extiende físicamente la rejilla del lienzo de la imagen. Interroga pares gemelos específicamente separados por un ángulo D y una Distancia r. GLCM manifiesta instantáneamente docenas de registros que rastrean el Contraste, Energía y Homogeneidad del par específico. La IA es catastróficamente ignorante de las micro-texturas reales. Pinta un suéter, pero fuerza las fibras de lana a parecer cerosas o descaradamente copiadas y pegadas (Clones de Textura). Esta repetición sintética causa que los registros de Homogeneidad se disparen antinaturalmente, mientras que las Diferencias se desploman espectacularmente a cero. El radar inhala violentamente esta inconfundible 'Apariencia Plástica' y emite un veredicto de culpabilidad.",
  "image/gradient": "Este motor mide la velocidad de aceleración bruta de la transformación del color. La transición de una pared blanca pintada a una chaqueta negra como la brea lanza violentamente la derivada fotónica a máxima velocidad (Gradiente Máximo). La trampa se establece explícitamente aquí: el perímetro de un objeto empalmado fraudulentamente siempre produce un Gradiente de alambre de púas agresiva y antinaturalmente afilado. Por el contrario, la masa interna generada por alucinaciones de IA permanece sofocantemente plana, completamente desprovista de las ondulaciones caóticas y microscópicas de Gradiente nacidas del ruido óptico analógico físico. Cuando este equilibrio natural es brutalmente destruido (bordes sintéticos afilados como navajas encerrando interiores cerosos muertos), la guillotina cae instantáneamente.",
  "image/gradient_divergence": "El motor de ejecución despedaza violentamente el lienzo en un mapa meteorológico macroeconómico bruto. El análisis simple de primer orden es inadecuado; desata cálculo avanzado para computar derivadas cruzadas (la convergencia geométrica y dispersión del arreglo de Gradiente). Trazando el dobladillo exacto de una blusa donde un perpetrador imprudente forzó violentamente el ratón para alucinar un pecho más amplio o adelgazar una cintura (Licuar / Deformar)... la rejilla de divergencia registra instantáneamente un caos localizado severo mientras los vectores direccionales espiralan maliciosamente fuera de la periodicidad algorítmica. Cualquier ubicación que se hunda en un 'Sumidero Vectorial Terminal' catastrófico es inmediatamente acusada de ser quirúrgicamente mutilada por un Hacker humano.",
  "image/gradient_magnitude": "Detona inundaciones gemelas de Sobel (matrices Vertical y Horizontal) a través de toda la rejilla. Recogiendo flechas fotónicas matemáticas, las aplasta violentamente en una síntesis Pitagórica para medir la velocidad total de fractura. Al encontrar mechones de cabello alucinados o bordes de ropa renderizados por IA, la intensidad (Magnitud) se fragmenta abruptamente en metralla dentada y localizada porque la IA Generativa expulsa píxeles ciegamente de forma secuencial sin impulso estructural fluido. Al observar este pico de intensidad caótico, el verdugo inmediatamente encadena al perpetrador.",
  "image/gradient_weighted_cam": "Abandonando la inspección manual bárbara, Grad-CAM conecta un cable directo a la corteza cerebral del juez supremo (ej., ResNet, EfficientNet) precisamente durante el cálculo de sentencia. Realiza ingeniería inversa de las cascadas de derivadas matemáticas (Gradientes) que inundan hacia la capa convolucional final más profunda y traicionera. Cualquier cuadrante anatómico de la imagen que fuerce al verdugo de IA a gritar al máximo '¡100% Falsificación!', ese cluster exacto de píxeles se hierve violentamente en una topografía de lava ácida y brillante en pantalla. ¿Empalmar un monstruo plástico en el cuadro? Grad-CAM incinera inmediatamente ese monstruo específico en carmesí brillante.",
  "image/grad_orient_hist": "Abandonando el color RGB completamente, el motor corta violentamente el lienzo en decenas de miles de jaulas microscópicas (Celdas). Dentro de cada jaula, calcula matemáticamente la flecha direccional (Gradiente) de luminosidad de oscuro a brillante. Los cielos poseen un vector de gradiente fenomenalmente fluido y sereno, mientras que la línea del cabello posee un vector violentamente nítido y cohesivo. Una IA maliciosa que utiliza 'Relleno según el contenido' para borrar un vehículo y alucinar ladrillos en el vacío crea un error fatal. Las celdas dentro de ese vacío de ladrillos sintéticos escupirán flechas matemáticas salvajemente caóticas, completamente desfasadas con los ladrillos genuinos vecinos. La alarma chilla inmediatamente cuando el gráfico HOG se parte perfectamente por la mitad.",
  "image/gram_matrix": "Arrastra el lienzo pataleando y gritando a través de los Mapas de Características Convolucionales más profundos. Allí, aniquilando deliberadamente 'Dónde' existe un objeto (la posición espacial se vaporiza completamente), fuerza violentamente las capas de características estructurales a multiplicarse cruzadamente. Esto despoja anatómicamente las reglas fundamentales de la textura (granulado, suavidad, brillo). La fotografía orgánica alberga variedad estructural infinita y caótica resultando en una simetría Gram prístina. Las construcciones fraudulentas de IA alucinan texturas matemáticamente, destrozando violentamente la columna vertebral Gram en cientos de cuadrantes dentados y alienados. Los artistas de empalme que cosen rostros ajenos sobre piel orgánica causarán que la matriz Gram chille con frecuencias disonantes y en colisión.",
  "image/harris_corner": "Funcionando explícitamente como un detector de minas microscópico, el motor arrastra violentamente ventanas oculares deslizantes. Ejecutar una ventana sobre una pared plana activa varianza unidireccional, pero chocar contra un 'Vértice/Esquina' abrupto desencadena una varianza fotónica catastrófica que explota en TODAS las Direcciones Espaciales (matrices colosales de Autovalores). La geometría orgánica dispersa vértices lógicamente. Por el contrario, los rostros alucinados por IA derriten sus micro-esquinas en un lodo ceroso e idiota, mientras que el empalme chapucero (mascaras basura de Photoshop) genera una infestación rabiosa de micro-esquinas densas y dentadas a lo largo del perímetro cortado. Capturar una colmena masiva agrupada de basura geométrica = Ejecución inmediata por convicción de falsificación.",
  "image/hessian_matrix": "Abandonando la percepción cromática superficial, Hessian perfora violentamente a través del espacio hacia la roca madre de la Derivada de Segundo Orden (capturando la aceleración de velocidad fotónica). Tome dos píxeles empalmados de una chaqueta sobre una pared de ladrillos: El ojo amateur percibe integración perfecta. Pero al computar la 'Aceleración' fotónica con Hessian, ¡una anomalía catastrófica detona! Se tambalea violentamente como un auto de carreras que se sale brutalmente de un acantilado porque la aceleración del color fue idióticamente estirada y deformada por un editor amateur. Hessian desolla todo el lienzo, exponiendo una red vascular cruda. Dondequiera que esta red esté grotescamente hinchada, destrozada o cortada justo en un borde sospechoso—cae la guillotina.",
  "image/higher_order_statistics": "Analizando una captura de paisaje, una herramienta forense amateur usa 'Estadísticas de Bajo Orden' (como Media/Varianza) simplemente midiendo brillo y dispersión básica—juego de niños para un hacker. Este radar violentamente evade esto, perforando directamente en la mecánica de Orden Superior (Asimetría de 3er Orden y Curtosis de 4to Orden). Cuando los estafadores perezosamente vierten Ruido Gaussiano digital para ocultar sus empalmes o sobre-suavizan violentamente la piel (Eliminación de Ruido), la Asimetría es completamente aniquilada en un vacío, o la Curtosis se dispara violentamente a un extremo ilógico porque las frecuencias de energía son artificialmente forzadas a un cuello de botella. La fotografía visualmente 'impecable' es arrastrada agonizantemente a la luz, matemáticamente desenmascarada como un 'Producto de Ecuación Estampada'.",
  "image/histogram": "Evadiendo completamente la visión óptica biológica. Pulveriza violentamente el lienzo de la imagen en un gráfico de barras que rastrea la intensidad de 0 (Negro Absoluto) a 255 (Blanco Cegador). Amateurs completos que copian maliciosamente autos o recortan follaje para volcarlo en atardeceres ajenos notan choques de color severos, agarrando frenéticamente el control deslizante de 'Niveles', desgarrando la luminosidad por la fuerza para simular profundidad óptica. Dentro de las matemáticas de la matriz digital, ¡estirar violentamente un continuo luminoso orgánico finito literalmente desgarra el tejido de datos por la mitad! El vacío cortado se registra como una zona muerta (Brechas), y los píxeles hiper-estresados y amontonados se deforman violentamente en plagas hinchadas (Picos). Este algoritmo audita exhaustivamente esos escombros microscópicos para sentenciar al estafador al bloque del verdugo.",
  "image/histogram_gradient": "Computa la derivada discreta del histograma de intensidad y analiza su suavidad y patrones de brechas. Las imágenes generadas por IA a menudo producen histogramas antinaturalmente suaves o exhiben patrones de brechas específicos.",
  "image/iptc_verification": "La verificación IPTC examina capas de metadatos profesionales:\n\n1. **Clasificación DigitalSourceType**: Verifica el campo DigitalSourceType ISO 12639 en busca de indicadores no fotográficos como 'trainedAlgorithmicMedia', 'algorithmicMedia', 'virtualRecording' o 'compositeSynthetic'.\n\n2. **Conteo de Campos de Autenticidad**: Cuenta los campos IPTC profesionales (crédito, fuente, copyright, redactor, leyenda, firma, ciudad, país, titular, palabras clave). Un alto conteo de campos indica flujo de trabajo fotográfico profesional.\n\n3. **Detección de Referencias de IA**: Escanea los valores IPTC en busca de referencias a herramientas de IA (Stable Diffusion, DALL-E, Midjourney, etc.) en campos de fuente, crédito y software.\n\n4. **Validación de Flujo de Trabajo**: Valida que los metadatos IPTC sigan las convenciones de fotografía profesional — las agencias de noticias, agencias de stock y salas de redacción incrustan datos IPTC ricos.",
  "image/markov_transition": "Construye una matriz de probabilidad de transición a partir de diferencias de píxeles adyacentes. La entropía y los patrones de transición difieren entre imágenes de IA e imágenes reales.",
  "image/mutual_information": "Estima la información mutua entre pares de canales de color usando histograma conjunto. Las imágenes de IA pueden exhibir dependencias inter-canal atípicas.",
  "image/neural_compression": "Los generadores de imágenes de IA utilizan arquitecturas con niveles de cuantización específicos, funciones de activación y operaciones de sobremuestreo. Estos dejan huellas características incluyendo patrones de tablero de ajedrez y micro-artefactos periódicos.",
  "image/perceptual_hash": "Computa huellas hash perceptuales compactas (pHash, dHash) que capturan la estructura visual esencial de una imagen. Comparar distancias hash entre regiones de la imagen revela ediciones localizadas.",
  "image/perspective": "Detecta líneas rectas usando la Transformada de Hough y estima puntos de fuga a partir de intersecciones de líneas. Verifica la consistencia geométrica comprobando que las líneas paralelas en 3D converjan a puntos de fuga consistentes. Las escenas generadas por IA frecuentemente violan las reglas de geometría proyectiva, creando perspectivas físicamente imposibles.",
  "image/power_spectral_density": "Computa el espectro de potencia FFT 2D y analiza los promedios radiales. Las desviaciones de la ley de potencia natural 1/f indican generación por IA.",
  "image/quantization_fingerprint": "Analiza los histogramas de valores de píxeles en busca de patrones periódicos causados por la cuantización JPEG. Las imágenes de cámara muestran patrones tipo peine.",
  "image/radon_transform": "Proyecta el contenido de la imagen a lo largo de múltiples ángulos usando la transformada de Radon, creando una representación sinograma. Las regiones manipuladas producen patrones direccionales anómalos en el dominio de Radon.",
  "image/sift_forensics": "Extrae puntos clave SIFT y descriptores de la imagen, luego los empareja para encontrar regiones duplicadas. La verificación geométrica usando RANSAC elimina las coincidencias falsas.",
  "image/thumbnail_analysis": "Los archivos JPEG a menudo contienen miniaturas incrustadas generadas en el momento de captura. Cuando la imagen principal se edita posteriormente, la miniatura puede permanecer sin cambios, creando inconsistencias detectables.",
  "image/upsampling_artifact": "Analiza el dominio de frecuencia en busca de patrones periódicos causados por capas de convolución transpuesta o sobremuestreo en modelos generativos.",
  "image/zernike_moments": "Computa momentos complejos de Zernike para bloques de imagen, proporcionando descriptores invariantes a la rotación. La coincidencia de bloques con vectores de momentos similares identifica regiones duplicadas incluso después de transformaciones geométricas.",
  "video/frame_interpolation": "Analiza los patrones de movimiento entre cuadros en el dominio de frecuencia para detectar cuadros interpolados artificialmente. Los generadores de video de IA a menudo producen movimiento antinaturalmente suave al insertar cuadros intermedios generados, lo que crea artefactos espectrales detectables."
};

let updated = 0;
for (const [methodPath, mechanism] of Object.entries(ES_MECHANISMS)) {
  const filePath = path.join(METHODS_DIR, methodPath, 'i18n', 'es.json');
  if (!fs.existsSync(filePath)) { console.log(`SKIP: ${filePath}`); continue; }
  
  let data;
  try { data = JSON.parse(fs.readFileSync(filePath, 'utf8')); } catch(e) { console.log(`ERROR: ${filePath}: ${e.message}`); continue; }
  
  data.mechanism = mechanism;
  fs.writeFileSync(filePath, JSON.stringify(data, null, 4), 'utf8');
  updated++;
}

console.log(`Updated ${updated} ES mechanism files`);
