/**
 * Fix TEMPLATE_MECH placeholder mechanisms with scientifically accurate descriptions
 * Batch 1: Image methods (15) + Text methods (1)
 */
const fs = require('fs');
const path = require('path');

const mechanisms = {
  // ===== IMAGE METHODS =====
  'image/hot_pixel': `Hot pixel detection exploits the unique photo-response non-uniformity (PRNU) of camera sensors:\n\n1. **Dark Current Mapping**: The method identifies pixels with abnormally high dark current values — defective sensor elements (\"hot pixels\") that produce elevated signal even without light exposure. These form a camera-specific fingerprint per Lukas et al. (2006).\n\n2. **Spatial Pattern Analysis**: Hot pixel locations are mapped across the image. Real camera images exhibit consistent hot pixel patterns determined by the specific sensor hardware. AI-generated images lack these physical sensor defects entirely.\n\n3. **Fixed Pattern Noise (FPN) Extraction**: The fixed-pattern noise component is separated from the image signal. Genuine photographs contain deterministic FPN arising from manufacturing variations in photodiodes, while synthetic images show statistically uniform or artificially modeled noise.\n\n4. **Temporal Stability Verification**: In authentic images, hot pixels appear at fixed spatial locations with intensity dependent on exposure time and sensor temperature (following Arrhenius behavior). The method checks whether detected anomalies conform to these physical constraints.\n\n5. **Authenticity Scoring**: A confidence score is computed based on the density, spatial distribution, and intensity characteristics of detected hot pixels. Absence of genuine hot pixel signatures or presence of statistically implausible patterns indicates AI generation.`,

  'image/laplacian_pyramid': `This method applies the Burt-Adelson Laplacian pyramid decomposition to analyze multi-scale residual structures:\n\n1. **Gaussian Pyramid Construction**: The image is iteratively low-pass filtered and downsampled by factor 2 to build a Gaussian pyramid G₀, G₁, ..., Gₙ. Each level captures progressively coarser spatial information.\n\n2. **Laplacian Residual Computation**: Each Laplacian level Lₖ = Gₖ − expand(Gₖ₊₁) captures the band-pass detail lost between consecutive Gaussian levels. These residuals encode edges, textures, and fine structures at each spatial scale.\n\n3. **Cross-Scale Correlation Analysis**: Natural images exhibit characteristic statistical dependencies between Laplacian pyramid levels — adjacent scales show predictable correlation patterns governed by the 1/f power spectrum of natural scenes. AI-generated images often violate these cross-scale relationships.\n\n4. **Kurtosis and Distribution Profiling**: The coefficient distributions at each pyramid level are analyzed. Natural image Laplacian coefficients follow a leptokurtic (heavy-tailed) distribution well modeled by generalized Gaussian. GAN/diffusion artifacts produce deviations from these expected distributions.\n\n5. **Residual Energy Scoring**: The energy (sum of squared coefficients) at each level is computed and compared against natural image statistics. Anomalous energy distributions across scales indicate synthetic generation or manipulation.`,

  'image/log_gabor_filter': `This method applies Log-Gabor filters following Field's (1987) framework for analyzing image frequency structure:\n\n1. **Log-Gabor Bank Construction**: A bank of Log-Gabor filters is constructed in the frequency domain with logarithmic spacing. Unlike standard Gabor filters, Log-Gabor filters have zero DC component, no bandwidth limitation, and their transfer function is Gaussian on a logarithmic frequency scale: G(f) = exp(−(log(f/f₀))²/(2(log(σ/f₀))²)).\n\n2. **Multi-Orientation Filtering**: The filter bank spans multiple orientations (typically 6-8) and scales (4-6 octaves), providing comprehensive coverage of the 2D frequency plane. Each filter isolates a specific frequency band and orientation.\n\n3. **Response Energy Mapping**: The local energy response is computed as E(x,y) = √(even²(x,y) + odd²(x,y)), where even and odd components are the real and imaginary parts of the filter response. This captures local frequency content independent of phase.\n\n4. **Natural Image Statistics Comparison**: Response statistics are compared to the known 1/f amplitude spectrum of natural images. AI-generated images exhibit characteristic deviations — GANs often show spectral peaks at grid frequencies, while diffusion models may underrepresent certain frequency bands.\n\n5. **Anomaly Scoring**: The deviation from expected natural image frequency statistics across all filter responses is aggregated into a forensic score indicating the likelihood of AI generation.`,

  'image/moment_invariants': `This method computes Hu's (1962) moment invariants and extended affine moment invariants for forgery detection:\n\n1. **Geometric Moment Computation**: Raw geometric moments mₚᵧ = ΣΣ xᵖyᵧI(x,y) are computed over image blocks. Central moments μₚᵧ are derived by shifting to the centroid, providing translation invariance.\n\n2. **Hu Moment Invariant Extraction**: The seven Hu invariants (φ₁ through φ₇) are calculated from normalized central moments. These are invariant to translation, rotation, and scaling — properties that enable detection of copy-move forgery where copied regions may be geometrically transformed.\n\n3. **Block-wise Invariant Mapping**: The image is divided into overlapping blocks and moment invariants are computed per block. Blocks with similar invariant vectors but different spatial locations suggest copy-move manipulation.\n\n4. **Affine Moment Invariants (AMI)**: Extended invariants following Flusser et al. (2009) capture affine-invariant features, detecting copies that have undergone shearing or non-uniform scaling beyond simple rotation.\n\n5. **Consistency Analysis**: Moment invariant distributions across the image are analyzed for statistical anomalies. Natural images show smooth spatial variation in moment features, while AI-generated images may exhibit unnatural uniformity or discontinuities at generation boundaries. The final score quantifies deviation from expected natural moment statistics.`,

  'image/multiscale_entropy': `This method applies Costa et al.'s (2002) Multiscale Entropy (MSE) framework to quantify image complexity across scales:\n\n1. **Coarse-Graining**: The image signal is coarse-grained at multiple temporal scales τ by averaging non-overlapping windows of length τ: yⱼ(τ) = (1/τ)Σᵢ₌₍ⱼ₋₁₎τ₊₁ʲᵗ xᵢ. This creates a family of representations capturing structure at different resolutions.\n\n2. **Sample Entropy Computation**: At each scale τ, sample entropy SampEn(m, r, N) is calculated — measuring the negative natural logarithm of the conditional probability that sequences similar for m points remain similar for m+1 points within tolerance r. This quantifies irregularity without requiring stationarity.\n\n3. **MSE Curve Construction**: The entropy values across scales form the MSE curve. Natural images exhibit a characteristic MSE profile: high entropy at fine scales (sensor noise, texture detail) with controlled decay at coarse scales reflecting structured content.\n\n4. **Complexity Index Computation**: The area under the MSE curve (Complexity Index, CI) provides a single measure of multi-scale complexity. AI-generated images typically show abnormal MSE profiles — either excessively smooth (low MSE across all scales) or with artificial periodicity absent in natural images.\n\n5. **Anomaly Detection**: The MSE curve shape is compared against reference distributions from natural images. Deviations indicate synthetic generation — diffusion models often produce overly regular fine-scale structure, while GANs may show characteristic entropy dips at specific scales corresponding to generator architecture artifacts.`,

  'image/niqe_score': `This method implements the Natural Image Quality Evaluator (NIQE) by Mittal et al. (2013) for blind quality assessment:\n\n1. **NSS Feature Extraction**: The image is decomposed into normalized luminance coefficients using mean-subtracted contrast-normalized (MSCN) coefficients: Î(x,y) = (I(x,y) − μ(x,y))/(σ(x,y) + C). These MSCN coefficients of natural images follow a unit Gaussian distribution.\n\n2. **Generalized Gaussian Distribution (GGD) Fitting**: MSCN coefficient distributions are fit to a GGD parameterized by shape (α) and variance (σ²). Additionally, pairwise products of adjacent MSCN coefficients are modeled using an asymmetric GGD (AGGD) in four directions (horizontal, vertical, and two diagonals).\n\n3. **Multivariate Gaussian (MVG) Model**: The extracted NSS features (GGD shape, variance, AGGD parameters) form a feature vector. A pristine MVG model (μₙ, Σₙ) is pre-computed from a corpus of natural undistorted images.\n\n4. **Quality Distance Computation**: The NIQE score is computed as the Mahalanobis-like distance: D = √((μ₁−μ₂)ᵀ((Σ₁+Σ₂)/2)⁻¹(μ₁−μ₂)) between the test image's feature distribution (μ₁, Σ₁) and the pristine model (μ₂, Σ₂). Lower scores indicate more natural-looking images.\n\n5. **Forensic Application**: AI-generated images often deviate from natural scene statistics (NSS) captured by NIQE. While visually plausible, synthetic images exhibit subtle violations of NSS regularity — particularly in local contrast normalization and adjacent coefficient dependencies — yielding elevated NIQE scores that serve as a generation indicator.`,

  'image/pixel_value_diff': `This method applies Pixel Value Differencing (PVD) analysis following Wu & Tsai (2003) for steganographic and manipulation detection:\n\n1. **Block Partitioning**: The image is divided into non-overlapping blocks of two consecutive pixels. For each block, the difference value dₖ = |pᵢ − pᵢ₊₁| is computed between adjacent pixel pairs in both horizontal and vertical directions.\n\n2. **Difference Histogram Construction**: A histogram of all pixel difference values is constructed. Natural images exhibit a characteristic PVD histogram following a Laplacian-like distribution — high concentration near zero (smooth regions) with exponential decay toward larger differences (edge regions).\n\n3. **Range Table Analysis**: Differences are classified into ranges [lₖ, uₖ] following the PVD range table. Each range has an expected capacity proportional to its width. Steganographic embedding modifies the histogram within these ranges in detectable ways — creating artifacts in the distribution tails.\n\n4. **Statistical Regularity Detection**: The method detects statistical anomalies in the PVD histogram: (a) unnatural steps between adjacent bins caused by embedding algorithms, (b) abnormal symmetry or flatness in typically peaked distributions, (c) deviations from the expected Benford-like first-digit distribution of differences.\n\n5. **AI Generation Indicators**: AI-generated images typically exhibit PVD histograms with abnormal smoothness (lacking the fine-grained irregularities of real camera quantization), unusual uniformity across difference ranges, or artificial periodicity absent in natural pixel statistics. The analysis score quantifies these deviations.`,

  'image/run_length_matrix': `This method applies Galloway's (1975) Gray Level Run Length Matrix (GLRLM) for texture-based forensic analysis:\n\n1. **Run Length Encoding**: For each direction θ (0°, 45°, 90°, 135°), the image is scanned to identify runs — consecutive pixels with the same gray level. The GLRLM R(i,j|θ) counts the number of runs with gray level i and length j in direction θ.\n\n2. **Feature Extraction**: Standard GLRLM features are computed:\n   - Short Run Emphasis (SRE): Measures fine texture density\n   - Long Run Emphasis (LRE): Quantifies coarse texture presence\n   - Gray Level Non-Uniformity (GLN): Measures gray level distribution uniformity\n   - Run Length Non-Uniformity (RLN): Quantifies run length distribution uniformity\n   - Run Percentage (RP): Ratio of runs to total pixel count\n\n3. **Directional Consistency Analysis**: Natural images show smooth, physically motivated directional variation in GLRLM features. AI-generated images often exhibit either excessive directional uniformity (over-smoothed textures) or implausible directional discontinuities at generation boundaries.\n\n4. **Higher-Order Statistics**: Following Tang (1998), higher-order run length features including Low/High Gray Level Run Emphasis (LGRE/HGRE) capture subtle gray level-run length correlations that differ between natural and synthetic textures.\n\n5. **Forensic Scoring**: GLRLM feature vectors from image blocks are compared against natural image texture statistics. AI-generated images typically produce anomalous short-run-to-long-run ratios and unnatural gray level uniformity patterns, yielding elevated detection scores.`,

  'image/shearlet_analysis': `This method applies the Shearlet Transform following Kutyniok & Labate (2012) for directional multi-scale forensic analysis:\n\n1. **Shearlet System Construction**: A shearlet system is constructed using parabolic scaling matrices Aₐ = diag(a, √a) and shear matrices Sₛ. The shearlet ψₐ,ₛ,ₜ(x) = a⁻³/⁴ψ(Sₛ⁻¹Aₐ⁻¹(x−t)) provides near-optimal sparse representation of images with edges along curves.\n\n2. **Directional Decomposition**: Unlike wavelets, shearlets capture directional information via the shear parameter, enabling anisotropic analysis across multiple orientations at each scale. This is particularly effective for detecting edge artifacts in AI-generated images that exhibit unnatural directional properties.\n\n3. **Phase Congruency Analysis**: Shearlet-domain phase congruency measures the coherence of frequency components at edge locations. Natural edges show high phase congruency across scales, while AI-generated boundaries may show inconsistent phase relationships.\n\n4. **Sparsity Profiling**: The shearlet representation sparsity (measured by ℓ¹/ℓ² ratio) is analyzed per block. Natural images achieve near-optimal sparsity in the shearlet domain due to the geometric regularity of natural edges. AI artifacts — ringing, grid patterns, texture discontinuities — reduce sparsity in characteristic ways.\n\n5. **Edge Regularity Assessment**: The decay rate of shearlet coefficients across scales at detected edges is measured. Natural edges follow predictable decay patterns governed by Hölder regularity, while AI-generated edges often show anomalous coefficient decay indicating synthetic generation.`,

  'image/sparse_representation': `This method applies sparse representation theory following Wright et al. (2009) and Elad & Aharon (2006) for forensic analysis:\n\n1. **Dictionary Learning**: A redundant dictionary D ∈ ℝⁿˣᴷ (K >> n, overcomplete) is learned from natural image patches via K-SVD algorithm. Each atom captures a characteristic local structure (edge, texture, smooth region) found in authentic images.\n\n2. **Sparse Coding**: For each image patch y, the sparsest representation α is found via: min‖α‖₀ s.t. ‖y − Dα‖₂ ≤ ε. In practice, OMP (Orthogonal Matching Pursuit) or LASSO provides an approximate solution. Natural image patches admit highly sparse representations (few active atoms).\n\n3. **Representation Residual Analysis**: The residual r = ‖y − Dα‖₂ measures how well each patch fits the natural image dictionary. Authentic image patches yield low residuals, while AI-generated patches — containing artifacts outside the natural image manifold — produce elevated residuals.\n\n4. **Sparsity Map Construction**: A spatial map of sparsity levels (‖α‖₀) and residuals across the image reveals regions inconsistent with natural image statistics. Manipulated or AI-generated regions typically require more dictionary atoms (lower sparsity) yet still produce higher residuals.\n\n5. **Anomaly Scoring**: The joint distribution of sparsity and residuals across all patches is compared to the expected distribution for natural images. Systematic deviations — particularly elevated residuals in textured regions that should be well-represented by the learned dictionary — indicate synthetic generation.`,

  'image/ssim_map': `This method applies the Structural Similarity Index (SSIM) framework by Wang et al. (2004) for forensic quality analysis:\n\n1. **Local Statistics Computation**: For each local window w (typically 11×11 Gaussian), three components are computed: luminance μ, contrast σ, and structure σ_xy. These capture perceptually relevant image properties following the human visual system model.\n\n2. **SSIM Component Decomposition**: The SSIM index between reference and test patches decomposes as: SSIM(x,y) = l(x,y)^α · c(x,y)^β · s(x,y)^γ, where l = (2μₓμᵧ+C₁)/(μₓ²+μᵧ²+C₁), c = (2σₓσᵧ+C₂)/(σₓ²+σᵧ²+C₂), s = (σₓᵧ+C₃)/(σₓσᵧ+C₃).\n\n3. **Self-Similarity Map Construction**: For forensic analysis without a reference image, local self-similarity is computed by comparing each patch against its neighboring regions. The resulting SSIM map reveals spatial consistency of image quality — genuine images show smooth, physically coherent quality variation.\n\n4. **Quality Discontinuity Detection**: Abrupt changes in local SSIM indicate potential manipulation boundaries — where inserted or AI-generated regions meet authentic image content. These discontinuities arise from differences in compression artifacts, noise levels, or rendering quality.\n\n5. **Statistical Profiling**: The distribution of local SSIM values is analyzed. Natural images exhibit characteristic SSIM distributions governed by content complexity. AI-generated images often show abnormally uniform local quality (lacking the natural variation from optics, sensor, and compression) or suspicious quality boundaries absent in untampered photographs.`,

  'image/steerable_pyramid': `This method applies the Steerable Pyramid decomposition by Simoncelli & Freeman (1995) for multi-scale oriented forensic analysis:\n\n1. **Pyramid Construction**: The image is decomposed via steerable filters into oriented subbands at multiple scales. Unlike the DWT, the steerable pyramid is non-aliased, translation-invariant, and provides exact rotation steerability — enabling analysis at arbitrary orientations without recomputation.\n\n2. **Subband Statistics Extraction**: At each scale and orientation, local coefficient statistics are computed: variance, kurtosis, skewness, and the parameters of a fitted generalized Gaussian distribution. Natural images produce characteristic heavy-tailed distributions in oriented subbands.\n\n3. **Cross-Scale Phase Analysis**: Phase relationships between coefficients at adjacent scales reveal edge structure. Natural edges maintain coherent phase across scales following the predictions of local spectral analysis. AI-generated images may exhibit phase incoherence at generation boundaries or fine scales.\n\n4. **Orientation Energy Analysis**: The orientation energy at each scale E(θ,s) = Σ|c(θ,s)|² captures directional texture structure. Natural images show smooth orientation energy as a function of angle, while AI generation artifacts often produce anomalous peaks or gaps in the orientation energy function.\n\n5. **Texture Synthesis Detection**: The joint statistics of steerable pyramid coefficients (parent-child correlations, cross-orientation coupling) define a texture signature per Portilla & Simoncelli (2000). AI-generated textures often fail to reproduce the full joint statistics achievable by the steerable pyramid model, enabling detection of synthetic content.`,

  'image/svd_decomposition': `This method applies Singular Value Decomposition (SVD) analysis for forensic image authentication:\n\n1. **Block-wise SVD Computation**: The image is partitioned into blocks, and for each block matrix A ∈ ℝᵐˣⁿ, the SVD A = UΣVᵀ is computed. The singular values σ₁ ≥ σ₂ ≥ ... ≥ σᵣ capture the energy distribution across orthogonal rank-1 components following Eckart & Young (1936).\n\n2. **Singular Value Spectrum Analysis**: The decay profile of singular values is analyzed. Natural image blocks exhibit characteristic decay patterns — smooth regions decay rapidly (low effective rank), while textured regions show gradual decay. AI-generated images often produce anomalous decay profiles with unexpected rank distributions.\n\n3. **Effective Rank Mapping**: The effective rank ρ(A) = exp(H(σ̃)), where H is the Shannon entropy of normalized singular values σ̃ᵢ = σᵢ/Σσⱼ, provides a continuous measure of block complexity. A spatial map of effective rank reveals regions with unnatural complexity — either over-smoothed (low rank) or artificially textured.\n\n4. **Principal Component Residual Analysis**: After retaining the top-k singular components (capturing structural content), the residual R = A − UₖΣₖVₖᵀ contains noise, texture detail, and potential artifacts. The statistical properties of this residual differ systematically between natural photographs (sensor noise characteristics) and AI-generated images.\n\n5. **Forensic Scoring**: The spatial distribution of SVD statistics (effective rank, spectral decay rate, residual statistics) is analyzed for consistency. Manipulated or AI-generated regions show characteristic SVD signatures — truncated singular value spectra, abnormal rank distributions, or residuals lacking genuine sensor noise characteristics.`,

  'image/total_variation': `This method applies Total Variation (TV) analysis following Rudin, Osher & Fatemi (1992) for forensic image assessment:\n\n1. **Total Variation Computation**: The isotropic TV of the image I is computed as TV(I) = Σ√(|∂I/∂x|² + |∂I/∂y|²), measuring the total amount of spatial variation. This L¹ norm of the gradient penalizes oscillations while preserving edges — making it sensitive to the difference between natural and synthetic image characteristics.\n\n2. **Local TV Mapping**: A spatial map of local TV values computed in sliding windows reveals the distribution of image complexity. Natural images show physically coherent TV variation — smooth regions (low TV), edges (moderate TV), and textures (high TV) arranged in semantically meaningful patterns.\n\n3. **TV Regularity Analysis**: The ratio of TV to image energy (TV/‖I‖₂) provides a normalized smoothness measure. AI-generated images often exhibit characteristic TV profiles: diffusion models tend toward overly smooth interiors with sharp boundaries, while GANs may produce micro-oscillations elevating TV in supposedly smooth regions.\n\n4. **Anisotropic TV Decomposition**: The directional components TV_x and TV_y are analyzed separately. Natural images show orientation-dependent TV variation correlated with scene geometry. AI-generated images may exhibit isotropic TV even in scenes that should show strong directional bias (e.g., architectural images).\n\n5. **Chambolle Projection Analysis**: Using Chambolle's (2004) dual formulation, the TV-minimizing reconstruction is computed. The difference between the original and TV-denoised image isolates the texture/noise component. Analysis of this component reveals whether the fine-scale structure follows natural sensor noise statistics or exhibits AI generation artifacts.`,

  'image/wavelet_packet': `This method applies Wavelet Packet Decomposition (WPD) following Coifman & Wickerhauser (1992) for comprehensive frequency-domain forensic analysis:\n\n1. **Full Wavelet Packet Tree**: Unlike standard DWT (which only decomposes the approximation subband), WPD recursively decomposes both approximation and detail subbands, creating a full binary tree of 2ⁿ subbands at depth n. This provides uniform frequency resolution across the entire spectrum.\n\n2. **Best Basis Selection**: The optimal basis is selected via entropy-based cost function (Shannon entropy, log-energy, or threshold counting) minimization over the packet tree. The best basis structure itself is forensically informative — natural images optimize differently than AI-generated ones.\n\n3. **Subband Energy Distribution**: Energy distribution across all wavelet packet subbands is computed. Natural images follow predictable energy decay patterns related to the 1/f spectral falloff. AI artifacts produce anomalous energy in specific subbands — GAN grid artifacts appear as energy peaks at characteristic spatial frequencies.\n\n4. **Inter-Subband Correlation Analysis**: Cross-correlations between sibling and parent-child subbands capture statistical dependencies inherent in natural images. AI-generated images often exhibit altered inter-subband correlation structures — either excessive independence (failing to replicate natural dependencies) or artificial correlations from generator architectures.\n\n5. **Coefficient Distribution Profiling**: Wavelet packet coefficient distributions at each node are modeled. Natural image coefficients follow generalized Gaussian distributions with scale-dependent parameters. Deviations from these models — particularly in high-frequency subbands where AI generators struggle to reproduce correct statistics — are quantified for forensic scoring.`,

  // ===== TEXT METHODS =====  
  'text/ghostbuster_detect': `The Ghostbuster Detection method implements the technique from Verma et al. (2023) for detecting AI-generated text using structured search over weaker language models:\n\n1. **Feature Vector Construction**: The input text is processed through a series of weaker, unstructured language models (e.g., unigram, bigram, trigram models and a small GPT-like model). For each token, the probability assigned by each model is computed, yielding per-token probability vectors from multiple model perspectives.\n\n2. **Document-Level Feature Aggregation**: Token-level probabilities are aggregated into document-level features using selected functions: mean, variance, and quantile statistics of log-probabilities from each model. This creates a compact feature vector capturing the distributional characteristics of the text through multiple linguistic lenses.\n\n3. **Structured Search over Feature Combinations**: A structured search selects the most discriminative combination of features and models. Rather than relying on a single powerful model, Ghostbuster combines signals from multiple weaker models — exploiting the observation that AI-generated text exhibits characteristic probability patterns across different model architectures.\n\n4. **Linear Classification**: The selected feature vector is fed into a trained logistic regression classifier. The linear model ensures interpretability and robustness — avoiding overfitting to specific generator architectures. The decision boundary separates human-written text (which shows variable probability across models) from AI-generated text (which tends to be uniformly probable across models).\n\n5. **Confidence Scoring**: The classifier output probability provides a confidence score. Texts near the decision boundary are flagged as uncertain, while those with strong signals from multiple feature dimensions receive high-confidence predictions. The method generalizes across different AI generators without requiring per-model training.`
};

let fixed = 0;
let errors = [];

for (const [methodPath, newMechanism] of Object.entries(mechanisms)) {
  const enPath = path.join('src/app/methods', methodPath, 'i18n', 'en.json');
  
  try {
    const data = JSON.parse(fs.readFileSync(enPath, 'utf8'));
    data.mechanism = newMechanism;
    fs.writeFileSync(enPath, JSON.stringify(data, null, 2), 'utf8');
    fixed++;
    console.log(`✓ Fixed: ${methodPath}`);
  } catch (err) {
    errors.push(`✗ Error ${methodPath}: ${err.message}`);
  }
}

console.log(`\nFixed: ${fixed}/${Object.keys(mechanisms).length}`);
errors.forEach(e => console.log(e));
