/**
 * Fix remaining 20 methods with template mechanisms in English
 */
const fs = require('fs');
const path = require('path');

const mechanisms = {
  'image/hue_consistency': `This method analyzes hue consistency to detect image manipulation and AI generation:\n\n1. **Color Space Conversion**: The image is converted from RGB to HSV (Hue-Saturation-Value) color space, isolating the hue channel. The hue channel represents the dominant wavelength of light independent of brightness and saturation, following Popescu & Farid's (2005) approach to color analysis.\n\n2. **Regional Hue Analysis**: The image is divided into overlapping regions and per-region hue statistics are computed — mean hue, hue variance, and circular hue histogram (since hue is angular). Natural images show smooth hue transitions between adjacent regions following physical illumination constraints.\n\n3. **Hue Gradient Computation**: The spatial gradient of the hue channel is computed. In authentic images, hue gradients correlate with material boundaries and illumination changes. AI-generated images may show hue inconsistencies — abrupt hue shifts not explained by scene geometry or lighting, especially at object boundaries.\n\n4. **Cross-Channel Hue Correlation**: The relationship between hue and luminance/saturation is analyzed. Natural scenes follow physical constraints (e.g., sky hue depends on viewing angle, skin hue varies with illumination). AI models may produce hue-luminance relationships that violate these physical priors.\n\n5. **Hue Coherence Scoring**: A coherence score is computed measuring the overall consistency of hue across the image. Low coherence (high hue variation not explained by scene content) indicates potential manipulation. The score reflects deviations from the expected hue distribution for the detected scene type.`,

  'image/isolated_pixel': `This method detects isolated pixel anomalies for image forensic analysis:\n\n1. **Pixel Neighborhood Analysis**: For each pixel, its value is compared against its local neighborhood (3×3, 5×5, or 7×7 windows). Isolated pixels — those whose values differ significantly from all neighbors — are identified as potential artifacts.\n\n2. **Statistical Outlier Detection**: Using robust statistics (median absolute deviation), pixels whose intensity, color, or gradient values are statistical outliers relative to their local neighborhood are flagged. Natural images rarely contain truly isolated pixels due to optical blur and sensor integration.\n\n3. **AI Generation Artifact Detection**: AI image generators (particularly diffusion models, per Corvi et al., 2023) can produce isolated pixel anomalies through: (a) quantization artifacts in the denoising process, (b) numerical precision issues during generation, (c) boundary artifacts between generated regions. These isolated pixels have a different statistical signature than camera noise.\n\n4. **Spatial Distribution Analysis**: The spatial distribution of detected isolated pixels is analyzed. Random distribution suggests sensor noise (expected). Clustered or patterned distribution suggests generation artifacts or manipulation. The method distinguishes between natural sensor noise (Poisson + Gaussian) and synthetic pixel anomalies.\n\n5. **Isolation Map Generation**: A spatial map of pixel isolation scores is generated. High-isolation regions are marked as suspicious. The overall score reflects the density and pattern of isolated pixels compared to what's expected from the estimated imaging pipeline.`,

  'image/kirsch_edge': `This method applies Kirsch edge operators for image forensic analysis:\n\n1. **Kirsch Compass Kernel Application**: Eight directional Kirsch kernels (3×3) are convolved with the image, each detecting edges in one of eight compass directions (N, NE, E, SE, S, SW, W, NW). The maximum response across all eight directions gives the edge magnitude at each pixel.\n\n2. **Edge Direction Analysis**: The direction of maximum Kirsch response indicates the local edge orientation. In authentic images, edge orientations follow scene geometry and object boundaries. AI-generated images may show edge direction anomalies — directions that don't correspond to coherent object boundaries.\n\n3. **Edge Magnitude Distribution**: The statistical distribution of Kirsch edge magnitudes is analyzed. Natural camera images show characteristic edge magnitude distributions shaped by the lens MTF and sensor resolution. AI-generated images may show different distributions — either too many weak edges (from generation smoothing) or edge magnitude patterns inconsistent with optical imaging.\n\n4. **Edge Continuity Assessment**: Real object edges produce continuous Kirsch responses along their length. The method checks edge continuity — AI generation may produce fragmented edges or edges that appear and disappear without physical justification, especially at boundaries of generated regions.\n\n5. **Multi-Directional Edge Coherence**: The coherence of edge responses across the eight Kirsch directions is analyzed. At true edges, one or two adjacent directions dominate. AI artifacts may produce diffuse edge responses across multiple directions, indicating non-physical edge structures detectable through directional coherence analysis.`,

  'image/laplacian_variance': `This method uses Laplacian variance statistics for image forensic analysis:\n\n1. **Laplacian Computation**: The discrete Laplacian operator (second-order derivative) is applied to the image: ∇²I = ∂²I/∂x² + ∂²I/∂y². The Laplacian highlights regions of rapid intensity change — edges, textures, and noise — while suppressing smooth regions.\n\n2. **Local Variance Analysis**: The local variance of the Laplacian response is computed in sliding windows across the image. This captures the spatial distribution of image detail and texture energy. Natural images show Laplacian variance patterns that follow scene content — high variance at textured regions, low variance at smooth surfaces.\n\n3. **Blur Detection**: The overall Laplacian variance is a classic blur metric (higher values indicate sharper images). The method computes per-region Laplacian variance to detect focus inconsistencies. Regions with different Laplacian variance than expected for their scene position (relative to the focal plane) indicate potential compositing.\n\n4. **AI Generation Signature Detection**: AI-generated images often show characteristic Laplacian variance patterns: (a) unnaturally uniform Laplacian variance across regions that should vary (e.g., in-focus vs. out-of-focus), (b) excessive or insufficient high-frequency content in specific regions, (c) Laplacian variance ratios between spatial scales that don't match natural image statistics.\n\n5. **Comparative Scoring**: The overall Laplacian variance statistics are compared against expected values for the image type and content. Deviations from natural Laplacian variance distributions — measured by moments, kurtosis, and scale ratios — contribute to the forensic score.`,

  'image/laws_texture_e': `This method applies Laws' texture energy measures for image forensic analysis following Laws (1980):\n\n1. **Laws' Kernel Generation**: Nine specific 5×5 texture energy kernels are generated from combinations of three 1D vectors: Level L5=[1,4,6,4,1], Edge E5=[-1,-2,0,2,1], and Spot S5=[-1,0,2,0,-1]. The nine kernels (L5E5, E5L5, L5S5, S5L5, E5E5, E5S5, S5E5, S5S5, L5L5) each detect different texture properties.\n\n2. **Texture Energy Map Computation**: Each Laws' kernel is convolved with the image, and the resulting filtered image is processed with a local energy measure (mean absolute value or variance in a window). This produces nine texture energy maps, each capturing a different texture characteristic — edges, spots, ripples, and combinations.\n\n3. **Texture Feature Vector Analysis**: The nine energy maps form a texture feature vector at each pixel. The distribution and spatial pattern of these features characterize the image's texture properties. Natural textures produce characteristic feature vector distributions shaped by the physical texture-generating process.\n\n4. **Forensic Texture Anomaly Detection**: AI-generated textures often fail to reproduce the full complexity of natural texture statistics. The method analyzes Laws' texture energy distributions for anomalies: (a) texture energy ratios that deviate from natural distributions as characterized by Haralick et al. (1973), (b) spatial discontinuities in texture energy at suspected manipulation boundaries.\n\n5. **Texture Coherence Scoring**: A comprehensive texture score is computed from all nine energy maps. The score measures how well the image's texture statistics conform to natural texture models versus synthetic texture characteristics. Region-specific scoring highlights areas where texture properties suggest manipulation.`,

  'image/linear_pattern': `This method detects linear patterns for image forensic analysis using features inspired by Fridrich & Kodovsky (2012):\n\n1. **Linear Structure Detection**: The image is analyzed for linear structures using directional filtering (oriented Gabor filters, Hough transform, or Radon transform). Lines, edges, and linear patterns are extracted with their orientation, length, and intensity.\n\n2. **Linear Pattern Regularity Analysis**: The regularity and periodicity of linear patterns are analyzed. Natural images contain some linear structures (architecture, horizon lines) but AI-generated images may show: (a) excessive linear regularity, (b) line patterns from the generator's convolutional grid structure, (c) artificial straight lines where natural curves should exist.\n\n3. **Orientation Histogram**: The distribution of linear pattern orientations is computed. Natural scenes show orientation distributions related to scene geometry (many horizontal/vertical lines in architectural scenes, random orientations in natural scenes). AI generators may produce orientation biases from their training data or architecture.\n\n4. **Subpixel Line Analysis**: Lines in authentic images, when analyzed at subpixel precision, show characteristics of the optical imaging process: anti-aliasing from the lens, CFA interpolation effects, edge softening. AI-generated lines may show different subpixel profiles — too sharp, too smooth, or with incorrect anti-aliasing patterns.\n\n5. **Linear Coherence Scoring**: The overall coherence of linear patterns is scored. Anomalies include: linear patterns that don't follow perspective geometry, line segments that terminate abruptly without physical justification, and linear structures with non-physical optical characteristics. The score quantifies deviation from expected linear pattern statistics.`,

  'image/luma_gradient_angle': `This method analyzes luminance gradient angles for image forensic analysis following the rich model framework of Fridrich & Kodovsky (2012):\n\n1. **Gradient Computation**: The luminance gradient vector is computed at each pixel using finite differences or Sobel operators: (∂I/∂x, ∂I/∂y). The gradient angle θ = arctan(∂I/∂y / ∂I/∂x) captures the local edge orientation.\n\n2. **Gradient Angle Statistics**: The distribution of gradient angles across the image is analyzed. Natural images show characteristic angle distributions shaped by scene content. The method extracts statistical features from the gradient angle histogram — moments, entropy, and directional energy ratios.\n\n3. **Local Gradient Angle Patterns**: Co-occurrence patterns of gradient angles between neighboring pixels are analyzed, similar to the rich model approach. Natural images show specific gradient angle co-occurrence patterns arising from smooth edge curves and continuous surfaces. AI artifacts disrupt these patterns.\n\n4. **Gradient Angle Consistency**: The spatial consistency of gradient angles along edges is checked. Real edges show gradually varying gradient angles (smooth contours). AI-generated images may show abrupt angle changes along edges or gradient angle patterns inconsistent with the expected camera imaging pipeline.\n\n5. **Forensic Score from Gradient Features**: The gradient angle features (histogram statistics, co-occurrence patterns, consistency measures) are combined into a forensic score. Features are evaluated against models trained on natural vs. AI-generated images, following the rich model steganalysis framework adapted for AI detection.`,

  'image/maximal_grad_flow': `This method analyzes maximal gradient flow for image forensic analysis:\n\n1. **Gradient Field Computation**: The full gradient vector field ∇I(x,y) = (∂I/∂x, ∂I/∂y) is computed across the image. The gradient magnitude and direction at each point characterize the local image structure.\n\n2. **Gradient Flow Tracing**: Starting from each pixel, the maximal gradient ascent path is traced — following the direction of steepest intensity increase. These paths converge at local intensity maxima (peaks). The network of gradient flow paths reveals the image's topological structure.\n\n3. **Flow Convergence Analysis**: In natural images, gradient flow paths show smooth convergence patterns consistent with continuous intensity surfaces. The method analyzes convergence patterns — AI-generated images may show anomalous convergence: flow paths that terminate prematurely, converge in non-physical patterns, or show grid-aligned artifacts from the generation architecture.\n\n4. **Watershed-Like Segmentation**: The gradient flow induces a natural segmentation of the image into basins of attraction (each associated with a local maximum). The shapes and boundaries of these basins reflect the image's natural structure. Generated images may show basin shapes inconsistent with the depicted scene physics.\n\n5. **Flow Topology Scoring**: The topological complexity of the gradient flow field (number of critical points: maxima, minima, saddle points, and their spatial distribution) is analyzed. Natural images follow predictable topological statistics. The score measures deviation from expected gradient flow topology, flagging images with anomalous gradient structure.`,

  'image/micro_texture': `This method analyzes micro-level texture patterns for image forensic analysis following Haralick et al. (1973):\n\n1. **Micro-Texture Extraction**: Fine-grained texture features are extracted at the pixel level using high-pass filtering and texture energy measurements. Micro-textures (texture details at the 1-5 pixel scale) capture the finest observable detail in the image.\n\n2. **Texture Co-occurrence Analysis**: Gray-Level Co-occurrence Matrices (GLCM) are computed at small displacements (1-3 pixels) in multiple directions. GLCM-derived features (contrast, correlation, energy, homogeneity, per Haralick et al.) characterize the micro-texture properties.\n\n3. **Natural vs. Synthetic Texture Discrimination**: Natural micro-textures arise from physical surface properties (material roughness, surface structure) filtered through the camera's imaging pipeline (lens MTF, sensor integration). AI-generated micro-textures arise from the generator's learned distribution. These differ in: (a) statistical higher-order moments, (b) directional properties, (c) scale-dependent behavior.\n\n4. **Micro-Texture Spatial Consistency**: The consistency of micro-texture statistics across the image is checked. All regions captured through the same camera show consistent micro-texture properties. Regions with different micro-texture statistics (e.g., a face with different micro-texture than the background) indicate potential manipulation or AI generation.\n\n5. **Texture Authenticity Scoring**: Micro-texture features are combined into a forensic score. The score measures how well the observed micro-textures match expectations for natural imaging vs. AI generation, with region-specific scoring to highlight inconsistent areas.`,

  'image/patch_similarity': `This method analyzes patch similarity patterns for image forensic analysis:\n\n1. **Patch Extraction**: The image is divided into overlapping patches (typically 8×8 to 32×32 pixels). Each patch is characterized by its feature vector — pixel values, DCT coefficients, or learned features.\n\n2. **Similarity Matrix Computation**: A similarity matrix is computed measuring the similarity (e.g., cosine similarity, normalized cross-correlation) between all patch pairs. This matrix reveals the self-similarity structure of the image — which regions look alike.\n\n3. **Self-Similarity Pattern Analysis**: Natural images show specific self-similarity patterns: similar patches cluster near repeated textures and objects, and similarity falls off with spatial distance. AI-generated images may show: (a) excessive self-similarity (repetitive generation patterns), (b) similarity patterns inconsistent with scene geometry, (c) patch similarity at non-physically-motivated spatial distances (from the generator repeating learned patterns).\n\n4. **Copy-Move Forensics**: High patch similarity between distant image regions can indicate copy-move manipulation. The method distinguishes between natural recurrence (repeated textures, symmetric objects) and artificial duplication. Geometric matching checks for affine transformations between similar patches.\n\n5. **Similarity Distribution Scoring**: The overall similarity distribution is scored against expected distributions for natural images vs. AI-generated content. Features include: maximum similarity values, similarity decay with distance, number of near-duplicate patches, and spatial distribution of high-similarity regions.`,

  'image/pixel_bit_plane': `This method analyzes pixel bit planes for image forensic analysis following the steganalysis framework of Fridrich & Kodovsky (2012):\n\n1. **Bit Plane Decomposition**: Each pixel value is decomposed into its constituent bit planes (8 bit planes for 8-bit images). Each bit plane is a binary image representing one bit position across all pixels. Higher bit planes carry structural information; lower bit planes carry fine detail and noise.\n\n2. **Bit Plane Statistics**: Statistical properties of each bit plane are analyzed — randomness (entropy), spatial correlation, and pattern regularity. In natural images, lower bit planes approach random binary noise while higher bit planes show image structure. AI-generated images may show different bit plane statistics — especially in lower planes where the generator's quantization produces non-random patterns.\n\n3. **Bit Plane Correlation Analysis**: The correlation between adjacent bit planes is measured. Natural camera images show specific inter-plane correlation patterns arising from the sensor's analog-to-digital conversion. AI-generated pixels don't arise from A/D conversion and may show different inter-plane correlations.\n\n4. **LSB Plane Analysis**: The least significant bit (LSB) plane receives special attention. In natural images, the LSB plane appears quasi-random. AI generators, depending on their output quantization method, may produce LSB planes with: residual patterns, reduced entropy, or spatial correlations that reveal the generation process.\n\n5. **Multi-Plane Feature Scoring**: Features from all bit planes are combined into a forensic score. The score captures bit plane entropy ratios, inter-plane correlation anomalies, and spatial regularity in individual planes.`,

  'image/pixel_symmetry': `This method analyzes pixel-level symmetry for image forensic analysis:\n\n1. **Symmetry Detection**: Multiple types of pixel-level symmetry are detected — bilateral (mirror) symmetry, rotational symmetry, and translational symmetry (repetition). Symmetry is measured using normalized cross-correlation between the image region and its transformed version.\n\n2. **Natural vs. Artificial Symmetry**: Natural images contain approximate symmetry (faces, architecture, natural objects) but never perfect pixel-level symmetry due to noise, lighting variation, and 3D perspective. The method measures symmetry precision — AI-generated images may show unnaturally precise symmetry (too perfect for a camera capture) per the analysis of Corvi et al. (2023).\n\n3. **Local Symmetry Maps**: A per-pixel or per-region symmetry score map is computed showing the degree and type of local symmetry. The spatial distribution of symmetry reveals structural properties. AI generators may produce symmetry artifacts — unexpected symmetry patterns from the generator's architecture (e.g., U-Net skip connections creating symmetric features).\n\n4. **Symmetry Breaking Analysis**: In natural images, physical factors break perfect symmetry — shadows, specularity, perspective foreshortening. The method checks whether expected symmetry-breaking factors are present. AI-generated images might maintain symmetry where physical factors should break it.\n\n5. **Symmetry Feature Scoring**: Symmetry features (precision, spatial distribution, type frequency, symmetry-breaking correspondence) are combined into a forensic score. The score measures how well the image's symmetry properties match expectations for natural photography versus AI generation.`,

  'image/posterization': `This method detects posterization artifacts for image forensic analysis:\n\n1. **Intensity Level Census**: The number of unique intensity levels actually used in each color channel is counted. 8-bit images have 256 possible levels per channel. Posterization reduces the number of distinct levels, creating visible banding in smooth gradients.\n\n2. **Gradient Banding Detection**: Smooth image regions (sky, skin, gradual lighting transitions) are identified, and within these regions, the method checks for intensity staircase patterns — sudden jumps between flat intensity plateaus instead of smooth transitions.\n\n3. **Tone Curve Analysis**: The image's effective tone curve is estimated by analyzing the mapping from expected smooth gradients to observed intensity values. Posterization creates a staircase-like tone curve. The method characterizes the tone curve's step pattern — number of steps, step sizes, and their distribution.\n\n4. **AI Generation Posterization Signatures**: Some AI generators produce posterization-like artifacts from: (a) limited output precision in the generator's final layer, (b) training on processed/compressed images, (c) color quantization in the generation pipeline. The method distinguishes between processing-induced posterization (uniform across the image) and generation-specific posterization (may appear selectively in generated content).\n\n5. **Posterization Severity Scoring**: The severity of posterization is scored based on: number of missing intensity levels, banding visibility in smooth regions, and comparison against expected levels for the image's declared bit depth and pipeline.`,

  'image/scharr_gradient': `This method applies the Scharr gradient operator for image forensic analysis:\n\n1. **Scharr Operator Application**: The 3×3 Scharr kernels are applied in horizontal and vertical directions. The Scharr operator provides improved rotational symmetry compared to Sobel, with kernel weights [−3,0,3; −10,0,10; −3,0,3] for the horizontal direction, yielding more accurate gradient estimation.\n\n2. **Gradient Magnitude Distribution**: The distribution of Scharr gradient magnitudes across the image is analyzed. Natural images show characteristic gradient magnitude distributions shaped by the optical transfer function and scene content. AI-generated images may show different distributions — modified high-frequency content or gradient magnitude statistics inconsistent with optical imaging.\n\n3. **Gradient Direction Analysis**: The gradient direction field θ = arctan(Gy/Gx) reveals edge orientations. The method analyzes direction distributions and directional coherence. AI-generated images may show direction field anomalies — grid-aligned gradient biases from convolutional architectures or direction distributions not matching scene geometry.\n\n4. **Local Gradient Statistics**: Per-region Scharr gradient statistics (mean, variance, skewness, kurtosis) are computed. Spatial variation in gradient statistics should follow scene content. The method detects regions where gradient statistics are inconsistent with neighboring regions — indicating potential manipulation boundaries.\n\n5. **Gradient Feature Scoring**: Scharr gradient features (magnitude distribution, directional statistics, spatial consistency, scale behavior) are combined into a forensic score measuring conformity with natural image gradient characteristics versus AI generation artifacts.`,

  'image/second_order_grad': `This method analyzes second-order gradient features for image forensic analysis:\n\n1. **Second-Order Derivative Computation**: Second-order partial derivatives (∂²I/∂x², ∂²I/∂y², ∂²I/∂x∂y) are computed, capturing the rate of change of image gradients. These measure edge sharpness, curvature, and texture acceleration — properties sensitive to image generation and processing.\n\n2. **Hessian Matrix Analysis**: The 2×2 Hessian matrix H(x,y) = [[∂²I/∂x², ∂²I/∂x∂y], [∂²I/∂x∂y, ∂²I/∂y²]] is computed at each pixel. Eigenvalue analysis of the Hessian reveals local surface curvature — ridges, valleys, and flat regions. The distribution of Hessian eigenvalues characterizes image structure.\n\n3. **Curvature Pattern Analysis**: The principal curvatures (Hessian eigenvalues) and their directions reveal edge profile shapes. Natural edges show specific curvature profiles from optical blur. AI-generated edges may show different curvature — sharper (lacking optical blur), more uniform (from generation smoothing), or with curvature discontinuities at generation boundaries.\n\n4. **Second-Order Statistics**: Statistical moments of second-order derivatives are computed in local windows. Natural images follow specific distributions (typically super-Gaussian). AI generation may produce different second-order statistics — particularly in the relationship between first and second order derivatives, which reflects the image's underlying generative process.\n\n5. **Multi-Scale Second-Order Analysis**: Second-order features are computed at multiple scales (using Gaussian scale-space). The scale-dependent behavior of second-order statistics characterizes the imaging pipeline. AI generation produces different multi-scale second-order behavior than camera capture.`,

  'image/sobel_magnitude': `This method analyzes Sobel magnitude distributions for image forensic analysis following Sobel & Feldman (1968):\n\n1. **Sobel Edge Detection**: The Sobel operator computes horizontal (Gx) and vertical (Gy) gradients using 3×3 kernels. The gradient magnitude G = √(Gx² + Gy²) and direction θ = arctan(Gy/Gx) are computed at each pixel, providing a robust measure of edge strength and orientation.\n\n2. **Magnitude Distribution Analysis**: The histogram of Sobel magnitude values across the image is analyzed. Natural images show specific magnitude distributions following approximately an exponential or Weibull distribution. AI-generated images may show different distributions — modified tail behavior, unusual peak structures, or distribution shape inconsistent with optical imaging.\n\n3. **Spatial Magnitude Patterns**: The spatial distribution of Sobel magnitudes reveals the image's edge structure. In natural images, high-magnitude pixels (strong edges) form connected contours following object boundaries. AI-generated images may show: fragmented edge structures, edge magnitudes not consistent with depth-of-field expectations, or unnaturally uniform edge strength.\n\n4. **Magnitude-Direction Correlation**: In natural images, edge magnitude and direction are correlated through scene structure — strong edges along object boundaries have coherent directions. The method analyzes magnitude-direction correlation. AI artifacts may produce strong gradients with incoherent directions.\n\n5. **Sobel Feature Scoring**: Sobel magnitude features (distribution parameters, spatial patterns, magnitude-direction correlation, multi-scale behavior) are combined into a forensic score. The score measures deviation from natural image edge statistics.`,

  'image/spatial_coherence': `This method analyzes spatial coherence for image forensic analysis, informed by Corvi et al. (2023):\n\n1. **Local Feature Extraction**: Dense local features (texture descriptors, color statistics, gradient properties) are extracted at each spatial location. These features characterize the local image properties at multiple scales.\n\n2. **Spatial Coherence Measurement**: The coherence of features between neighboring regions is measured — how smoothly features vary spatially. Natural images show high spatial coherence: neighboring regions share similar imaging characteristics (noise level, sharpness, color rendering).\n\n3. **Coherence Map Generation**: A spatial coherence map is generated showing where feature coherence breaks down. In authentic images, coherence breaks occur at object boundaries, occlusion edges, and depth discontinuities. In manipulated or AI-generated images, coherence breaks may appear at unexpected locations — manipulation boundaries, generator tile edges, or within regions that should be coherent.\n\n4. **Multi-Scale Coherence Analysis**: Spatial coherence is analyzed at multiple spatial scales. Fine-scale coherence captures pixel-level consistency (noise, texture). Coarse-scale coherence captures structural consistency (lighting, perspective, color grading). AI generation artifacts may appear at specific scales corresponding to the generator's architecture.\n\n5. **Coherence Anomaly Scoring**: The overall spatial coherence is scored against expected values. Localized coherence anomalies (regions where coherence drops without physical justification) contribute to the forensic score. The score highlights boundaries between authentic and generated/manipulated content.`,

  'image/texture_periodicity': `This method analyzes texture periodicity for image forensic analysis, based on texture analysis frameworks from Haralick et al. (1973):\n\n1. **Autocorrelation Analysis**: The 2D autocorrelation function of the image (or image regions) is computed. Periodic textures produce peaks in the autocorrelation at the period intervals. The method extracts periodicity parameters: period, orientation, and regularity.\n\n2. **Power Spectrum Periodicity**: The 2D Fourier power spectrum is analyzed for spectral peaks indicating periodic content. The location of peaks reveals the spatial frequency and orientation of periodic patterns. The method distinguishes between natural periodicities (fabric weave, architectural patterns) and artificial periodicities (GAN grid artifacts, aliasing patterns).\n\n3. **Period Regularity Assessment**: The regularity (or irregularity) of detected periodicities is measured. Natural periodic textures show slight irregularity (variation in period, phase jitter) from the physical process generating them. AI-generated periodicities may be either too regular (perfect repetition from learned patterns) or show characteristic period variation from the generation process.\n\n4. **Periodicity Spatial Distribution**: The spatial distribution of periodic content is mapped. Natural periodic textures are confined to specific objects (fabric, brickwork). AI generation may produce subtle periodicities throughout the image from the convolutional architecture (grid artifacts appearing across all generated content).\n\n5. **Periodicity Feature Scoring**: Periodicity features (detected periods, regularity measures, spatial distribution, spectral peak analysis) are combined into a forensic score. The score captures the presence of anomalous periodicities characteristic of AI generation or manipulation.`,

  'image/tone_mapping': `This method analyzes tone mapping characteristics for image forensic analysis:\n\n1. **Tone Curve Estimation**: The effective tone curve (mapping from scene luminance to pixel values) is estimated from the image content. This is done by analyzing: highlight rolloff behavior, shadow detail rendering, and the overall luminance distribution relative to expected scene statistics.\n\n2. **Tone Mapping Operator Detection**: Different cameras and processing pipelines apply different tone mapping operators (TMOs). The method identifies the TMO type — standard curves (sRGB gamma), camera-specific tone curves (S-curves), HDR tone mapping (Reinhard, Drago, Mantiuk), or AI-generated tone mapping. AI generators learn tone mapping from their training data and may produce inconsistent or unusual tone curves.\n\n3. **Per-Region Tone Response Analysis**: The local tone response is analyzed in different image regions. In single-capture images, the same tone curve applies globally. Composite images may show different effective tone curves in different regions — a key indicator of manipulation.\n\n4. **Dynamic Range Consistency**: The effective dynamic range and its distribution across the image are analyzed. Natural single-capture images have consistent dynamic range limited by the sensor. AI-generated images may show dynamic range inconsistencies — regions with impossible dynamic range extension or unnatural highlight-shadow balance.\n\n5. **Tone Mapping Forensic Score**: Tone mapping features (estimated TMO parameters, per-region tone response consistency, dynamic range analysis) are combined into a forensic score. The score captures tone mapping inconsistencies indicative of compositing, AI generation, or post-processing manipulation.`,

  'text/genre_conformity': `This method analyzes genre conformity for AI text detection following Uchendu et al. (2020):\n\n1. **Genre Classification**: The text is classified into its genre/domain (academic, journalistic, conversational, creative fiction, technical documentation, social media, etc.) using stylistic and structural features — sentence length distributions, vocabulary complexity, formality markers, and discourse structure.\n\n2. **Genre-Specific Feature Extraction**: Features specific to the detected genre are extracted. Each genre has distinct characteristics: academic writing uses passive voice, hedging language, and citation patterns; journalism uses inverted pyramid structure and attribution; creative writing uses figurative language and varied sentence rhythm.\n\n3. **Conformity Assessment**: The text's adherence to genre conventions is measured. Human writers naturally conform to genre expectations through learned writing conventions and audience awareness. AI-generated text may show: (a) genre mixing (formal vocabulary with informal structure), (b) surface-level genre markers without deep genre understanding, (c) generic language that fits no specific genre.\n\n4. **Statistical Genre Profile Comparison**: The text's statistical profile (word frequency distributions, part-of-speech patterns, syntactic complexity metrics) is compared against reference profiles for the detected genre. Deviations from expected genre statistics — particularly in higher-order features like discourse coherence and rhetorical structure — indicate potential AI generation.\n\n5. **Genre Conformity Scoring**: A conformity score is computed measuring how well the text matches its expected genre profile. The score considers multiple dimensions: lexical conformity, syntactic conformity, structural conformity, and pragmatic conformity. Low overall conformity or inconsistent conformity across dimensions suggests AI generation.`
};

// Also fix pixel_value_diff which already has a detailed mechanism
// Check remaining methods
const remaining = ['image/pixel_value_diff'];
remaining.forEach(m => {
  const f = require('path').join('src/app/methods', m, 'i18n', 'en.json');
  try {
    const d = JSON.parse(fs.readFileSync(f, 'utf8'));
    if (d.mechanism && d.mechanism.length > 700) {
      console.log(m + ' already has detailed mechanism (' + d.mechanism.length + ' chars)');
    } else {
      console.log(m + ' needs fix (' + (d.mechanism ? d.mechanism.length : 0) + ' chars)');
    }
  } catch(e) { console.log(m + ': error'); }
});

let fixed = 0;
for (const [methodPath, newMechanism] of Object.entries(mechanisms)) {
  const enPath = path.join('src/app/methods', methodPath, 'i18n', 'en.json');
  try {
    const data = JSON.parse(fs.readFileSync(enPath, 'utf8'));
    data.mechanism = newMechanism;
    fs.writeFileSync(enPath, JSON.stringify(data, null, 2), 'utf8');
    fixed++;
    console.log(`✓ ${methodPath}`);
  } catch (err) {
    console.log(`✗ ${methodPath}: ${err.message}`);
  }
}
console.log(`\nFixed: ${fixed}/${Object.keys(mechanisms).length}`);
