/**
 * Fix TEMPLATE_MECH - Video methods batch 7 (qp through skin)
 */
const fs = require('fs');
const path = require('path');

const mechanisms = {
  'video/qp_analysis': `This method analyzes quantization parameter (QP) patterns for video forensic detection:\n\n1. **QP Map Extraction**: The per-macroblock quantization parameter is extracted from the video bitstream. The QP map reveals how the encoder allocated quality across the frame — lower QP (higher quality) for important/complex regions, higher QP (lower quality) for simpler regions.\n\n2. **QP Distribution Analysis**: The QP distribution across the frame is analyzed. Authentic single-encoded video shows QP values following the encoder's rate-control algorithm — smooth QP variation correlated with content complexity. Re-encoded video (manipulation + re-encoding) shows QP distributions influenced by two encoding passes.\n\n3. **QP-Content Consistency**: The relationship between QP and local content complexity is verified. In normal encoding, complex regions (edges, texture) receive lower QP. Manipulated regions may show QP-content mismatches — the second encoder's QP decisions may not optimally match the inserted content.\n\n4. **Double Quantization Detection**: When video is decoded, manipulated, and re-encoded, characteristic double-quantization artifacts appear in the QP and DCT coefficient distributions. The method detects periodicities in DCT histograms that indicate the original QP, revealing the encoding history.\n\n5. **Temporal QP Pattern Analysis**: QP allocation across frames follows the encoder's rate control model — I-frames typically get lower QP than P/B-frames. The method analyzes temporal QP patterns for anomalies. Manipulated video segments may show QP pattern breaks where the manipulation disrupted the original rate control.`,

  'video/reflection_physics': `This method analyzes reflection physical consistency for deepfake detection:\n\n1. **Reflection Detection**: Reflective surfaces in the scene are identified — mirrors, glass, glossy surfaces, water, metallic objects. Reflected content (particularly face reflections) is detected and extracted from these surfaces.\n\n2. **Reflection Geometry Verification**: Reflections should follow the laws of optics — the reflected image is positioned according to the geometry of the reflective surface. The method checks whether face reflections are geometrically consistent with the face position and surface orientation. Deepfakes that only modify the direct view of the face may leave original reflections unmodified, creating geometry mismatches.\n\n3. **Reflection-Source Identity Matching**: If the face is visible both directly and in a reflection, both views should show the same identity, expression, and appearance. The method cross-checks reflection identity against the direct face view — face-swap deepfakes that don't modify all reflections create detectable identity disagreements.\n\n4. **Specular Highlight Physics**: Specular reflections on shiny surfaces (glasses, jewelry, skin highlights) should follow Fresnel equations — intensity and position depend on the angle between light source, surface, and camera. The method verifies specular highlight physics. AI generators may produce specular highlights with incorrect angular behavior.\n\n5. **Temporal Reflection Consistency**: As objects move, reflections should change according to optics (mirror law, Snell's law for refraction). The method tracks reflection dynamics — reflections should move smoothly and consistently with source object motion. Deepfake reflections may show temporal artifacts or fail to update with face motion.`,

  'video/saccade_analysis': `This method analyzes saccadic eye movements for deepfake detection:\n\n1. **Saccade Detection**: Saccades (rapid ballistic eye movements) are detected from the gaze direction temporal signal. Saccades are characterized by their amplitude (typical 1-40°), peak velocity (up to 500°/s), and duration (20-200ms).\n\n2. **Main Sequence Verification**: Saccades follow the \"main sequence\" — a fixed relationship between amplitude and peak velocity: V_peak ∝ √amplitude (Bahill et al., 1975). The method checks whether detected saccades conform to this physiological invariant. AI-generated eye movements may violate the main sequence — producing incorrect velocity-amplitude relationships.\n\n3. **Saccade Dynamics Analysis**: Natural saccades have characteristic dynamics: rapid acceleration, smooth velocity profile with single peak, small post-saccadic oscillation. The method analyzes each saccade's kinematic profile. AI-generated saccades may show: multiple velocity peaks, incorrect acceleration/deceleration asymmetry, or missing post-saccadic ringing.\n\n4. **Fixation-Saccade Pattern**: Natural gaze alternates between fixations (~200-400ms, stable gaze) and saccades (~20-80ms, rapid shifts). The method verifies this pattern — particularly the fixation duration distribution (approximately log-normal) and saccade rate (3-4 per second during reading/scanning). Deepfakes may show anomalous fixation-saccade patterns.\n\n5. **Bilateral Saccade Coordination**: Both eyes execute saccades simultaneously (conjugate movements). The method checks saccade synchrony between eyes — independent AI generation of each eye may produce asynchronous or differently-sized saccades between left and right eyes.`,

  'video/scene_cut_anomaly': `This method detects scene cut anomalies for video forensic analysis:\n\n1. **Scene Cut Detection**: Scene cuts (hard cuts, dissolves, fades, wipes) are detected by analyzing inter-frame similarity metrics — histogram differences, pixel MSE, and structural similarity. Cut locations are identified and classified by type.\n\n2. **Cut Point Content Analysis**: The content immediately before and after each cut is analyzed for consistency. Manipulated videos may contain cuts specifically placed to hide temporal discontinuities from deepfake insertion — cuts at moments where generation artifacts would be most visible.\n\n3. **Cut Frequency Analysis**: The temporal distribution of cuts is analyzed. Normal video editing follows content-driven patterns (cuts at speech pauses, action changes). Anomalous cut frequency — particularly rapid cuts correlating with challenging deepfake scenarios (profile views, extreme expressions) — may indicate editing to conceal generation failures.\n\n4. **Cross-Cut Consistency**: Content properties (lighting, color balance, noise level) should be consistent across cuts within the same scene. The method checks for property discontinuities at cuts that might indicate different source material. Face properties changing at cut points (subtle identity shifts, quality changes) suggest manipulation.\n\n5. **Cut-Compression Alignment**: In properly encoded video, scene cuts should align with I-frame positions. Misalignment between detected cuts and I-frames may indicate post-manipulation re-encoding without proper scene detection, a forensic trace of manipulation processing.`,

  'video/scene_geometry': `This method analyzes scene geometry consistency for deepfake detection:\n\n1. **3D Scene Reconstruction**: From video frames, approximate 3D scene geometry is estimated using structure-from-motion, depth estimation, and perspective cues. The spatial layout — room dimensions, furniture positions, wall angles — is reconstructed.\n\n2. **Geometric Consistency Verification**: The estimated scene geometry should remain consistent across all frames. The method tracks 3D reconstruction consistency — deformations, scale changes, or geometric shifts indicate manipulation where inserted content doesn't match the scene's 3D structure.\n\n3. **Person-Scene Perspective Match**: The person (particularly face scale and perspective distortion) should be consistent with their position in the 3D scene. Face size should scale correctly with estimated distance from camera. Deepfake composites may show faces at incorrect apparent distances — face scale inconsistent with scene geometry.\n\n4. **Shadow-Geometry Agreement**: Shadows in the scene should be consistent with the 3D geometry and estimated illumination. Ground shadows, cast shadows, and attached shadows should all agree with a single light model and the scene geometry. Manipulated scenes may show shadow-geometry conflicts.\n\n5. **Camera Motion-Scene Geometry Coherence**: As the camera moves, the relative motion of objects at different depths (motion parallax) should be consistent with the scene geometry. The method analyzes motion parallax patterns — composited elements at wrong estimated depths produce incorrect parallax, revealing manipulation.`,

  'video/shadow_temporal': `This method analyzes temporal shadow consistency for video deepfake detection:\n\n1. **Shadow Detection & Tracking**: Shadows (both cast shadows and attached shadows) are detected per frame and tracked across time. Shadow regions are identified by their characteristic low luminance with preserved chromaticity relative to surrounding areas.\n\n2. **Shadow-Light Source Consistency**: Shadow direction and sharpness should be consistent with scene illumination across all frames. The method tracks shadow direction stability — in constant lighting, shadows should remain directionally stable. Temporal shadow direction changes without corresponding light source movement indicate manipulation.\n\n3. **Face Shadow Coherence**: Facial shadows (nose shadow, orbital shadows, chin shadow) should be temporally consistent with scene shadows. The method compares facial shadow dynamics with background shadow behavior. Deepfake face generation may produce facial shadows that evolve differently from scene shadows.\n\n4. **Shadow Intensity Stability**: Shadow intensity (luminance ratio of shadow to illuminated region) should vary smoothly over time. The method tracks shadow intensity — sudden changes in shadow darkness without illumination changes indicate temporal artifacts from frame-independent generation.\n\n5. **Penumbra Consistency**: Shadow edge softness (penumbra width) is determined by light source size and distance. Penumbra should remain consistent across the scene and over time. The method checks penumbra consistency — deepfakes may produce shadows with inconsistent or physically impossible penumbra characteristics.`,

  'video/shoulder': `This method analyzes shoulder movement patterns for deepfake detection:\n\n1. **Shoulder Detection & Tracking**: Shoulder landmarks (acromion processes, deltoid contours, shoulder line angle) are tracked per frame. The shoulder line provides reference for head-body alignment and upper body posture.\n\n2. **Head-Shoulder Coordination**: Head and shoulder movements are biomechanically coupled — large head rotations involve shoulder contribution, nodding produces subtle shoulder adjustments. The method measures head-shoulder temporal correlation. Face-swap deepfakes that only modify the face may show decoupled head-shoulder dynamics.\n\n3. **Breathing Motion Detection**: Shoulders rise subtly during inspiration and fall during expiration. The method detects respiratory shoulder motion (0.2-0.33 Hz) as a biological authenticity signal. Deepfake videos that don't model breathing may show shoulders without respiratory motion.\n\n4. **Shoulder-Clothing Interaction**: Shoulder movement should produce corresponding clothing deformation — fabric stretch, fold formation, collar shifts. The method checks shoulder-clothing dynamic coupling. Generated shoulders may show movement without physically correct clothing response.\n\n5. **Temporal Shoulder Stability**: In steady posture, shoulder position should be stable with only breathing-related and physiological tremor micro-motion. The method tracks shoulder stability — anomalous shoulder jitter, position drift, or contour instability indicates deepfake generation artifacts at the body-face interface.`,

  'video/skin_color_drift': `This method detects temporal skin color drift for deepfake detection:\n\n1. **Skin Color Extraction**: Per-frame skin color is measured in perceptually uniform color space (CIE Lab) from multiple facial regions: forehead, cheeks, nose, chin. The color metrics — L* (lightness), a* (redness), b* (yellowness) — provide a comprehensive skin color characterization.\n\n2. **Temporal Color Stability**: Skin color temporal signals are analyzed for stability. Natural skin color changes slowly (blood flow variations, ~0.1 Hz cardiac cycle, slower vasodilation). The method detects high-frequency color fluctuations inconsistent with physiological rates — deepfake generators may produce frame-to-frame color variations from inconsistent face rendering.\n\n3. **Face-Neck Color Coherence**: Skin color should be consistent between face and neck regions over time (same person, same blood flow). The method tracks face-neck color difference. Deepfake face generation produces a face with potentially different skin color characteristics than the original neck, and this mismatch may vary over time.\n\n4. **Illumination-Independent Color Analysis**: Skin color changes due to illumination are separated from intrinsic skin color changes using chromaticity-based methods. The method isolates the intrinsic skin color signal — physiological changes (blushing, pallor) have specific spectral signatures different from illumination changes. AI-generated color drift may show spectrally incorrect color variations.\n\n5. **Cross-Region Color Correlation**: Different facial skin regions should show correlated color changes (same blood supply). The method checks inter-region color correlation — low correlation suggests different processing/generation of different face regions, characteristic of some deepfake methods.`,

  'video/skin_micro_motion': `This method analyzes skin micro-motion for deepfake detection:\n\n1. **Micro-Motion Amplification**: Subtle skin surface movements are amplified using Eulerian video magnification or phase-based motion amplification. This reveals sub-pixel movements invisible to direct observation — physiological signals encoded in skin surface dynamics.\n\n2. **Pulse Wave Detection**: The cardiac pulse produces a wave of skin displacement traveling from the heart through arterial branches. This pulse wave should be detectable on the face (particularly at the temporal artery region, neck, and forehead). The method checks for pulse wave presence and propagation consistency. Deepfakes lack physiological micro-motion.\n\n3. **Respiratory Motion Signal**: Chest and shoulder respiratory motion may produce subtle cascading movements visible on the neck and lower face. The method detects respiratory-frequency micro-motion in appropriate facial regions. Absence of respiratory micro-motion indicates AI generation.\n\n4. **Micro-Motion Spatial Coherence**: Physiological micro-motion should be spatially coherent — neighboring skin regions show correlated micro-motion from the same underlying physiological source. The method checks spatial coherence of detected micro-motion. AI generation may produce spatially incoherent micro-motion (independent noise per pixel/region).\n\n5. **Micro-Motion Frequency Spectrum**: Natural skin micro-motion has characteristic frequency content: cardiac (1-2 Hz), respiratory (0.2-0.33 Hz), and physiological tremor (8-12 Hz). The method analyzes the frequency spectrum of amplified motion. AI-generated micro-motion may lack these characteristic frequency components or show wrong frequency signatures.`,

  'video/skin_pore_sim': `This method analyzes skin pore similarity patterns for deepfake detection:\n\n1. **Pore Pattern Extraction**: Skin pore patterns are extracted from high-resolution facial regions using local morphological operators. Pore centers are localized and characterized by size, depth (estimated from shadow), and spacing.\n\n2. **Intra-Frame Pore Consistency**: Within each frame, pore characteristics should vary systematically across the face (larger on nose, medium on cheeks, smaller on forehead). The method checks for anatomically correct pore distribution. AI generators may produce spatially uniform pore patterns or incorrect regional variation.\n\n3. **Inter-Frame Pore Stability**: Pore patterns should remain identical across frames (pores are fixed skin structures). The method computes pore pattern similarity between frames using point matching. High inter-frame pore pattern variation indicates AI generation where pore texture is generated independently per frame.\n\n4. **Pore Resolution Assessment**: Pore visibility depends on resolution and should be consistent across the face at the same camera distance. The method checks whether pore resolution matches the video's spatial resolution. AI-generated faces may show resolution-inconsistent pore rendering — visible pores in some regions but smooth skin in others at the same scale.\n\n5. **Synthetic Pore Pattern Detection**: AI-generated pore patterns may show statistical regularities absent in natural skin: (a) too-perfect hexagonal spacing (crystalline pattern), (b) exact repetition of pore patches (texture tiling), (c) pore patterns that don't respond to skin stretching during expression. These markers are quantified for scoring.`,

  'video/skin_specular_reflection': `This method analyzes skin specular reflection for deepfake detection:\n\n1. **Specular Component Extraction**: The specular (glossy) component of skin reflectance is separated from the diffuse (matte) component using dichromatic reflection model decomposition. Specular highlights appear where skin surface is oriented to reflect light directly toward the camera.\n\n2. **Specular Highlight Distribution**: The spatial distribution of skin specular highlights should follow the face's 3D geometry and illumination. The method checks highlight positions against expected locations — forehead center, nose bridge and tip, cheekbone apexes. AI generators may produce specular highlights at incorrect locations or with wrong intensity distributions.\n\n3. **Physical Specular Model**: Skin specular reflection follows the Torrance-Sparrow (microfacet) BRDF model with characteristic roughness parameters. The method measures specular highlight shape and falloff, comparing against physical skin reflectance models. Generated highlights may show non-physical profiles — too sharp, too broad, or incorrect Fresnel behavior.\n\n4. **Temporal Specular Dynamics**: As the head moves, specular highlights should slide across the face following the changing reflection geometry. The method tracks highlight positions relative to landmarks — highlights should move according to the rotation of the surface normal relative to the light direction. Incorrect highlight dynamics indicate AI generation.\n\n5. **Sweat/Oil Physics**: Facial skin specularity varies with surface moisture — oily regions (forehead, nose) are more specular. This distribution should be consistent across frames and follow physiological patterns. AI generators typically don't model skin moisture variation, producing uniform or incorrectly distributed specularity.`,

  'video/skin_texture': `This method analyzes skin texture characteristics for video deepfake detection:\n\n1. **Multi-Scale Skin Texture Extraction**: Skin texture is analyzed at multiple scales using Gabor filters and Local Binary Pattern (LBP) descriptors. The texture hierarchy captures: macro-texture (wrinkles, expression lines), meso-texture (pores, fine wrinkles), and micro-texture (skin grain, cell patterns).\n\n2. **Texture Quality Assessment**: Natural skin texture shows characteristic statistical properties at each scale — specific kurtosis, spatial autocorrelation, and frequency content. The method evaluates texture quality against natural skin models. AI-generated skin often shows: over-smoothed texture (lost high-frequency detail), artificial periodicity, or textures that don't scale correctly with resolution.\n\n3. **Regional Texture Consistency**: Different facial regions have different texture characteristics (nose more textured than cheeks). These regional differences should be physically motivated and consistent across the face. The method maps texture distribution and checks for anomalies — AI generators may produce inconsistent regional texture, particularly at the boundaries between separately generated regions.\n\n4. **Texture-Expression Interaction**: During expressions, skin texture changes predictably: wrinkles deepen, pores stretch across tension lines, and skin becomes smoother in compressed regions. The method verifies texture-expression correspondence. Deepfakes may show expressions without corresponding texture changes.\n\n5. **Temporal Texture Stability**: Fixed skin texture elements (pores, stable wrinkles, moles) should maintain consistent positions across frames. The method tracks landmark texture features over time — temporal texture instability indicates per-frame independent rendering characteristic of AI generation.`
};

let fixed = 0;
for (const [methodPath, newMechanism] of Object.entries(mechanisms)) {
  const enPath = path.join('src/app/methods', methodPath, 'i18n', 'en.json');
  try {
    const data = JSON.parse(fs.readFileSync(enPath, 'utf8'));
    data.mechanism = newMechanism;
    fs.writeFileSync(enPath, JSON.stringify(data, null, 2), 'utf8');
    fixed++;
    console.log(`✓ ${methodPath}`);
  } catch (err) {
    console.log(`✗ ${methodPath}: ${err.message}`);
  }
}
console.log(`\nFixed: ${fixed}/${Object.keys(mechanisms).length}`);
