/**
 * Fix TEMPLATE_MECH - Video methods batch 6 (motion_estimation through pupil)
 */
const fs = require('fs');
const path = require('path');

const mechanisms = {
  'video/motion_estimation_res': `This method analyzes motion estimation residuals for video deepfake detection:\n\n1. **Motion Estimation**: Dense optical flow is computed between consecutive frames using established algorithms (Farnebäck, Lucas-Kanade, or variational methods). This estimates per-pixel motion vectors describing the apparent motion field.\n\n2. **Residual Computation**: The motion-compensated prediction is computed by warping frame t using the estimated flow to predict frame t+1. The residual R = I_{t+1} − W(I_t, flow) captures what the motion model couldn't predict — new content, disoccluded regions, and artifacts.\n\n3. **Residual Distribution Analysis**: Natural video produces motion estimation residuals with characteristic distributions: small residuals in smooth regions (well-predicted), larger at occlusion boundaries and newly visible regions. The method analyzes residual statistics — AI-generated video may show anomalous residual patterns, particularly in face regions where generation artifacts create unpredictable inter-frame changes.\n\n4. **Face-Background Residual Comparison**: The residual characteristics of face regions vs. background are compared. In authentic video, both regions show similar residual statistics (same camera motion, natural object motion). Deepfakes may produce elevated face residuals because the independently generated face doesn't follow physically consistent inter-frame motion.\n\n5. **Temporal Residual Pattern Analysis**: The temporal signal of residual magnitude is tracked. Periodic or anomalous patterns — such as regular residual spikes at the generator's refresh rate or systematically higher face residuals — indicate deepfake manipulation. The score quantifies the deviation from expected motion estimation residual behavior.`,

  'video/motion_vector': `This method analyzes motion vectors from video compression for forensic detection:\n\n1. **Motion Vector Extraction**: Block-level motion vectors are extracted from the video bitstream (H.264/H.265 encoded streams contain explicitly coded motion vectors). These describe how the encoder predicted each block from reference frames.\n\n2. **Motion Field Coherence**: The motion vector field should be physically coherent — nearby blocks should have similar motion vectors (smoothly varying field) except at object boundaries. The method detects regions with anomalous motion vector patterns inconsistent with physical object motion or camera motion.\n\n3. **Foreground-Background Motion Separation**: Global camera motion produces a coherent motion vector field across the frame, while object motion creates local deviations. The method separates these components and verifies that face/body motion is physically consistent. Deepfake insertion may produce face motion that's inconsistent with the camera motion model.\n\n4. **Motion Vector Magnitude Distribution**: The distribution of motion vector magnitudes follows predictable patterns depending on motion speed and search range. The method analyzes this distribution for anomalies — re-encoded deepfakes may show motion vector distributions affected by the original encoding, creating detectable double-estimation artifacts.\n\n5. **Prediction Error Correlation**: Motion vectors should produce effective predictions (low residual). The method analyzes the correlation between motion vector quality and prediction residuals. Regions where motion vectors are optimal for the original content but suboptimal for inserted content reveal manipulation through elevated prediction errors.`,

  'video/neck_skin': `This method analyzes neck skin characteristics for deepfake detection:\n\n1. **Neck Region Segmentation**: The neck region is segmented — the area between the jawline and collar/clothing line. This region is forensically important as it lies at the boundary or outside the typical face-swap region.\n\n2. **Face-Neck Skin Matching**: Skin characteristics (color, tone, texture, sun damage, aging) should be consistent between face and neck. The method compares skin properties across the face-neck boundary. Face-swap deepfakes may show mismatched skin between the generated face and original neck — different color temperature, different texture quality, or different aging characteristics.\n\n3. **Neck Skin Texture Analysis**: Neck skin has characteristic texture: horizontal creases (neck lines), visible platysma muscle bands in some individuals, and different pore distribution than facial skin. The method evaluates whether neck texture is consistent with the face age and quality. AI-generated faces may show an unnatural transition at the jaw-neck boundary.\n\n4. **Color Continuity Across Jaw**: The color transition from face to neck should be smooth and physically motivated (slightly different sun exposure). The method measures color discontinuity at the jawline. Deepfake blending often creates subtle but detectable color seams at this boundary.\n\n5. **Temporal Neck-Face Coherence**: Neck skin should respond to head motion consistently — rotating head reveals different neck surfaces, creates characteristic skin folds, and shows consistent skin tone from different angles. The method tracks neck-face coherence across frames. Deepfake face movement that doesn't correctly account for neck kinematics produces detectable inconsistencies.`,

  'video/neck_transition': `This method analyzes the face-neck transition zone for deepfake detection:\n\n1. **Transition Zone Identification**: The boundary region between the face (jaw, chin) and neck is identified. This transition zone is typically 20-50 pixels wide and is the most common artifact location for face-swap deepfakes.\n\n2. **Gradient Analysis**: The image gradient across the transition zone is measured. Natural face-neck transitions show smooth, anatomically motivated gradients: skin color gradation, shadow from the mandible, and texture transition from facial skin to neck skin. Deepfake blending produces characteristic gradient anomalies — either over-smoothed (Poisson blending) or showing color steps.\n\n3. **Rendering Quality Discontinuity**: The effective resolution and detail level on either side of the transition is compared. Generated faces may have different rendering quality than the original neck — different noise patterns, different compression artifacts, or different texture granularity. These quality discontinuities at the transition indicate compositing.\n\n4. **Anatomical Transition Verification**: The face-neck transition should follow anatomical constraints: submental contour, hyoid region, sternocleidomastoid muscle visibility. The method checks whether surface geometry at the transition is anatomically correct. Deepfake blending may produce anatomically implausible neck-face junctions.\n\n5. **Temporal Transition Tracking**: The transition zone characteristics are tracked across frames. Natural transitions remain anatomically consistent. Deepfake transitions may show varying artifact intensity — more visible at extreme head poses, during fast motion, or under challenging lighting — creating temporal variation in boundary quality.`,

  'video/nose_geometry': `This method analyzes nose geometry for deepfake detection:\n\n1. **Nose Landmark Tracking**: Detailed nose landmarks — bridge, tip, alae (wings), nostrils, columella, nasion (bridge root) — are tracked per frame. These landmarks define the nose's 3D geometry projected into 2D.\n\n2. **Geometric Proportion Analysis**: Nose proportions should follow anatomical constraints: bridge width vs. alar width, nostril size relative to nose length, tip protrusion relative to bridge height. The method checks whether proportions remain within normal human ranges and are consistent across frames. Deepfakes may produce floating proportions.\n\n3. **3D Shape Consistency**: The nose is a prominent 3D structure that should show consistent self-occlusion and shading as head pose changes. The method verifies that nose appearance changes (nostril visibility, bridge shadow, tip highlight) are geometrically consistent with the estimated head pose. AI generators may produce incorrect nose shading at certain poses.\n\n4. **Nose-Face Integration**: The nose must integrate seamlessly with surrounding facial features — nasolabial folds connect nose to cheeks, bridge connects to brow ridge, and skin texture continues smoothly. The method checks for boundary artifacts around the nose perimeter. Face-swap blending may be visible at nose boundaries.\n\n5. **Temporal Shape Stability**: Nose cartilage provides a rigid structure — nose geometry shouldn't change between frames (only viewing angle changes). The method tracks nose proportions over time. Frame-to-frame variation in nose proportions indicates AI generation where the nose is independently rendered each frame.`,

  'video/nose_shadow': `This method analyzes nose shadow patterns for deepfake detection:\n\n1. **Nose Shadow Detection**: The shadow cast by the nose (primarily on the cheek and upper lip) is detected per frame using luminance gradient analysis. The shadow's shape, direction, and intensity are measured.\n\n2. **Shadow-Lighting Consistency**: The nose shadow direction should be consistent with the overall scene illumination. The method estimates the light source direction from the nose shadow and cross-validates against other facial shadows (orbital shadows, chin shadow, nasolabial shadows). Inconsistent shadow directions indicate manipulated lighting in the generated face.\n\n3. **Shadow Shape Analysis**: The nose shadow shape should be geometrically consistent with the nose's 3D shape and the light direction. A straight nose bridge casts a different shadow than a curved one. The method checks whether the shadow shape is physically plausible given the detected nose geometry. AI generators may produce shadows that don't correspond to the nose geometry.\n\n4. **Shadow-Pose Dynamics**: As the head rotates, the nose shadow should shift according to the changing angle between the nose and light source. The method tracks shadow position relative to nose landmarks across frames. In deepfakes, shadows may not respond correctly to head rotation — remaining static or moving independently of head pose.\n\n5. **Soft Shadow Rendering**: Natural nose shadows show penumbra (soft edges) whose width depends on the light source size. The method evaluates shadow edge quality — AI generators may produce shadows with incorrect penumbra (too sharp or too soft) or no penumbra gradient, lacking the physical light-shadow relationship.`,

  'video/nostril_darkness': `This method analyzes nostril darkness and rendering for deepfake detection:\n\n1. **Nostril Detection**: The nostrils are detected per frame as dark interior regions visible at the base of the nose. Their shape (typically oval), size, and darkness level are measured.\n\n2. **Darkness Level Analysis**: Natural nostrils show very low luminance (dark cavity) with specific spectral properties (warm dark due to skin back-scattering). The method measures nostril darkness and compares against expected values. AI generators may produce nostrils that are: too bright (failing to render the cavity), too uniform (lacking internal light gradients), or with incorrect color temperature.\n\n3. **Bilateral Symmetry**: Left and right nostrils should be approximately symmetric in size and darkness (adjusted for head pose). The method checks bilateral nostril consistency. AI generators may produce asymmetric nostrils or nostrils that change relative size between frames.\n\n4. **Pose-Dependent Visibility**: Nostril visibility changes predictably with head pitch — looking up shows more nostril interior, looking down hides them. The method verifies that nostril appearance changes correctly with estimated head pose. Incorrect pose-dependent nostril rendering indicates AI generation.\n\n5. **Temporal Nostril Stability**: Nostril dark regions should maintain consistent shape and position across frames (nostrils don't move relative to nose). The method tracks nostril features over time. Frame-to-frame nostril instability — changing shape, flickering darkness, shifting position — indicates per-frame independent rendering.`,

  'video/object_boundary': `This method analyzes object boundary quality in video for deepfake detection:\n\n1. **Boundary Detection & Classification**: Object boundaries are detected using edge detection and semantic segmentation. Boundaries are classified: person-background boundaries, clothing-skin boundaries, face feature boundaries (eyes, nose, mouth), and hair-background boundaries.\n\n2. **Boundary Quality Assessment**: The quality of each boundary is measured: sharpness, smoothness, sub-pixel anti-aliasing. Natural boundaries have consistent quality across the frame (same optical system). Deepfake composites may show different boundary quality between generated face regions and original footage.\n\n3. **Person-Background Boundary Analysis**: The boundary between the person and background is particularly informative. In authentic video, this boundary shows consistent optical properties. In composited deepfakes, the person-background boundary may show: matting artifacts (alpha channel errors), fringing, or resolution mismatches.\n\n4. **Temporal Boundary Stability**: Object boundaries should be temporally stable and move smoothly. The method tracks boundary positions and quality across frames. AI-generated boundaries may exhibit sub-pixel jitter, temporal instability, or motion artifacts not present in authentically captured boundaries.\n\n5. **Boundary Frequency Analysis**: The spatial frequency content at object boundaries encodes the imaging pipeline's optical characteristics. The method analyzes boundary frequency profiles — different capture/generation pipelines produce different boundary frequency signatures. Mismatched boundary profiles between face and background indicate compositing.`,

  'video/phoneme_correlation': `This method analyzes phoneme-visual correlation for deepfake detection:\n\n1. **Audio Phoneme Extraction**: The audio track is processed to extract a phoneme sequence with precise temporal alignment. Each phoneme is identified with its onset-offset timestamps and confidence score using speech recognition.\n\n2. **Visual Phoneme (Viseme) Detection**: The corresponding visual phoneme (viseme) sequence is extracted from lip/jaw motion analysis. Key visemes include: bilabial closure (/m/, /p/, /b/), labiodental (/f/, /v/), dental (/θ/, /ð/), and open vowels (/a/, /o/).\n\n3. **Phoneme-Viseme Temporal Correlation**: The temporal alignment between audio phonemes and visual visemes is measured. In authentic speech, audio leads visual by ~50ms (auditory-visual speech lag). The method computes cross-correlation to check this temporal relationship. Deepfakes may show incorrect timing between audio and visual speech.\n\n4. **Articulation Completeness**: Certain phonemes require specific visual articulations that are physiologically mandatory — /m/ requires complete lip closure, /f/ requires lip-teeth contact. The method checks whether mandatory articulations are achieved. Deepfake lip generators may fail to produce complete target articulations.\n\n5. **Co-Articulation Pattern Verification**: In natural speech, phoneme production is influenced by surrounding phonemes (anticipatory and carry-over coarticulation). The method checks for natural coarticulation effects in the visual speech signal. AI-generated lip movements often lack proper coarticulation, producing discrete viseme transitions.`,

  'video/phoneme_viseme_map': `This method creates and analyzes phoneme-to-viseme mapping for deepfake detection:\n\n1. **Comprehensive Viseme Mapping**: A many-to-one mapping from phonemes to visemes is established and verified per video. Multiple phonemes map to the same viseme (e.g., /p/, /b/, /m/ all produce bilabial closure). The method checks that phonemes with the same target viseme actually produce the same visual appearance.\n\n2. **Viseme Cluster Analysis**: For each viseme category, all instances across the video are collected and analyzed for consistency. The visual appearance of the same viseme should be consistent throughout the video. High intra-viseme variance suggests AI generation where the lip model doesn't consistently reproduce the same visual targets.\n\n3. **Speaker-Specific Viseme Model**: Each speaker has characteristic viseme shapes determined by their dental/skeletal structure and speaking habits. The method builds a per-speaker viseme model and checks temporal consistency. Deepfakes may show inconsistent viseme shapes as the generator doesn't maintain a stable articulatory model.\n\n4. **Transition Trajectory Analysis**: Viseme-to-viseme transitions follow curved trajectories through the lip configuration space, determined by articulatory dynamics. The method analyzes transition trajectories for physical plausibility — AI-generated transitions may take shorter (unnatural shortcuts) or longer (meandering) paths than anatomically possible.\n\n5. **Viseme Duration Distribution**: Each viseme has a characteristic duration distribution dependent on the phonemic context and speaking rate. The method checks whether viseme durations follow expected distributions. AI lip generation may produce visemes with incorrect or implausibly uniform durations.`,

  'video/pixel_jitter': `This method detects pixel-level temporal jitter for video deepfake detection:\n\n1. **Sub-Pixel Motion Analysis**: Per-pixel temporal variation is measured in regions that should be static (stationary background, stable facial features during stillness). Sub-pixel motion is extracted using phase-based methods to detect motion below one-pixel magnitude.\n\n2. **Jitter Frequency Analysis**: The temporal frequency content of per-pixel variation is analyzed. Natural video shows specific jitter signatures: (a) sensor read noise (white noise, typically < 1 LSB), (b) quantization dither, (c) compression artifact variation. AI-generated video may show jitter with different spectral characteristics — frame-independent rendering produces temporally uncorrelated pixel variations.\n\n3. **Spatial Jitter Pattern**: The spatial distribution of jitter intensity is mapped. Natural jitter is spatially uniform (same sensor for all pixels). AI-generated jitter may be spatially non-uniform — varying in intensity across the frame or showing different jitter characteristics in generated face regions vs. original background.\n\n4. **Face-Background Jitter Comparison**: Jitter characteristics of face pixels are compared with background pixels. In authentic video, both originate from the same sensor and show identical noise characteristics. Deepfake composites show different jitter signatures between the generated face and original background.\n\n5. **Jitter-Motion Decoupling**: The method separates true motion from jitter to avoid false positives. Genuine micro-motion (physiological tremor, breathing) is distinguished from generation artifacts based on spatial coherence and frequency characteristics. The forensic score quantifies the anomalous jitter component.`,

  'video/pixel_repetition_v': `This method detects pixel-level repetition patterns in video for deepfake detection:\n\n1. **Spatial Repetition Detection**: The method searches for exact or near-exact pixel pattern repetitions within each frame. Copy-paste manipulation and some AI generators produce repeated pixel patterns (tiled textures from the generator's feature map).\n\n2. **Generator Architecture Artifact Detection**: GAN generators using transposed convolution upsampling can produce characteristic periodic pixel patterns (\"checkerboard artifacts\") at the generator's stride frequency. The method detects these periodic spatial repetitions in the frequency domain using spectral analysis.\n\n3. **Temporal Pixel Repetition**: The method checks for repeated pixel patterns across frames — exact pixel-level repetition between non-adjacent frames indicates artificial frame generation or copying. Natural video never produces exact pixel-level repetition between distinct frames.\n\n4. **Patch Similarity Analysis**: Local patches are compared using normalized cross-correlation. Unusually high similarity between distant patches (beyond what natural texture would produce) indicates AI generation where the generator's limited diversity manifests as repeated micro-patterns.\n\n5. **Repetition-Scale Analysis**: Repetition is analyzed at multiple spatial scales. Natural textures can show repetition at macro scales (wallpaper, fabric patterns) but not at micro scales. AI-generated content may show micro-scale repetition invisible to human inspection but detectable statistically.`,

  'video/pupillary_unrest': `This method analyzes pupillary unrest (hippus) for deepfake detection:\n\n1. **Pupil Size Measurement**: Pupil diameter is measured per frame using iris-pupil boundary detection and ellipse fitting. High-resolution tracking captures the temporal signal of pupil diameter changes.\n\n2. **Hippus Detection**: Pupillary unrest (hippus) is the continuous, involuntary oscillation of pupil diameter at frequencies of 0.5-2 Hz with amplitude of 0.2-0.5mm. This is a normal physiological phenomenon reflecting sympathetic-parasympathetic nervous system interplay. The method checks for the presence and characteristics of hippus.\n\n3. **Pupillary Light Reflex**: When illumination changes, pupils should constrict (light increase) or dilate (light decrease) with characteristic latency (~200ms) and dynamics (rapid constriction, slower dilation). The method checks for correct pupillary light reflex dynamics. Deepfakes typically don't model this physiological response.\n\n4. **Bilateral Pupil Coordination**: Both pupils should show consensual response — constricting/dilating together with minimal difference (≤0.5mm). The method checks bilateral pupil size correlation. AI generators may produce independent pupil sizes between left and right eyes, violating the consensual pupil response.\n\n5. **Cognitive Pupil Response**: Cognitive effort and emotional arousal produce small pupil dilations (0.1-0.5mm above baseline). The method analyzes whether pupil size correlates with speech content complexity and emotional context. Deepfake pupils that don't respond to cognitive demands lack this natural physiological signal.`,

  'video/pupil_dilation': `This method analyzes pupil dilation dynamics for deepfake detection:\n\n1. **Pupil Tracking**: Precise pupil boundaries are tracked per frame using circular Hough transform or ellipse fitting. Pupil diameter is measured relative to iris diameter (to normalize for distance/zoom changes). The pupil-to-iris ratio temporal signal is extracted.\n\n2. **Lighting-Pupil Correlation**: Pupil diameter should inversely correlate with ambient light level — brighter environment → smaller pupils. The method measures scene luminance and checks the pupil-light correlation. In deepfakes, generated pupil sizes may not respond to scene illumination changes.\n\n3. **Dilation Dynamics**: Pupil dilation/constriction follows specific temporal dynamics: constriction is faster (~0.5s) than dilation (~1s), with characteristic latency (~250ms). The method verifies that observed pupil changes follow these physiological dynamics. AI-generated pupils may show instantaneous or non-physiological size changes.\n\n4. **Bilateral Consistency**: Both pupils should maintain nearly equal sizes (anisocoria < 1mm in normal conditions). The method tracks left-right pupil size difference. Deepfakes frequently produce different pupil sizes in left and right eyes because each eye is generated independently.\n\n5. **Pupil Shape Assessment**: Real pupils are circular (round pupil margin) under normal conditions. Slight elliptical deformation occurs only at extreme gaze angles. The method checks pupil shape — AI generators may produce irregularly shaped pupils, non-circular boundaries, or pupils that change shape between frames. The combined pupil analysis provides a physiological authenticity assessment.`
};

let fixed = 0;
for (const [methodPath, newMechanism] of Object.entries(mechanisms)) {
  const enPath = path.join('src/app/methods', methodPath, 'i18n', 'en.json');
  try {
    const data = JSON.parse(fs.readFileSync(enPath, 'utf8'));
    data.mechanism = newMechanism;
    fs.writeFileSync(enPath, JSON.stringify(data, null, 2), 'utf8');
    fixed++;
    console.log(`✓ ${methodPath}`);
  } catch (err) {
    console.log(`✗ ${methodPath}: ${err.message}`);
  }
}
console.log(`\nFixed: ${fixed}/${Object.keys(mechanisms).length}`);
