const fs = require('fs'), p = require('path'), dir = p.join(__dirname, '..', 'src', 'lib', 'methods', 'video');
const M = [
    ['skinColorDrift', 'analyzeSkinColorDrift', 'Skin Color Drift', 'signal.skinColorDrift', 'sensor', 0.3, '🎨', `const fX=Math.floor(w*0.3),fY=Math.floor(h*0.2),fW=Math.floor(w*0.4),fH=Math.floor(h*0.3);const rows=[];const step=4;for(let y=fY;y<fY+fH&&y<h;y+=step){let sum=0,cnt=0;for(let x=fX;x<fX+fW&&x<w;x+=step){const i=(y*w+x)*4;sum+=(p[i]+p[i+1]+p[i+2])/3;cnt++;}rows.push(cnt>0?sum/cnt:128);}let drift=0;for(let i=1;i<rows.length;i++)drift+=Math.abs(rows[i]-rows[i-1]);const avgD=rows.length>1?drift/(rows.length-1):0;`, `if(avgD<0.5)score=66;else if(avgD<2)score=50;else if(avgD>5)score=30;else score=44;`, `\`Skin drift: \${avgD.toFixed(3)}\``, 2021],
    ['facialSymmetryVideo', 'analyzeFacialSymmetryVideo', 'Facial Symmetry', 'signal.facialSymmetryVideo', 'sensor', 0.3, '🪞', `const fX=Math.floor(w*0.25),fW=Math.floor(w*0.5),fY=Math.floor(h*0.15),fH=Math.floor(h*0.5);let lSum=0,rSum=0,cnt=0;const step=3;const midX=fX+fW/2;for(let y=fY;y<fY+fH&&y<h;y+=step)for(let dx=0;dx<fW/2;dx+=step){const lx=Math.floor(midX-dx),rx=Math.floor(midX+dx);if(lx>=0&&rx<w){const li=(y*w+lx)*4,ri=(y*w+rx)*4;lSum+=Math.abs(p[li]-p[ri])+Math.abs(p[li+1]-p[ri+1]);cnt++;}}const avgDiff=cnt>0?lSum/(cnt*2):0;`, `if(avgDiff<5)score=68;else if(avgDiff<15)score=50;else if(avgDiff>30)score=28;else score=44;`, `\`Facial symmetry diff: \${avgDiff.toFixed(2)}\``, 2021],
    ['lipTextureDetail', 'analyzeLipTextureDetail', 'Lip Texture Detail', 'signal.lipTextureDetail', 'pixel', 0.2, '👄', `const mX=Math.floor(w*0.35),mY=Math.floor(h*0.55),mW=Math.floor(w*0.3),mH=Math.floor(h*0.1);let detail=0,cnt=0;for(let y=mY;y<mY+mH&&y<h-1;y+=2)for(let x=mX;x<mX+mW&&x<w-1;x+=2){const i=(y*w+x)*4;const d=Math.abs(p[i]-p[i+4]);if(d>3&&d<20)detail++;cnt++;}const r=cnt>0?detail/cnt:0;`, `if(r<0.15)score=66;else if(r<0.3)score=48;else if(r>0.5)score=30;else score=44;`, `\`Lip detail: \${r.toFixed(4)}\``, 2022],
    ['foreheadWrinkle', 'analyzeForeheadWrinkle', 'Forehead Wrinkle', 'signal.foreheadWrinkle', 'pixel', 0.2, '🧑‍🦲', `const fX=Math.floor(w*0.3),fY=Math.floor(h*0.08),fW=Math.floor(w*0.4),fH=Math.floor(h*0.12);let wrinkle=0,cnt=0;for(let y=fY;y<fY+fH&&y<h-1;y+=2)for(let x=fX;x<fX+fW&&x<w;x+=2){const i=(y*w+x)*4,j=i+w*4;const d=Math.abs(p[i]-p[j]);if(d>5&&d<25)wrinkle++;cnt++;}const r=cnt>0?wrinkle/cnt:0;`, `if(r<0.05)score=64;else if(r<0.15)score=48;else if(r>0.35)score=32;else score=44;`, `\`Wrinkle ratio: \${r.toFixed(4)}\``, 2022],
    ['irisDetail', 'analyzeIrisDetail', 'Iris Detail', 'signal.irisDetail', 'sensor', 0.3, '👁️‍🗨️', `const eY=Math.floor(h*0.25),eH=Math.floor(h*0.08);const regions=[[Math.floor(w*0.32),eY],[Math.floor(w*0.55),eY]];let totalDetail=0,cnt=0;for(const[ex,ey]of regions){const eW=Math.floor(w*0.1);for(let y=ey;y<ey+eH&&y<h-1;y+=1)for(let x=ex;x<ex+eW&&x<w-1;x+=1){const i=(y*w+x)*4;const d=Math.abs(p[i]-p[i+4])+Math.abs(p[i]-p[i+w*4]);totalDetail+=d;cnt++;}}const avgD=cnt>0?totalDetail/(cnt*2):0;`, `if(avgD<2)score=68;else if(avgD<5)score=52;else if(avgD>12)score=28;else score=44;`, `\`Iris detail: \${avgD.toFixed(3)}\``, 2022],
    ['noseShadow', 'analyzeNoseShadow', 'Nose Shadow', 'signal.noseShadow', 'sensor', 0.2, '👃', `const nX=Math.floor(w*0.42),nY=Math.floor(h*0.3),nW=Math.floor(w*0.16),nH=Math.floor(h*0.2);let leftB=0,rightB=0,lc=0,rc=0;const mid=nX+nW/2;const step=2;for(let y=nY;y<nY+nH&&y<h;y+=step)for(let x=nX;x<nX+nW&&x<w;x+=step){const i=(y*w+x)*4;const b=(p[i]+p[i+1]+p[i+2])/3;if(x<mid){leftB+=b;lc++;}else{rightB+=b;rc++;}}const lAvg=lc>0?leftB/lc:128,rAvg=rc>0?rightB/rc:128;const diff=Math.abs(lAvg-rAvg);`, `if(diff<2)score=64;else if(diff<8)score=48;else if(diff>20)score=32;else score=44;`, `\`Nose shadow diff: \${diff.toFixed(2)}\``, 2021],
    ['chinJawDetail', 'analyzeChinJawDetail', 'Chin-Jaw Detail', 'signal.chinJawDetail', 'pixel', 0.2, '🧏', `const cY=Math.floor(h*0.65),cH=Math.floor(h*0.15),cX=Math.floor(w*0.25),cW=Math.floor(w*0.5);let detail=0,cnt=0;for(let y=cY;y<cY+cH&&y<h-1;y+=2)for(let x=cX;x<cX+cW&&x<w-1;x+=2){const i=(y*w+x)*4;const g=Math.abs(p[i]-p[i+4])+Math.abs(p[i]-p[i+w*4]);if(g>5)detail++;cnt++;}const r=cnt>0?detail/cnt:0;`, `if(r<0.1)score=64;else if(r<0.25)score=48;else if(r>0.5)score=30;else score=44;`, `\`Chin detail: \${r.toFixed(4)}\``, 2022],
    ['backgroundComplexity', 'analyzeBackgroundComplexity', 'Background Complexity', 'signal.bgComplexity', 'pixel', 0.2, '🏔️', `const regions=[[0,0,Math.floor(w*0.2),h],[Math.floor(w*0.8),0,w,h]];let edgeSum=0,cnt=0;const step=3;for(const[x1,y1,x2,y2]of regions)for(let y=y1;y<y2-1;y+=step)for(let x=x1;x<x2-1&&x<w-1;x+=step){const i=(y*w+x)*4;edgeSum+=Math.abs(p[i]-p[i+4])+Math.abs(p[i]-p[i+w*4]);cnt++;}const avgE=cnt>0?edgeSum/(cnt*2):0;`, `if(avgE<2)score=64;else if(avgE<6)score=48;else if(avgE>15)score=32;else score=44;`, `\`BG edge avg: \${avgE.toFixed(3)}\``, 2020],
    ['colorBleeding', 'analyzeColorBleeding', 'Color Bleeding', 'signal.colorBleeding', 'pixel', 0.2, '🩸', `let bleed=0,cnt=0;const step=3;for(let y=0;y<h-1;y+=step)for(let x=0;x<w-1;x+=step){const i=(y*w+x)*4,j=i+4;const rDiff=Math.abs(p[i]-p[j]),gDiff=Math.abs(p[i+1]-p[j+1]),bDiff=Math.abs(p[i+2]-p[j+2]);if(rDiff>30&&gDiff<5&&bDiff<5||gDiff>30&&rDiff<5&&bDiff<5)bleed++;cnt++;}const r=cnt>0?bleed/cnt:0;`, `if(r<0.001)score=62;else if(r<0.01)score=48;else if(r>0.05)score=32;else score=44;`, `\`Color bleed: \${bleed}, Ratio: \${r.toFixed(5)}\``, 2020],
    ['faceMaskEdge', 'analyzeFaceMaskEdge', 'Face Mask Edge', 'signal.faceMaskEdge', 'sensor', 0.3, '🎭', `const fX=Math.floor(w*0.2),fW=Math.floor(w*0.6),fY=Math.floor(h*0.1),fH=Math.floor(h*0.75);const borderW=6;let borderG=0,innerG=0,bc=0,ic=0;const step=2;for(let y=fY;y<fY+fH&&y<h-1;y+=step)for(let x=fX;x<fX+fW&&x<w-1;x+=step){const i=(y*w+x)*4;const g=Math.abs(p[i]-p[i+4]);const isB=(x<fX+borderW||x>fX+fW-borderW||y<fY+borderW||y>fY+fH-borderW);if(isB){borderG+=g;bc++;}else{innerG+=g;ic++;}}const bAvg=bc>0?borderG/bc:0,iAvg=ic>0?innerG/ic:0;const ratio=iAvg>0?bAvg/iAvg:1;`, `if(ratio>3)score=74;else if(ratio>2)score=58;else if(ratio<0.8)score=30;else score=44;`, `\`Border/Inner: \${ratio.toFixed(3)}\``, 2020],
    ['motionBlurDir', 'analyzeMotionBlurDir', 'Motion Blur Direction', 'signal.motionBlurDir', 'pixel', 0.2, '💨', `const dirs=[0,45,90,135];const scores2=[];for(const deg of dirs){const rad=deg*Math.PI/180;const dx=Math.round(Math.cos(rad)*3),dy=Math.round(Math.sin(rad)*3);let s=0,c=0;for(let y=3;y<h-3;y+=4)for(let x=3;x<w-3;x+=4){const i=(y*w+x)*4,j=((y+dy)*w+(x+dx))*4;if(j>=0&&j<p.length-3){s+=Math.abs(p[i]-p[j]);c++;}}scores2.push(c>0?s/c:0);}const mn=Math.min(...scores2),mx=Math.max(...scores2);const dirBias=mx>0?(mx-mn)/mx:0;`, `if(dirBias<0.1)score=62;else if(dirBias<0.25)score=48;else if(dirBias>0.5)score=32;else score=44;`, `\`Direction bias: \${dirBias.toFixed(3)}\``, 2020],
    ['videoGlobalIllum', 'analyzeVideoGlobalIllum', 'Video Global Illum', 'signal.videoGlobalIllum', 'sensor', 0.2, '☀️', `const quadrants=[[0,0,w/2,h/2],[w/2,0,w,h/2],[0,h/2,w/2,h],[w/2,h/2,w,h]];const qBright=[];const step=4;for(const[x1,y1,x2,y2]of quadrants){let s=0,c=0;for(let y=Math.floor(y1);y<Math.floor(y2);y+=step)for(let x=Math.floor(x1);x<Math.floor(x2);x+=step){const i=(y*w+x)*4;s+=(p[i]+p[i+1]+p[i+2])/3;c++;}qBright.push(c>0?s/c:128);}const avg=qBright.reduce((a,b)=>a+b,0)/4;const cv=Math.sqrt(qBright.reduce((a,b)=>a+(b-avg)**2,0)/4)/(avg||1);`, `if(cv<0.05)score=64;else if(cv<0.15)score=48;else if(cv>0.3)score=30;else score=44;`, `\`Illumination CV: \${cv.toFixed(3)}\``, 2019],
    ['pixelJitter', 'analyzePixelJitter', 'Pixel Jitter', 'signal.pixelJitter', 'pixel', 0.2, '🫨', `let jitter=0,cnt=0;const step=3;for(let y=1;y<h-1;y+=step)for(let x=1;x<w-1;x+=step){const i=(y*w+x)*4;const avg4=(p[i-4]+p[i+4]+p[i-w*4]+p[i+w*4])/4;const d=Math.abs(p[i]-avg4);if(d>2&&d<8)jitter++;cnt++;}const r=cnt>0?jitter/cnt:0;`, `if(r<0.05)score=64;else if(r<0.15)score=48;else if(r>0.35)score=30;else score=44;`, `\`Jitter: \${jitter}, Ratio: \${r.toFixed(4)}\``, 2021],
    ['frameEdgeEnergy', 'analyzeFrameEdgeEnergy', 'Frame Edge Energy', 'signal.frameEdgeEnergy', 'frequency', 0.2, '⚡', `let topE=0,botE=0,tc=0,bc2=0;const step=3;for(let x=0;x<w-1;x+=step){for(let y=0;y<Math.min(10,h);y++){const i=(y*w+x)*4;topE+=Math.abs(p[i]-p[i+4]);tc++;}for(let y=h-Math.min(10,h);y<h-1;y++){const i=(y*w+x)*4;botE+=Math.abs(p[i]-p[i+4]);bc2++;}}const tAvg=tc>0?topE/tc:0,bAvg=bc2>0?botE/bc2:0;const diff=Math.abs(tAvg-bAvg);`, `if(diff<1)score=64;else if(diff<4)score=48;else if(diff>10)score=32;else score=44;`, `\`Top: \${tAvg.toFixed(2)}, Bot: \${bAvg.toFixed(2)}\``, 2020],
    ['facialPoreTexture', 'analyzeFacialPoreTexture', 'Facial Pore Texture', 'signal.facialPoreTexture', 'sensor', 0.3, '🔍', `const cX=Math.floor(w*0.35),cY=Math.floor(h*0.35),cW=Math.floor(w*0.3),cH=Math.floor(h*0.15);let micro=0,cnt=0;for(let y=cY;y<cY+cH&&y<h-1;y++)for(let x=cX;x<cX+cW&&x<w-1;x++){const i=(y*w+x)*4;const d=Math.abs(p[i]-p[i+4]);if(d>1&&d<6)micro++;cnt++;}const r=cnt>0?micro/cnt:0;`, `if(r<0.15)score=70;else if(r<0.3)score=52;else if(r>0.5)score=28;else score=44;`, `\`Pore texture: \${r.toFixed(4)}\``, 2023],
    ['temporalGradient', 'analyzeTemporalGradient', 'Temporal Gradient', 'signal.temporalGradient', 'frequency', 0.2, '📉', `let gradSum=0,cnt=0;const step=4;for(let x=0;x<w;x+=step){let prev=p[x*4];for(let y=step;y<h;y+=step){const v=p[(y*w+x)*4];gradSum+=Math.abs(v-prev);prev=v;cnt++;}}const avgG=cnt>0?gradSum/cnt:0;`, `if(avgG<1)score=64;else if(avgG<4)score=48;else if(avgG>10)score=30;else score=44;`, `\`Temporal gradient: \${avgG.toFixed(3)}\``, 2020],
    ['videoSaturationMap', 'analyzeVideoSaturationMap', 'Saturation Map', 'signal.videoSaturationMap', 'statistical', 0.2, '🌈', `let sats=[];const step=4;for(let y=0;y<h;y+=step)for(let x=0;x<w;x+=step){const i=(y*w+x)*4;const mx=Math.max(p[i],p[i+1],p[i+2]),mn=Math.min(p[i],p[i+1],p[i+2]);sats.push(mx>0?(mx-mn)/mx:0);}const avg=sats.reduce((a,b)=>a+b,0)/sats.length;const cv=Math.sqrt(sats.reduce((a,b)=>a+(b-avg)**2,0)/sats.length)/(avg||1);`, `if(cv<0.3)score=64;else if(cv<0.6)score=48;else if(cv>1.2)score=30;else score=44;`, `\`Sat CV: \${cv.toFixed(3)}, Avg: \${avg.toFixed(3)}\``, 2019],
    ['neckSkinConsistency', 'analyzeNeckSkinConsistency', 'Neck Skin', 'signal.neckSkinConsistency', 'pixel', 0.2, '🦒', `const nX=Math.floor(w*0.3),nY=Math.floor(h*0.6),nW=Math.floor(w*0.4),nH=Math.floor(h*0.15);let faceB=0,neckB=0,fc=0,nc=0;const step=3;for(let y=Math.floor(h*0.35);y<Math.floor(h*0.5)&&y<h;y+=step)for(let x=nX;x<nX+nW&&x<w;x+=step){const i=(y*w+x)*4;faceB+=(p[i]+p[i+1]+p[i+2])/3;fc++;}for(let y=nY;y<nY+nH&&y<h;y+=step)for(let x=nX;x<nX+nW&&x<w;x+=step){const i=(y*w+x)*4;neckB+=(p[i]+p[i+1]+p[i+2])/3;nc++;}const fAvg=fc>0?faceB/fc:128,nAvg=nc>0?neckB/nc:128;const diff=Math.abs(fAvg-nAvg);`, `if(diff<3)score=64;else if(diff<10)score=48;else if(diff>25)score=32;else score=44;`, `\`Face-neck diff: \${diff.toFixed(2)}\``, 2022],
    ['videoLumaRange', 'analyzeVideoLumaRange', 'Video Luma Range', 'signal.videoLumaRange', 'statistical', 0.2, '🔆', `let mn=255,mx=0;const step=4;for(let y=0;y<h;y+=step)for(let x=0;x<w;x+=step){const i=(y*w+x)*4;const v=Math.round(0.299*p[i]+0.587*p[i+1]+0.114*p[i+2]);if(v<mn)mn=v;if(v>mx)mx=v;}const dr=mx-mn;`, `if(dr<40)score=66;else if(dr<100)score=50;else if(dr>220)score=30;else score=44;`, `\`Luma range: \${dr}, Min: \${mn}, Max: \${mx}\``, 2019],
    ['cheekTexture', 'analyzeCheekTexture', 'Cheek Texture', 'signal.cheekTexture', 'sensor', 0.2, '🧏‍♀️', `const regions=[[Math.floor(w*0.2),Math.floor(h*0.35),Math.floor(w*0.15),Math.floor(h*0.15)],[Math.floor(w*0.65),Math.floor(h*0.35),Math.floor(w*0.15),Math.floor(h*0.15)]];let detail=0,cnt=0;for(const[rx,ry,rw,rh]of regions)for(let y=ry;y<ry+rh&&y<h-1;y+=2)for(let x=rx;x<rx+rw&&x<w-1;x+=2){const i=(y*w+x)*4;detail+=Math.abs(p[i]-p[i+4]);cnt++;}const avg=cnt>0?detail/cnt:0;`, `if(avg<2)score=68;else if(avg<5)score=50;else if(avg>12)score=28;else score=44;`, `\`Cheek detail: \${avg.toFixed(3)}\``, 2022],
    ['videoColorBalance', 'analyzeVideoColorBalance', 'Color Balance', 'signal.videoColorBalance', 'statistical', 0.2, '⚖️', `let rSum=0,gSum=0,bSum=0,cnt=0;const step=4;for(let y=0;y<h;y+=step)for(let x=0;x<w;x+=step){const i=(y*w+x)*4;rSum+=p[i];gSum+=p[i+1];bSum+=p[i+2];cnt++;}const rA=cnt>0?rSum/cnt:128,gA=cnt>0?gSum/cnt:128,bA=cnt>0?bSum/cnt:128;const avg2=(rA+gA+bA)/3;const dev=Math.sqrt(((rA-avg2)**2+(gA-avg2)**2+(bA-avg2)**2)/3);`, `if(dev<3)score=64;else if(dev<8)score=48;else if(dev>20)score=30;else score=44;`, `\`R:\${rA.toFixed(1)} G:\${gA.toFixed(1)} B:\${bA.toFixed(1)} Dev:\${dev.toFixed(2)}\``, 2019],
    ['edgeAntiAliasingVideo', 'analyzeEdgeAntiAliasingVideo', 'Edge Antialiasing', 'signal.edgeAAVideo', 'pixel', 0.2, '🔲', `let smooth=0,hard=0;const step=3;for(let y=1;y<h-1;y+=step)for(let x=1;x<w-1;x+=step){const i=(y*w+x)*4;const g=Math.abs(p[i]-p[i+4])+Math.abs(p[i]-p[i+w*4]);if(g>20){const mid=(p[i-4]+p[i+4])/2;if(Math.abs(p[i]-mid)<10)smooth++;else hard++;}}const r=(smooth+hard)>0?smooth/(smooth+hard):0.5;`, `if(r>0.8)score=66;else if(r>0.5)score=48;else if(r<0.2)score=30;else score=44;`, `\`Smooth: \${smooth}, Hard: \${hard}\``, 2020],
    ['temporalCoherenceMap', 'analyzeTemporalCoherenceMap', 'Temporal Coherence', 'signal.tempCoherenceMap', 'frequency', 0.3, '🔗', `let coherent=0,cnt=0;const step=4;for(let x=0;x<w;x+=step){for(let y=2;y<h-2;y+=step){const i=(y*w+x)*4;const prev=p[((y-2)*w+x)*4],next=p[((y+2)*w+x)*4];const predicted=(prev+next)/2;if(Math.abs(p[i]-predicted)<8)coherent++;cnt++;}}const r=cnt>0?coherent/cnt:0;`, `if(r>0.85)score=66;else if(r>0.6)score=48;else if(r<0.3)score=30;else score=44;`, `\`Temporal coherence: \${r.toFixed(4)}\``, 2021],
    ['videoFreqSpectrum', 'analyzeVideoFreqSpectrum', 'Video Freq Spectrum', 'signal.videoFreqSpectrum', 'frequency', 0.3, '📡', `const sz=Math.min(32,Math.min(w,h));let lowE=0,highE=0;for(let k=1;k<=sz/2;k++){let re=0,im=0;for(let n=0;n<sz;n++){const a=-2*Math.PI*k*n/sz;const i=(n*w)*4;re+=p[i]*Math.cos(a);im+=p[i]*Math.sin(a);}const pw=re*re+im*im;if(k<=sz/4)lowE+=pw;else highE+=pw;}const ratio=lowE>0?highE/lowE:0;`, `if(ratio<0.01)score=66;else if(ratio<0.05)score=50;else if(ratio>0.2)score=28;else score=44;`, `\`HF/LF ratio: \${ratio.toFixed(4)}\``, 2020],
];
for (const [file, fn, name, key, cat, wt, icon, logic, scoring, det, yr] of M) {
    const code = `/**\n * ${name}\n * AI video detection method\n */\nimport type { AnalysisMethod } from "../../types";\n\nexport function ${fn}(p: Uint8ClampedArray, w: number, h: number): AnalysisMethod {\n    if (w < 32 || h < 32) {\n        return { name: "${name}", nameKey: "${key}", category: "${cat}", score: 50, weight: ${wt}, description: "Frame too small", descriptionKey: "${key}.error", icon: "${icon}" };\n    }\n    ${logic}\n    let score: number;\n    ${scoring}\n    return {\n        name: "${name}", nameKey: "${key}", category: "${cat}", score, weight: ${wt},\n        description: score > 55 ? "${name} pattern suggests deepfake" : "Natural ${name.toLowerCase()} — consistent with real video",\n        descriptionKey: score > 55 ? "${key}.ai" : "${key}.real", icon: "${icon}",\n        details: ${det},\n    };\n}\n`;
    fs.writeFileSync(p.join(dir, file + '.ts'), code);
}
console.log('Created', M.length, 'video methods');
