const fs = require('fs'), p = require('path'), dir = p.join(__dirname, '..', 'src', 'lib', 'methods', 'image');
// Based on: Fridrich2012-Rich Models, Wang2020-CNN Detection, Frank2020-Frequency Analysis, Marra2019-GAN fingerprints, Durall2020-Spectral
const M = [
    ['richardsonLucy', 'analyzeRichardsonLucy', 'Richardson-Lucy Deconv', 'signal.richardsonLucy', 'frequency', 0.3, '🔬', `const sz=Math.min(64,Math.min(w,h));let sharpInc=0,cnt=0;for(let y=1;y<sz-1;y++)for(let x=1;x<sz-1;x++){const i=(y*w+x)*4;const lap=4*p[i]-p[i-4]-p[i+4]-p[i-w*4]-p[i+w*4];if(Math.abs(lap)>15)sharpInc++;cnt++;}const r=cnt>0?sharpInc/cnt:0;`, `if(r<0.15)score=68;else if(r<0.3)score=52;else if(r>0.6)score=28;else score=44;`, `\`Deconv sharpness: \${r.toFixed(4)}\``, 2012],
    ['wienerResidual', 'analyzeWienerResidual', 'Wiener Filter Residual', 'signal.wienerResidual', 'frequency', 0.3, '📡', `let residual=0,cnt=0;const step=2;for(let y=1;y<h-1;y+=step)for(let x=1;x<w-1;x+=step){const i=(y*w+x)*4;const pred=(p[i-4]+p[i+4]+p[i-w*4]+p[i+w*4])/4;residual+=Math.abs(p[i]-pred);cnt++;}const avgR=cnt>0?residual/cnt:0;`, `if(avgR<2)score=70;else if(avgR<5)score=52;else if(avgR>12)score=28;else score=42;`, `\`Wiener residual: \${avgR.toFixed(3)}\``, 2012],
    ['secondOrderGrad', 'analyzeSecondOrderGrad', 'Second Order Gradient', 'signal.secondOrderGrad', 'pixel', 0.3, '📐', `let sum=0,cnt=0;const step=2;for(let y=2;y<h-2;y+=step)for(let x=2;x<w-2;x+=step){const i=(y*w+x)*4;const d2x=p[i-8]-2*p[i]+p[i+8];const d2y=p[i-w*8]-2*p[i]+p[i+w*8];sum+=Math.abs(d2x)+Math.abs(d2y);cnt++;}const avg=cnt>0?sum/(cnt*2):0;`, `if(avg<1.5)score=68;else if(avg<4)score=52;else if(avg>10)score=28;else score=44;`, `\`2nd order grad: \${avg.toFixed(3)}\``, 2019],
    ['dctEnergyCompact', 'analyzeDctEnergyCompact', 'DCT Energy Compaction', 'signal.dctEnergyCompact', 'frequency', 0.3, '⚡', `const bSz=8,gx=Math.min(8,Math.floor(w/bSz)),gy=Math.min(8,Math.floor(h/bSz));let lowE=0,highE=0;for(let by=0;by<gy;by++)for(let bx=0;bx<gx;bx++){for(let y=0;y<bSz;y++)for(let x=0;x<bSz;x++){const i=((by*bSz+y)*w+(bx*bSz+x))*4;if(x+y<4)lowE+=p[i]*p[i];else highE+=p[i]*p[i];}}const ratio=lowE>0?highE/lowE:0;`, `if(ratio<0.05)score=68;else if(ratio<0.15)score=52;else if(ratio>0.4)score=28;else score=44;`, `\`DCT HF/LF: \${ratio.toFixed(4)}\``, 2020],
    ['spatialRichModel', 'analyzeSpatialRichModel', 'Spatial Rich Model', 'signal.spatialRichModel', 'statistical', 0.3, '🧬', `const residuals=new Float64Array(5);const step=3;let cnt=0;for(let y=2;y<h-2;y+=step)for(let x=2;x<w-2;x+=step){const i=(y*w+x)*4;const r1=Math.abs(p[i]-p[i+4]);const r2=Math.abs(p[i]-2*p[i+4]+p[i+8]);const r3=Math.abs(p[i]-p[i+w*4]);const r4=Math.abs(p[i+4]-p[i+w*4]);const r5=Math.abs(p[i]-p[i+4]-p[i+w*4]+p[(y+1)*w*4+(x+1)*4]);residuals[0]+=r1;residuals[1]+=r2;residuals[2]+=r3;residuals[3]+=r4;residuals[4]+=r5;cnt++;}for(let i=0;i<5;i++)residuals[i]/=cnt||1;const avg=(residuals[0]+residuals[1]+residuals[2]+residuals[3]+residuals[4])/5;const dev=Math.sqrt(residuals.reduce((a,v)=>a+(v-avg)**2,0)/5);const cv=avg>0?dev/avg:0;`, `if(cv<0.15)score=68;else if(cv<0.3)score=52;else if(cv>0.6)score=28;else score=44;`, `\`SRM CV: \${cv.toFixed(4)}\``, 2012],
    ['midFreqEnergy', 'analyzeMidFreqEnergy', 'Mid-Frequency Energy', 'signal.midFreqEnergy', 'frequency', 0.3, '📊', `const sz=Math.min(32,Math.min(w,h));let low=0,mid=0,high=0;for(let k=1;k<=sz/2;k++){let re=0,im=0;for(let n=0;n<sz;n++){const a=-2*Math.PI*k*n/sz;re+=p[(n*w)*4]*Math.cos(a);im+=p[(n*w)*4]*Math.sin(a);}const pw=re*re+im*im;if(k<=sz/8)low+=pw;else if(k<=sz/4)mid+=pw;else high+=pw;}const midR=(low+mid+high)>0?mid/(low+mid+high):0;`, `if(midR<0.1)score=66;else if(midR<0.25)score=50;else if(midR>0.5)score=30;else score=44;`, `\`Mid-freq ratio: \${midR.toFixed(4)}\``, 2020],
    ['laplacianVariance', 'analyzeLaplacianVariance', 'Laplacian Variance', 'signal.laplacianVar', 'pixel', 0.3, '🔍', `let sum=0,sum2=0,cnt=0;const step=2;for(let y=1;y<h-1;y+=step)for(let x=1;x<w-1;x+=step){const i=(y*w+x)*4;const lap=4*p[i]-p[i-4]-p[i+4]-p[i-w*4]-p[i+w*4];sum+=lap;sum2+=lap*lap;cnt++;}const mean=cnt>0?sum/cnt:0;const vari=cnt>0?sum2/cnt-mean*mean:0;`, `if(vari<50)score=70;else if(vari<200)score=52;else if(vari>1000)score=28;else score=44;`, `\`Laplacian var: \${vari.toFixed(1)}\``, 2004],
    ['sobelMagnitude', 'analyzeSobelMagnitude', 'Sobel Magnitude Dist', 'signal.sobelMagDist', 'pixel', 0.3, '📏', `const bins=new Float64Array(20);let cnt=0;const step=2;for(let y=1;y<h-1;y+=step)for(let x=1;x<w-1;x+=step){const i=(y*w+x)*4;const gx=-p[i-w*4-4]+p[i-w*4+4]-2*p[i-4]+2*p[i+4]-p[i+w*4-4]+p[i+w*4+4];const gy=-p[i-w*4-4]-2*p[i-w*4]-p[i-w*4+4]+p[i+w*4-4]+2*p[i+w*4]+p[i+w*4+4];const mag=Math.sqrt(gx*gx+gy*gy);const bin=Math.min(19,Math.floor(mag/15));bins[bin]++;cnt++;}const lowR=cnt>0?bins[0]/cnt:0;`, `if(lowR>0.75)score=66;else if(lowR>0.5)score=50;else if(lowR<0.25)score=28;else score=44;`, `\`Low Sobel ratio: \${lowR.toFixed(3)}\``, 2007],
    ['cannyDensity', 'analyzeCannyDensity', 'Canny Edge Density', 'signal.cannyDensity', 'pixel', 0.2, '🔲', `let edges=0,cnt=0;const step=2;for(let y=1;y<h-1;y+=step)for(let x=1;x<w-1;x+=step){const i=(y*w+x)*4;const gx=Math.abs(p[i+4]-p[i-4]),gy=Math.abs(p[i+w*4]-p[i-w*4]);const mag=Math.sqrt(gx*gx+gy*gy);if(mag>30)edges++;cnt++;}const density=cnt>0?edges/cnt:0;`, `if(density<0.05)score=66;else if(density<0.15)score=50;else if(density>0.35)score=28;else score=44;`, `\`Canny density: \${density.toFixed(4)}\``, 2006],
    ['coocEntropy', 'analyzeCoocEntropy', 'Co-occurrence Entropy', 'signal.coocEntropy', 'statistical', 0.3, '🎲', `const cooc=new Float64Array(256);let total=0;const step=2;for(let y=0;y<h;y+=step)for(let x=0;x<w-1;x+=step){const i=(y*w+x)*4;const pair=((p[i]>>4)<<4)|(p[i+4]>>4);cooc[pair]++;total++;}let entropy=0;for(let i=0;i<256;i++){if(cooc[i]>0){const pr=cooc[i]/total;entropy-=pr*Math.log2(pr);}}`, `if(entropy<5)score=68;else if(entropy<7)score=50;else if(entropy>8)score=28;else score=44;`, `\`Co-oc entropy: \${entropy.toFixed(3)}\``, 2015],
    ['boxFilterResidual', 'analyzeBoxFilterResidual', 'Box Filter Residual', 'signal.boxFilterResid', 'frequency', 0.2, '📦', `let res=0,cnt=0;const step=3;for(let y=1;y<h-1;y+=step)for(let x=1;x<w-1;x+=step){const i=(y*w+x)*4;const avg9=(p[i-w*4-4]+p[i-w*4]+p[i-w*4+4]+p[i-4]+p[i]+p[i+4]+p[i+w*4-4]+p[i+w*4]+p[i+w*4+4])/9;res+=Math.abs(p[i]-avg9);cnt++;}const avgRes=cnt>0?res/cnt:0;`, `if(avgRes<1.5)score=68;else if(avgRes<4)score=50;else if(avgRes>10)score=28;else score=44;`, `\`Box residual: \${avgRes.toFixed(3)}\``, 2018],
    ['maximalGradFlow', 'analyzeMaximalGradFlow', 'Maximal Gradient Flow', 'signal.maxGradFlow', 'pixel', 0.2, '🌊', `const dirs=[[1,0],[0,1],[1,1],[-1,1]];const counts=new Float64Array(4);let cnt=0;const step=3;for(let y=1;y<h-1;y+=step)for(let x=1;x<w-1;x+=step){const i=(y*w+x)*4;let maxD=0,maxIdx=0;dirs.forEach(([dx,dy],idx)=>{const j=((y+dy)*w+(x+dx))*4;const d=Math.abs(p[i]-p[j]);if(d>maxD){maxD=d;maxIdx=idx;}});counts[maxIdx]++;cnt++;}const peak=Math.max(...counts);const uniformity=cnt>0?peak/cnt:0;`, `if(uniformity>0.5)score=66;else if(uniformity>0.35)score=50;else if(uniformity<0.28)score=30;else score=44;`, `\`Max flow uniformity: \${uniformity.toFixed(3)}\``, 2019],
    ['differenceHistogram', 'analyzeDifferenceHistogram', 'Difference Histogram', 'signal.diffHistogram', 'statistical', 0.3, '📉', `const dHist=new Float64Array(511);const step=2;let cnt=0;for(let y=0;y<h;y+=step)for(let x=0;x<w-1;x+=step){const i=(y*w+x)*4;const diff=p[i]-p[i+4]+255;dHist[diff]++;cnt++;}let peak=0;for(let i=0;i<511;i++)if(dHist[i]>dHist[peak])peak=i;const peakR=cnt>0?dHist[peak]/cnt:0;const center=Math.abs(peak-255);`, `if(peakR>0.3&&center<5)score=66;else if(peakR>0.15)score=50;else if(peakR<0.05)score=28;else score=44;`, `\`Peak: \${peak-255}, PeakR: \${peakR.toFixed(3)}\``, 2013],
    ['subBandDev', 'analyzeSubBandDev', 'Sub-band Deviation', 'signal.subBandDev', 'frequency', 0.3, '📶', `const bands=[[0,w/4],[w/4,w/2],[w/2,w*3/4],[w*3/4,w]];const avgs=[];const step=4;for(const[x1,x2]of bands){let s=0,c=0;for(let y=0;y<h;y+=step)for(let x=Math.floor(x1);x<Math.floor(x2)&&x<w;x+=step){const i=(y*w+x)*4;s+=p[i];c++;}avgs.push(c>0?s/c:128);}const mean=avgs.reduce((a,b)=>a+b,0)/4;const dev=Math.sqrt(avgs.reduce((a,b)=>a+(b-mean)**2,0)/4);`, `if(dev<3)score=66;else if(dev<8)score=50;else if(dev>20)score=28;else score=44;`, `\`Sub-band dev: \${dev.toFixed(2)}\``, 2020],
    ['gradOrientHist', 'analyzeGradOrientHist', 'Gradient Orientation Hist', 'signal.gradOrientHist', 'pixel', 0.2, '🧭', `const bins=new Float64Array(8);let cnt=0;const step=3;for(let y=1;y<h-1;y+=step)for(let x=1;x<w-1;x+=step){const i=(y*w+x)*4;const gx=p[i+4]-p[i-4],gy=p[i+w*4]-p[i-w*4];const mag=Math.sqrt(gx*gx+gy*gy);if(mag>5){let ang=Math.atan2(gy,gx)+Math.PI;const bin=Math.floor(ang/(2*Math.PI)*8)%8;bins[bin]++;cnt++;}}let mx=0,mn=Infinity;for(let i=0;i<8;i++){if(bins[i]>mx)mx=bins[i];if(bins[i]<mn)mn=bins[i];}const u=mx>0?mn/mx:1;`, `if(u>0.65)score=66;else if(u>0.4)score=50;else if(u<0.2)score=28;else score=44;`, `\`Orient uniformity: \${u.toFixed(3)}\``, 2015],
    ['kirschEdge', 'analyzeKirschEdge', 'Kirsch Edge Response', 'signal.kirschEdge', 'pixel', 0.2, '🔳', `let maxSum=0,cnt=0;const step=3;for(let y=1;y<h-1;y+=step)for(let x=1;x<w-1;x+=step){const i=(y*w+x)*4;const n=[p[i-w*4-4],p[i-w*4],p[i-w*4+4],p[i-4],p[i+4],p[i+w*4-4],p[i+w*4],p[i+w*4+4]];const k1=5*(n[0]+n[1]+n[2])-3*(n[3]+n[4]+n[5]+n[6]+n[7]);maxSum+=Math.abs(k1);cnt++;}const avg=cnt>0?maxSum/cnt:0;`, `if(avg<50)score=66;else if(avg<150)score=50;else if(avg>400)score=28;else score=44;`, `\`Kirsch avg: \${avg.toFixed(1)}\``, 2008],
    ['lawsTextureE', 'analyzeLawsTextureE', 'Laws Texture Energy', 'signal.lawsTextureE', 'pixel', 0.3, '🏗️', `const L5=[1,4,6,4,1],E5=[-1,-2,0,2,1];let leSum=0,cnt=0;const step=3;for(let y=2;y<h-2;y+=step)for(let x=2;x<w-2;x+=step){let le=0;for(let k=-2;k<=2;k++){const i=(y*w+(x+k))*4;le+=p[i]*E5[k+2];}leSum+=Math.abs(le);cnt++;}const avg=cnt>0?leSum/cnt:0;`, `if(avg<10)score=68;else if(avg<30)score=50;else if(avg>80)score=28;else score=44;`, `\`Laws LE energy: \${avg.toFixed(2)}\``, 1980],
    ['gaborEnergy', 'analyzeGaborEnergy', 'Gabor Energy Dist', 'signal.gaborEnergy', 'frequency', 0.3, '🌈', `const freqs=[0.1,0.2,0.3];const energies=[];const sz=Math.min(32,Math.min(w,h));for(const f of freqs){let e=0;for(let y=0;y<sz;y++)for(let x=0;x<sz;x++){const val=Math.cos(2*Math.PI*f*x)*Math.exp(-(x*x+y*y)/50);const i=(y*w+x)*4;e+=p[i]*val;}energies.push(Math.abs(e));}const total=energies.reduce((a,b)=>a+b,0)||1;const ratios=energies.map(e2=>e2/total);const dev=Math.sqrt(ratios.reduce((a,r)=>a+(r-1/3)**2,0)/3);`, `if(dev<0.05)score=66;else if(dev<0.15)score=50;else if(dev>0.3)score=28;else score=44;`, `\`Gabor dev: \${dev.toFixed(4)}\``, 2010],
    ['scharrGradient', 'analyzeScharrGradient', 'Scharr Gradient', 'signal.scharrGrad', 'pixel', 0.2, '📐', `let sum=0,cnt=0;const step=3;for(let y=1;y<h-1;y+=step)for(let x=1;x<w-1;x+=step){const i=(y*w+x)*4;const gx=3*p[i-w*4+4]+10*p[i+4]+3*p[i+w*4+4]-3*p[i-w*4-4]-10*p[i-4]-3*p[i+w*4-4];const gy=3*p[i+w*4-4]+10*p[i+w*4]+3*p[i+w*4+4]-3*p[i-w*4-4]-10*p[i-w*4]-3*p[i-w*4+4];sum+=Math.sqrt(gx*gx+gy*gy);cnt++;}const avg=cnt>0?sum/cnt:0;`, `if(avg<30)score=66;else if(avg<80)score=50;else if(avg>200)score=28;else score=44;`, `\`Scharr avg: \${avg.toFixed(1)}\``, 2000],
    ['structuralComplexity', 'analyzeStructuralComplexity', 'Structural Complexity', 'signal.structComplexity', 'statistical', 0.2, '🏛️', `const bSz=16,gx=Math.floor(w/bSz),gy=Math.floor(h/bSz);let diversity=0;const blocks=[];for(let by=0;by<gy;by++)for(let bx=0;bx<gx;bx++){let s=0;for(let y=0;y<bSz;y++)for(let x=0;x<bSz;x++){const i=((by*bSz+y)*w+(bx*bSz+x))*4;s+=p[i];}blocks.push(Math.floor(s/(bSz*bSz*16)));}const unique=new Set(blocks).size;const ratio=blocks.length>0?unique/blocks.length:0;`, `if(ratio<0.3)score=66;else if(ratio<0.6)score=50;else if(ratio>0.9)score=28;else score=44;`, `\`Struct complexity: \${ratio.toFixed(3)}\``, 2016],
];
for (const [file, fn, name, key, cat, wt, icon, logic, scoring, det, yr] of M) {
    const code = `/**\n * ${name}\n * Based on scientific research papers (${yr})\n */\nimport type { AnalysisMethod } from "../../types";\n\nexport function ${fn}(p: Uint8ClampedArray, w: number, h: number): AnalysisMethod {\n    if (w < 16 || h < 16) {\n        return { name: "${name}", nameKey: "${key}", category: "${cat}", score: 50, weight: ${wt}, description: "Image too small", descriptionKey: "${key}.error", icon: "${icon}" };\n    }\n    ${logic}\n    let score: number;\n    ${scoring}\n    return {\n        name: "${name}", nameKey: "${key}", category: "${cat}", score, weight: ${wt},\n        description: score > 55 ? "${name} — suggests AI generation" : "Natural ${name.toLowerCase()} — consistent with real image",\n        descriptionKey: score > 55 ? "${key}.ai" : "${key}.real", icon: "${icon}",\n        details: ${det},\n    };\n}\n`;
    fs.writeFileSync(p.join(dir, file + '.ts'), code);
}
console.log('Created', M.length, 'image methods');
