const fs = require('fs'), p = require('path'), dir = p.join(__dirname, '..', 'src', 'lib', 'methods', 'image');
const M = [
    ['skinTextureFreq', 'analyzeSkinTextureFreq', 'Skin Texture Frequency', 'signal.skinTextureFreq', 'sensor', 0.2, '🧑', `const fX=Math.floor(w*0.3),fY=Math.floor(h*0.2),fW=Math.floor(w*0.4),fH=Math.floor(h*0.3);let hf=0,lf=0,c=0;for(let y=fY;y<fY+fH&&y<h-1;y+=2)for(let x=fX;x<fX+fW&&x<w-1;x+=2){const i=(y*w+x)*4;const d=Math.abs(p[i]-p[i+4]);if(d>8&&d<25)hf++;else lf++;c++;}const r=c>0?hf/c:0;`, `if(r<0.1)score=68;else if(r<0.25)score=52;else if(r>0.5)score=28;else score=42;`, `\`Skin HF ratio: \${r.toFixed(4)}\``, 2022],
    ['bloomArtifact', 'analyzeBloomArtifact', 'Bloom Artifact', 'signal.bloomArtifact', 'pixel', 0.2, '💡', `let bloom=0,c=0;const step=3;for(let y=1;y<h-1;y+=step)for(let x=1;x<w-1;x+=step){const i=(y*w+x)*4;if(p[i]>230&&p[i+1]>230&&p[i+2]>230){const nb=[p[(y*w+x-1)*4],p[(y*w+x+1)*4],p[((y-1)*w+x)*4],p[((y+1)*w+x)*4]];const avg=nb.reduce((a,b)=>a+b,0)/4;if(avg>180)bloom++;}c++;}const r=c>0?bloom/c:0;`, `if(r<0.001)score=62;else if(r<0.01)score=45;else if(r>0.05)score=35;else score=48;`, `\`Bloom: \${bloom}, Ratio: \${r.toFixed(5)}\``, 2020],
    ['gammaDistortion', 'analyzeGammaDistortion', 'Gamma Distortion', 'signal.gammaDistortion', 'statistical', 0.2, '📐', `const hist=new Float64Array(256);const step=3;let cnt=0;for(let y=0;y<h;y+=step)for(let x=0;x<w;x+=step){const i=(y*w+x)*4;const lum=Math.round(0.299*p[i]+0.587*p[i+1]+0.114*p[i+2]);hist[lum]++;cnt++;}let mid=0;for(let i=0;i<128;i++)mid+=hist[i];const midR=cnt>0?mid/cnt:0.5;const gammaEst=Math.log(midR)/Math.log(0.5);`, `if(Math.abs(gammaEst-1)<0.1)score=65;else if(Math.abs(gammaEst-1)<0.3)score=50;else if(gammaEst>2)score=30;else score=42;`, `\`Gamma est: \${gammaEst.toFixed(3)}, Mid ratio: \${midR.toFixed(3)}\``, 2018],
    ['linearPatternDetect', 'analyzeLinearPatternDetect', 'Linear Pattern', 'signal.linearPattern', 'pixel', 0.2, '📏', `let hStreak=0,vStreak=0,cnt=0;const step=2;for(let y=0;y<h;y+=step){let run=0;for(let x=1;x<w;x++){const i=(y*w+x)*4;if(Math.abs(p[i]-p[i-4])<3)run++;else{if(run>w*0.3)hStreak++;run=0;}cnt++;}if(run>w*0.3)hStreak++;}for(let x=0;x<w;x+=step){let run=0;for(let y=1;y<h;y++){const i=(y*w+x)*4,j=((y-1)*w+x)*4;if(Math.abs(p[i]-p[j])<3)run++;else{if(run>h*0.3)vStreak++;run=0;}}if(run>h*0.3)vStreak++;}const totalS=hStreak+vStreak;`, `if(totalS>20)score=70;else if(totalS>5)score=55;else if(totalS<2)score=32;else score=44;`, `\`H-streaks: \${hStreak}, V-streaks: \${vStreak}\``, 2020],
    ['dynamicRangeAnalysis', 'analyzeDynamicRangeAnalysis', 'Dynamic Range', 'signal.dynamicRange', 'statistical', 0.2, '🔆', `let minV=255,maxV=0;const step=3;for(let y=0;y<h;y+=step)for(let x=0;x<w;x+=step){const i=(y*w+x)*4;const v=Math.max(p[i],p[i+1],p[i+2]);if(v<minV)minV=v;if(v>maxV)maxV=v;}const dr=maxV-minV;`, `if(dr<50)score=68;else if(dr<120)score=55;else if(dr>230)score=30;else score=42;`, `\`Dynamic range: \${dr}, Min: \${minV}, Max: \${maxV}\``, 2018],
    ['intensityKurtosis', 'analyzeIntensityKurtosis', 'Intensity Kurtosis', 'signal.intensityKurtosis', 'statistical', 0.3, '📊', `const vals=[];const step=3;for(let y=0;y<h;y+=step)for(let x=0;x<w;x+=step){const i=(y*w+x)*4;vals.push((p[i]+p[i+1]+p[i+2])/3);}const n=vals.length;const mean=vals.reduce((a,b)=>a+b,0)/n;const m2=vals.reduce((a,b)=>a+(b-mean)**2,0)/n;const m4=vals.reduce((a,b)=>a+(b-mean)**4,0)/n;const kurt=m2>0?m4/(m2*m2)-3:0;`, `if(Math.abs(kurt)<0.5)score=66;else if(Math.abs(kurt)<1.5)score=50;else if(Math.abs(kurt)>4)score=28;else score=42;`, `\`Kurtosis: \${kurt.toFixed(3)}\``, 2019],
    ['crossGradient', 'analyzeCrossGradient', 'Cross Gradient', 'signal.crossGradient', 'pixel', 0.2, '✖️', `let cross=0,aligned=0,cnt=0;const step=3;for(let y=1;y<h-1;y+=step)for(let x=1;x<w-1;x+=step){const i=(y*w+x)*4;const gx=p[i+4]-p[i-4],gy=p[i+w*4]-p[i-w*4];if(Math.abs(gx)>10&&Math.abs(gy)>10){if(Math.abs(Math.abs(gx)-Math.abs(gy))<5)aligned++;else cross++;}cnt++;}const r=cnt>0?aligned/(aligned+cross+1):0;`, `if(r>0.3)score=68;else if(r>0.15)score=52;else if(r<0.05)score=30;else score=44;`, `\`Aligned: \${aligned}, Cross: \${cross}, Ratio: \${r.toFixed(4)}\``, 2020],
    ['pixelSymmetry', 'analyzePixelSymmetry', 'Pixel Symmetry', 'signal.pixelSymmetry', 'pixel', 0.2, '🪞', `let symDiff=0,cnt=0;const step=3;for(let y=0;y<h;y+=step)for(let x=0;x<w/2;x+=step){const l=(y*w+x)*4,r2=(y*w+(w-1-x))*4;symDiff+=Math.abs(p[l]-p[r2])+Math.abs(p[l+1]-p[r2+1])+Math.abs(p[l+2]-p[r2+2]);cnt++;}const avgSym=cnt>0?symDiff/(cnt*3):0;`, `if(avgSym<5)score=70;else if(avgSym<15)score=52;else if(avgSym>40)score=28;else score=44;`, `\`Symmetry diff: \${avgSym.toFixed(2)}\``, 2021],
    ['localEntropy', 'analyzeLocalEntropy', 'Local Entropy', 'signal.localEntropy', 'statistical', 0.3, '🧊', `const bSz=16,gx=Math.floor(w/bSz),gy=Math.floor(h/bSz);const ents=[];for(let by=0;by<gy;by++)for(let bx=0;bx<gx;bx++){const hist=new Float64Array(256);let tot=0;for(let y=0;y<bSz;y++)for(let x=0;x<bSz;x++){const i=((by*bSz+y)*w+(bx*bSz+x))*4;hist[p[i]]++;tot++;}let e=0;for(let i=0;i<256;i++){if(hist[i]>0){const pr=hist[i]/tot;e-=pr*Math.log2(pr);}}ents.push(e);}const avg=ents.reduce((a,b)=>a+b,0)/ents.length;const vari=ents.reduce((a,b)=>a+(b-avg)**2,0)/ents.length;const cv=avg>0?Math.sqrt(vari)/avg:0;`, `if(cv<0.15)score=68;else if(cv<0.3)score=52;else if(cv>0.6)score=28;else score=44;`, `\`Entropy CV: \${cv.toFixed(3)}, Avg: \${avg.toFixed(2)}\``, 2020],
    ['lumaGradientAngle', 'analyzeLumaGradientAngle', 'Luma Gradient Angle', 'signal.lumaGradientAngle', 'frequency', 0.2, '🧭', `const bins=new Float64Array(36);let cnt=0;const step=3;for(let y=1;y<h-1;y+=step)for(let x=1;x<w-1;x+=step){const i=(y*w+x)*4;const gx=p[i+4]-p[i-4],gy=p[i+w*4]-p[i-w*4];const mag=Math.sqrt(gx*gx+gy*gy);if(mag>10){let angle=Math.atan2(gy,gx)*180/Math.PI;if(angle<0)angle+=360;const bin=Math.floor(angle/10)%36;bins[bin]++;cnt++;}}let maxB=0,minB=Infinity;for(let i=0;i<36;i++){if(bins[i]>maxB)maxB=bins[i];if(bins[i]<minB)minB=bins[i];}const uniformity=maxB>0?minB/maxB:1;`, `if(uniformity>0.7)score=66;else if(uniformity>0.4)score=50;else if(uniformity<0.2)score=30;else score=44;`, `\`Angle uniformity: \${uniformity.toFixed(3)}\``, 2020],
    ['rgbCorrelation', 'analyzeRGBCorrelation', 'RGB Correlation', 'signal.rgbCorrelation', 'statistical', 0.2, '🔴', `let sumRG=0,sumRB=0,sumGB=0,sumR=0,sumG=0,sumB=0,sumR2=0,sumG2=0,sumB2=0,n=0;const step=4;for(let y=0;y<h;y+=step)for(let x=0;x<w;x+=step){const i=(y*w+x)*4;const r2=p[i],g=p[i+1],b=p[i+2];sumR+=r2;sumG+=g;sumB+=b;sumR2+=r2*r2;sumG2+=g*g;sumB2+=b*b;sumRG+=r2*g;sumRB+=r2*b;sumGB+=g*b;n++;}const corrRG=n>0?(n*sumRG-sumR*sumG)/Math.sqrt((n*sumR2-sumR*sumR)*(n*sumG2-sumG*sumG)||1):0;const avgCorr=Math.abs(corrRG);`, `if(avgCorr>0.98)score=68;else if(avgCorr>0.9)score=52;else if(avgCorr<0.5)score=30;else score=44;`, `\`RG correlation: \${corrRG.toFixed(4)}\``, 2019],
    ['isolatedPixel', 'analyzeIsolatedPixel', 'Isolated Pixel', 'signal.isolatedPixel', 'pixel', 0.2, '🔵', `let isolated=0,cnt=0;const step=2;for(let y=1;y<h-1;y+=step)for(let x=1;x<w-1;x+=step){const i=(y*w+x)*4;const c=p[i];const nb=[p[i-4],p[i+4],p[i-w*4],p[i+w*4]];const avgN=nb.reduce((a,b)=>a+b,0)/4;if(Math.abs(c-avgN)>40)isolated++;cnt++;}const r=cnt>0?isolated/cnt:0;`, `if(r<0.001)score=64;else if(r<0.01)score=48;else if(r>0.05)score=30;else score=44;`, `\`Isolated: \${isolated}, Ratio: \${r.toFixed(5)}\``, 2019],
    ['spatialCoherence', 'analyzeSpatialCoherence', 'Spatial Coherence', 'signal.spatialCoherence', 'pixel', 0.2, '🌀', `let coherent=0,incoherent=0;const step=4;for(let y=2;y<h-2;y+=step)for(let x=2;x<w-2;x+=step){const i=(y*w+x)*4;const c=p[i];const ring=[];for(let dy=-2;dy<=2;dy++)for(let dx=-2;dx<=2;dx++)if(dx!==0||dy!==0)ring.push(p[((y+dy)*w+(x+dx))*4]);const avg=ring.reduce((a,b)=>a+b,0)/ring.length;if(Math.abs(c-avg)<10)coherent++;else incoherent++;}const r=(coherent+incoherent)>0?coherent/(coherent+incoherent):0.5;`, `if(r>0.9)score=68;else if(r>0.75)score=50;else if(r<0.5)score=28;else score=44;`, `\`Coherence: \${r.toFixed(4)}\``, 2021],
    ['contourSmooth', 'analyzeContourSmooth', 'Contour Smoothness', 'signal.contourSmooth', 'pixel', 0.2, '〽️', `let smooth=0,sharp=0;const step=3;for(let y=1;y<h-1;y+=step)for(let x=1;x<w-1;x+=step){const i=(y*w+x)*4;const lap=Math.abs(4*p[i]-p[i-4]-p[i+4]-p[i-w*4]-p[i+w*4]);if(lap>20&&lap<60)smooth++;else if(lap>=60)sharp++;}const r=(smooth+sharp)>0?smooth/(smooth+sharp):0.5;`, `if(r>0.85)score=66;else if(r>0.6)score=50;else if(r<0.3)score=30;else score=44;`, `\`Smooth contours: \${smooth}, Sharp: \${sharp}\``, 2021],
    ['colorEntropy', 'analyzeColorEntropy', 'Color Entropy', 'signal.colorEntropy', 'statistical', 0.3, '🎲', `const cHist=new Map();const step=4;let total=0;for(let y=0;y<h;y+=step)for(let x=0;x<w;x+=step){const i=(y*w+x)*4;const key=((p[i]>>4)<<8)|((p[i+1]>>4)<<4)|(p[i+2]>>4);cHist.set(key,(cHist.get(key)||0)+1);total++;}let entropy=0;for(const cnt of cHist.values()){const pr=cnt/total;entropy-=pr*Math.log2(pr);}`, `if(entropy<6)score=66;else if(entropy<8)score=50;else if(entropy>11)score=30;else score=42;`, `\`Color entropy: \${entropy.toFixed(3)}\``, 2019],
    ['brightnessGradient', 'analyzeBrightnessGradient', 'Brightness Gradient', 'signal.brightnessGradient', 'pixel', 0.2, '🌓', `const rows=[];const step=4;for(let y=0;y<h;y+=step){let sum=0,cnt=0;for(let x=0;x<w;x+=step){const i=(y*w+x)*4;sum+=(p[i]+p[i+1]+p[i+2])/3;cnt++;}rows.push(cnt>0?sum/cnt:128);}let gradSum=0;for(let i=1;i<rows.length;i++)gradSum+=Math.abs(rows[i]-rows[i-1]);const avgGrad=rows.length>1?gradSum/(rows.length-1):0;`, `if(avgGrad<0.5)score=66;else if(avgGrad<2)score=50;else if(avgGrad>5)score=30;else score=44;`, `\`Brightness gradient: \${avgGrad.toFixed(3)}\``, 2018],
    ['noiseGranularity', 'analyzeNoiseGranularity', 'Noise Granularity', 'signal.noiseGranularity', 'sensor', 0.3, '🔸', `let fine=0,coarse=0;const step=2;for(let y=1;y<h-1;y+=step)for(let x=1;x<w-1;x+=step){const i=(y*w+x)*4;const d1=Math.abs(p[i]-p[i+4]),d2=Math.abs(p[i]-p[i+w*4]);if(d1>2&&d1<8&&d2>2&&d2<8)fine++;else if(d1>15||d2>15)coarse++;}const r=(fine+coarse)>0?fine/(fine+coarse):0.5;`, `if(r>0.7)score=35;else if(r>0.4)score=48;else if(r<0.15)score=66;else score=44;`, `\`Fine: \${fine}, Coarse: \${coarse}, Ratio: \${r.toFixed(3)}\``, 2020],
    ['hueConsistency', 'analyzeHueConsistency', 'Hue Consistency', 'signal.hueConsistency', 'statistical', 0.2, '🎨', `const hues=[];const step=4;for(let y=0;y<h;y+=step)for(let x=0;x<w;x+=step){const i=(y*w+x)*4;const r2=p[i]/255,g=p[i+1]/255,b=p[i+2]/255;const mx=Math.max(r2,g,b),mn=Math.min(r2,g,b),d=mx-mn;if(d>0.05){let h2=0;if(mx===r2)h2=((g-b)/d)%6;else if(mx===g)h2=(b-r2)/d+2;else h2=(r2-g)/d+4;hues.push(h2*60);}}if(hues.length<10){const cv=0;`, `score=50;}else{const avg=hues.reduce((a,b)=>a+b,0)/hues.length;const vari=hues.reduce((a,b)=>a+(b-avg)**2,0)/hues.length;const cv=avg!==0?Math.sqrt(vari)/Math.abs(avg):0;if(cv<0.3)score=66;else if(cv<0.6)score=50;else if(cv>1.5)score=28;else score=44;}`, `\`Hues sampled: \${hues.length}\``, 2019],
    ['pixelBitPlane', 'analyzePixelBitPlane', 'Pixel Bit Plane', 'signal.pixelBitPlane', 'frequency', 0.3, '💾', `const lsb=new Float64Array(256);const step=3;let cnt=0;for(let y=0;y<h;y+=step)for(let x=0;x<w;x+=step){const i=(y*w+x)*4;const bit=p[i]&1;lsb[p[i]>>1]+=bit;cnt++;}let ones=0;for(let i=0;i<256;i++)ones+=lsb[i];const lsbR=cnt>0?ones/cnt:0.5;`, `if(Math.abs(lsbR-0.5)<0.02)score=65;else if(Math.abs(lsbR-0.5)<0.05)score=50;else if(Math.abs(lsbR-0.5)>0.15)score=30;else score=44;`, `\`LSB ratio: \${lsbR.toFixed(4)}\``, 2017],
    ['contrastMap', 'analyzeContrastMapImg', 'Contrast Map', 'signal.contrastMap', 'pixel', 0.2, '🔲', `const bSz=16,gx=Math.floor(w/bSz),gy=Math.floor(h/bSz);const contrasts=[];for(let by=0;by<gy;by++)for(let bx=0;bx<gx;bx++){let mn=255,mx=0;for(let y=0;y<bSz;y++)for(let x=0;x<bSz;x++){const i=((by*bSz+y)*w+(bx*bSz+x))*4;const v=p[i];if(v<mn)mn=v;if(v>mx)mx=v;}contrasts.push(mx-mn);}const avg=contrasts.reduce((a,b)=>a+b,0)/contrasts.length;const cv=contrasts.length>1?Math.sqrt(contrasts.reduce((a,b)=>a+(b-avg)**2,0)/contrasts.length)/(avg||1):0;`, `if(cv<0.2)score=66;else if(cv<0.5)score=50;else if(cv>1.0)score=28;else score=44;`, `\`Contrast CV: \${cv.toFixed(3)}\``, 2020],
    ['flatRegionRatio', 'analyzeFlatRegionRatio', 'Flat Region Ratio', 'signal.flatRegionRatio', 'pixel', 0.2, '⬜', `let flat=0,textured=0;const step=2;for(let y=0;y<h-1;y+=step)for(let x=0;x<w-1;x+=step){const i=(y*w+x)*4;const d=Math.abs(p[i]-p[i+4])+Math.abs(p[i]-p[i+w*4]);if(d<4)flat++;else textured++;}const r=(flat+textured)>0?flat/(flat+textured):0;`, `if(r>0.8)score=70;else if(r>0.5)score=55;else if(r<0.2)score=28;else score=42;`, `\`Flat: \${flat}, Textured: \${textured}, Ratio: \${r.toFixed(3)}\``, 2019],
    ['posterizationDetect', 'analyzePosterizationDetect', 'Posterization', 'signal.posterization', 'statistical', 0.2, '🎭', `const hist=new Float64Array(256);const step=2;let cnt=0;for(let y=0;y<h;y+=step)for(let x=0;x<w;x+=step){const i=(y*w+x)*4;hist[p[i]]++;cnt++;}let gaps=0;for(let i=1;i<255;i++)if(hist[i]===0&&hist[i-1]>cnt*0.001&&hist[i+1]>cnt*0.001)gaps++;`, `if(gaps>30)score=72;else if(gaps>10)score=55;else if(gaps<3)score=30;else score=44;`, `\`Posterization gaps: \${gaps}\``, 2018],
    ['meanShiftCluster', 'analyzeMeanShiftCluster', 'Mean Shift Cluster', 'signal.meanShiftCluster', 'statistical', 0.2, '🎯', `const colorBins=new Map();const step=5;for(let y=0;y<h;y+=step)for(let x=0;x<w;x+=step){const i=(y*w+x)*4;const key=((p[i]>>5)<<6)|((p[i+1]>>5)<<3)|(p[i+2]>>5);colorBins.set(key,(colorBins.get(key)||0)+1);}const clusters=colorBins.size;`, `if(clusters<20)score=70;else if(clusters<50)score=55;else if(clusters>200)score=28;else score=44;`, `\`Color clusters: \${clusters}\``, 2020],
    ['gradientMagnitudeHist', 'analyzeGradientMagnitudeHist', 'Gradient Magnitude', 'signal.gradientMagHist', 'pixel', 0.3, '📈', `const bins=new Float64Array(50);let cnt=0;const step=2;for(let y=1;y<h-1;y+=step)for(let x=1;x<w-1;x+=step){const i=(y*w+x)*4;const gx=p[i+4]-p[i-4],gy=p[i+w*4]-p[i-w*4];const mag=Math.sqrt(gx*gx+gy*gy);const bin=Math.min(49,Math.floor(mag/5));bins[bin]++;cnt++;}let peak=0;for(let i=0;i<50;i++)if(bins[i]>bins[peak])peak=i;const lowR=cnt>0?bins[0]/cnt:0;`, `if(lowR>0.7)score=66;else if(lowR>0.4)score=50;else if(lowR<0.2)score=30;else score=44;`, `\`Peak bin: \${peak}, Low ratio: \${lowR.toFixed(3)}\``, 2020],
];
for (const [file, fn, name, key, cat, wt, icon, logic, scoring, det, yr] of M) {
    const code = `/**\n * ${name}\n * AI detection method\n */\nimport type { AnalysisMethod } from "../../types";\n\nexport function ${fn}(p: Uint8ClampedArray, w: number, h: number): AnalysisMethod {\n    if (w < 16 || h < 16) {\n        return { name: "${name}", nameKey: "${key}", category: "${cat}", score: 50, weight: ${wt}, description: "Image too small", descriptionKey: "${key}.error", icon: "${icon}" };\n    }\n    ${logic}\n    let score: number;\n    ${scoring}\n    return {\n        name: "${name}", nameKey: "${key}", category: "${cat}", score, weight: ${wt},\n        description: score > 55 ? "${name} pattern suggests AI generation" : "Natural ${name.toLowerCase()} — consistent with real image",\n        descriptionKey: score > 55 ? "${key}.ai" : "${key}.real", icon: "${icon}",\n        details: ${det},\n    };\n}\n`;
    fs.writeFileSync(p.join(dir, file + '.ts'), code);
}
console.log('Created', M.length, 'image methods');
