const fs = require('fs');
const path = require('path');
const base = path.join(__dirname, '..', 'src', 'app', 'methods');

const methods = [
    {
        id: "median_filter", cat: "pixel",
        en: { name: "Median Filtering Detection", description: "Detects traces of median filtering applied to suppress JPEG artifacts and hide tampering evidence.", algorithm: "Median Filtered Image Forensics via First-Digit Analysis", mechanism: "Analyzes pixel value distributions to detect the smoothing artifacts characteristic of median filtering. Median filtering removes high-frequency noise but leaves detectable traces in the histogram and pixel co-occurrence matrices.", parameters: "Window sizes: 3×3, 5×5, 7×7; Feature: histogram bin analysis, pixel autocorrelation, streak analysis", accuracy: "High — 82-94%", source: "Kirchner, M. & Fridrich, J. (2010) — On Detection of Median Filtering in Digital Images, SPIE Electronic Imaging", useCase: "Detecting anti-forensic median filtering used to conceal image manipulation or AI generation traces", strengths: "• Robust detection of median filtering traces\\n• Works across different window sizes\\n• Effective anti-forensic countermeasure\\n• Low false positive rate", limitations: "• Cannot detect very light filtering\\n• May confuse with other smoothing filters\\n• Requires sufficient image resolution\\n• Performance degrades with heavy JPEG compression" },
        vi: { name: "Phát hiện lọc trung vị", description: "Phát hiện dấu vết lọc trung vị được áp dụng để che giấu bằng chứng chỉnh sửa ảnh.", algorithm: "Pháp y ảnh lọc trung vị qua phân tích chữ số đầu", mechanism: "Phân tích phân bố giá trị pixel để phát hiện hiện vật đặc trưng của lọc trung vị.", parameters: "Cửa sổ: 3×3, 5×5, 7×7; Đặc trưng: phân tích bin histogram", accuracy: "Cao — 82-94%", source: "Kirchner & Fridrich (2010), SPIE Electronic Imaging", useCase: "Phát hiện lọc chống pháp y dùng để che giấu chỉnh sửa hoặc dấu vết AI", strengths: "• Phát hiện robust dấu vết lọc trung vị\\n• Hoạt động với nhiều kích thước cửa sổ\\n• Biện pháp chống pháp y hiệu quả\\n• Tỷ lệ dương tính giả thấp", limitations: "• Không phát hiện lọc rất nhẹ\\n• Có thể nhầm với bộ lọc mịn khác\\n• Cần độ phân giải đủ\\n• Giảm hiệu suất với nén JPEG nặng" }
    },
    {
        id: "resampling", cat: "statistical",
        en: { name: "Resampling Detection", description: "Detects interpolation artifacts from image scaling, rotation, or skewing operations.", algorithm: "Periodic Correlation Detection in Resampled Signals", mechanism: "Analyzes periodic correlations introduced by resampling operations. When an image is scaled or rotated, interpolation creates detectable periodic patterns in pixel derivatives that can be revealed through spectral analysis.", parameters: "Analysis: EM algorithm, Radon transform projection, Derivative filter: [-1, 1], Spectrum: 64-point DFT", accuracy: "High — 85-95%", source: "Popescu, A.C. & Farid, H. (2005) — Exposing Digital Forgeries by Detecting Traces of Resampling, IEEE TSP", useCase: "Detecting geometric transformations applied during image splicing or composition", strengths: "• Highly accurate for detecting scaling/rotation\\n• Theoretically well-grounded\\n• Can estimate resampling factor\\n• Works on different interpolation methods", limitations: "• Requires large homogeneous regions\\n• May fail on heavily textured areas\\n• Computationally intensive EM fitting\\n• JPEG compression can mask traces" },
        vi: { name: "Phát hiện tái lấy mẫu", description: "Phát hiện hiện vật nội suy từ các thao tác co giãn, xoay hoặc nghiêng ảnh.", algorithm: "Phát hiện tương quan tuần hoàn trong tín hiệu tái lấy mẫu", mechanism: "Phân tích tương quan tuần hoàn do tái lấy mẫu tạo ra. Khi ảnh bị co giãn hoặc xoay, nội suy tạo mẫu tuần hoàn phát hiện được qua phân tích phổ.", parameters: "Thuật toán EM, chiếu Radon, Bộ lọc đạo hàm: [-1, 1], Phổ: DFT 64 điểm", accuracy: "Cao — 85-95%", source: "Popescu & Farid (2005), IEEE TSP", useCase: "Phát hiện biến đổi hình học trong ghép ảnh hoặc tổng hợp", strengths: "• Độ chính xác cao cho phát hiện co giãn/xoay\\n• Nền tảng lý thuyết vững\\n• Ước lượng được hệ số tái lấy mẫu\\n• Hoạt động với nhiều phương pháp nội suy", limitations: "• Cần vùng đồng nhất lớn\\n• Có thể thất bại trên vùng kết cấu nặng\\n• Tốn tài nguyên cho khớp EM\\n• Nén JPEG có thể che dấu vết" }
    },
    {
        id: "contrast_enhancement", cat: "statistical",
        en: { name: "Contrast Enhancement Detection", description: "Detects histogram manipulation artifacts from contrast adjustments like levels, curves, or gamma correction.", algorithm: "Peak-Gap Artifact Detection in Pixel Value Histograms", mechanism: "Contrast enhancement operations create characteristic peak-gap patterns in the pixel intensity histogram. This method detects these artifacts by analyzing the regularity and spacing of peaks and valleys.", parameters: "Histogram bins: 256, Gap threshold: adaptive, Peak detection: local maxima, Smoothing: Gaussian σ=1", accuracy: "High — 80-92%", source: "Stamm, M.C. & Liu, K.J.R. (2008) — Forensic Detection of Image Manipulation Using Statistical Intrinsic Fingerprints, IEEE ICME", useCase: "Detecting brightness/contrast adjustments used to unify appearance in composited images", strengths: "• Detects multiple enhancement types\\n• Works on both global and local adjustments\\n• Fast histogram-based analysis\\n• Well-established forensic technique", limitations: "• Cannot detect very subtle adjustments\\n• Multiple enhancements may cancel artifacts\\n• JPEG compression affects histogram\\n• Limited to intensity-based manipulations" },
        vi: { name: "Phát hiện tăng cường tương phản", description: "Phát hiện hiện vật từ điều chỉnh tương phản như levels, curves hoặc gamma.", algorithm: "Phát hiện hiện vật đỉnh-khoảng trong histogram giá trị pixel", mechanism: "Tăng cường tương phản tạo mẫu đỉnh-khoảng đặc trưng trong histogram cường độ pixel.", parameters: "Bin histogram: 256, Ngưỡng khoảng: thích ứng, Phát hiện đỉnh: cực đại cục bộ", accuracy: "Cao — 80-92%", source: "Stamm & Liu (2008), IEEE ICME", useCase: "Phát hiện điều chỉnh sáng/tương phản trong ảnh ghép", strengths: "• Phát hiện nhiều loại tăng cường\\n• Hoạt động cả điều chỉnh toàn cục và cục bộ\\n• Phân tích histogram nhanh\\n• Kỹ thuật pháp y được thiết lập", limitations: "• Không phát hiện điều chỉnh rất tinh tế\\n• Nhiều tăng cường có thể triệt tiêu\\n• Nén JPEG ảnh hưởng histogram\\n• Giới hạn ở thao tác dựa cường độ" }
    },
    {
        id: "brisque", cat: "statistical",
        en: { name: "Blind Image Quality Assessment (BRISQUE)", description: "Uses natural scene statistics to evaluate image quality and detect distortions indicating AI generation or manipulation.", algorithm: "Blind/Referenceless Image Spatial Quality Evaluator", mechanism: "Computes locally normalized luminance coefficients and fits them to a generalized Gaussian distribution. The shape and variance parameters are used as features to detect deviations from natural image statistics.", parameters: "Patch size: 7×7, MSCN coefficients, GGD fitting, Features: 36-dimensional, SVR model", accuracy: "Medium-High — 78-90%", source: "Mittal, A. et al. (2012) — No-Reference Image Quality Assessment in the Spatial Domain, IEEE TIP", useCase: "Evaluating naturalness of images to flag AI-generated or heavily processed content", strengths: "• No reference image needed\\n• Fast computation\\n• Correlates well with human perception\\n• Detects multiple distortion types", limitations: "• May not detect high-quality AI images\\n• Sensitive to legitimate processing\\n• Requires calibration per domain\\n• Not specific to any forgery type" },
        vi: { name: "Đánh giá chất lượng ảnh mù (BRISQUE)", description: "Sử dụng thống kê cảnh tự nhiên để đánh giá chất lượng ảnh và phát hiện biến dạng do AI.", algorithm: "Đánh giá chất lượng không gian ảnh không tham chiếu", mechanism: "Tính hệ số độ sáng chuẩn hóa cục bộ và khớp với phân bố Gaussian tổng quát.", parameters: "Vùng: 7×7, Hệ số MSCN, Khớp GGD, Đặc trưng: 36 chiều", accuracy: "Trung bình-Cao — 78-90%", source: "Mittal et al. (2012), IEEE TIP", useCase: "Đánh giá tính tự nhiên của ảnh để gắn cờ nội dung AI", strengths: "• Không cần ảnh tham chiếu\\n• Tính toán nhanh\\n• Tương quan tốt với nhận thức con người\\n• Phát hiện nhiều loại biến dạng", limitations: "• Có thể không phát hiện ảnh AI chất lượng cao\\n• Nhạy cảm với xử lý hợp lệ\\n• Cần hiệu chuẩn theo miền\\n• Không đặc trưng cho loại giả mạo nào" }
    },
    {
        id: "demosaicing", cat: "sensor",
        en: { name: "Demosaicing Artifact Analysis", description: "Analyzes color filter array demosaicing artifacts to verify camera origin and detect synthetic images.", algorithm: "CFA Interpolation Pattern Consistency Check", mechanism: "Real camera images exhibit specific demosaicing patterns from Bayer CFA interpolation. This method analyzes inter-channel correlation patterns at pixel level to detect inconsistencies.", parameters: "CFA pattern: RGGB, Interpolation: bilinear/AHD/VNG, Correlation window: 5×5, Analysis: cross-channel", accuracy: "High — 83-93%", source: "Popescu, A.C. & Farid, H. (2005) — Exposing Digital Forgeries by Detecting Traces of Demosaicing, ACM IHMMSec", useCase: "Verifying camera sensor origin by checking CFA demosaicing traces in images", strengths: "• Strongly linked to physical sensor\\n• Difficult to forge convincingly\\n• Works across camera brands\\n• Detects both AI and spliced images", limitations: "• Not applicable to RAW images\\n• Some cameras use non-Bayer patterns\\n• Heavy post-processing may mask traces\\n• Requires sufficient spatial resolution" },
        vi: { name: "Phân tích hiện vật khử mosaic", description: "Phân tích hiện vật khử mosaic CFA để xác minh nguồn gốc camera và phát hiện ảnh tổng hợp.", algorithm: "Kiểm tra tính nhất quán mẫu nội suy CFA", mechanism: "Ảnh camera thật có mẫu khử mosaic đặc trưng từ nội suy CFA Bayer.", parameters: "Mẫu CFA: RGGB, Nội suy: bilinear/AHD/VNG, Cửa sổ: 5×5", accuracy: "Cao — 83-93%", source: "Popescu & Farid (2005), ACM IHMMSec", useCase: "Xác minh nguồn gốc cảm biến camera qua dấu vết khử mosaic", strengths: "• Liên kết chặt với cảm biến vật lý\\n• Khó giả mạo thuyết phục\\n• Hoạt động qua nhiều hãng camera\\n• Phát hiện cả ảnh AI và ghép", limitations: "• Không áp dụng cho ảnh RAW\\n• Một số camera dùng mẫu không phải Bayer\\n• Hậu xử lý nặng có thể che dấu vết\\n• Cần độ phân giải không gian đủ" }
    },
    {
        id: "steganalysis", cat: "pixel",
        en: { name: "Steganalysis (Hidden Data Detection)", description: "Detects hidden data embedded in images through steganographic techniques, indicating potential manipulation.", algorithm: "Rich Model Steganalysis with Spatial Domain Features", mechanism: "Extracts high-dimensional feature sets from spatial residuals using multiple filter kernels. Analyzes statistical properties disrupted when data is hidden in LSBs or transform coefficients.", parameters: "Feature dimension: 34671 (full SRM), Filters: 30 linear + nonlinear, Quantization: T=1,2,3, Classifier: ensemble", accuracy: "High — 80-95%", source: "Fridrich, J. & Kodovsky, J. (2012) — Rich Models for Steganalysis of Digital Images, IEEE TIFS", useCase: "Detecting hidden payloads in images that may indicate data exfiltration or tamper concealment", strengths: "• Extremely high-dimensional features\\n• Covers wide range of embedding methods\\n• State-of-the-art detection rates\\n• Generalizes across steganographic algorithms", limitations: "• Very high computational cost\\n• Requires training data per embedding rate\\n• Large feature vectors need dimensionality reduction\\n• May produce false positives on noisy images" },
        vi: { name: "Phân tích giấu tin (Phát hiện dữ liệu ẩn)", description: "Phát hiện dữ liệu ẩn được nhúng trong ảnh qua kỹ thuật giấu tin.", algorithm: "Phân tích giấu tin mô hình phong phú với đặc trưng không gian", mechanism: "Trích xuất tập đặc trưng đa chiều từ phần dư không gian sử dụng nhiều bộ lọc.", parameters: "Chiều đặc trưng: 34671 (SRM đầy đủ), Bộ lọc: 30, Lượng tử: T=1,2,3", accuracy: "Cao — 80-95%", source: "Fridrich & Kodovsky (2012), IEEE TIFS", useCase: "Phát hiện payload ẩn trong ảnh có thể chỉ ra rò rỉ dữ liệu", strengths: "• Đặc trưng chiều cực cao\\n• Bao phủ nhiều phương pháp nhúng\\n• Tỷ lệ phát hiện tiên tiến\\n• Tổng quát hóa qua các thuật toán giấu tin", limitations: "• Chi phí tính toán rất cao\\n• Cần dữ liệu huấn luyện theo tỷ lệ nhúng\\n• Vector đặc trưng lớn cần giảm chiều\\n• Có thể dương tính giả trên ảnh nhiễu" }
    },
    {
        id: "thumbnail_analysis", cat: "metadata",
        en: { name: "Thumbnail Consistency Analysis", description: "Compares embedded EXIF thumbnail with the main image to detect post-capture modifications.", algorithm: "Embedded Thumbnail vs Main Image Structural Comparison", mechanism: "JPEG files often contain embedded thumbnails generated at capture time. When the main image is later edited, the thumbnail may remain unchanged, creating detectable inconsistencies.", parameters: "Comparison: SSIM, Histogram correlation, Pixel hash, Thumbnail source: EXIF APP1, Resolution: 160×120", accuracy: "Medium-High — 75-90%", source: "Kee, E. & Farid, H. (2011) — Digital Image Authentication from Thumbnails, SPIE Electronic Imaging", useCase: "Detecting image editing by comparing original thumbnail with potentially modified main image", strengths: "• Simple and fast analysis\\n• High confidence when thumbnail differs\\n• Non-invasive metadata check\\n• Works on any JPEG with embedded thumbnail", limitations: "• Many images lack embedded thumbnails\\n• Some editors update thumbnails too\\n• AI-generated images may not have thumbnails\\n• Limited to JPEG format" },
        vi: { name: "Phân tích nhất quán thumbnail", description: "So sánh thumbnail EXIF nhúng với ảnh chính để phát hiện chỉnh sửa sau chụp.", algorithm: "So sánh cấu trúc thumbnail nhúng với ảnh chính", mechanism: "File JPEG thường chứa thumbnail nhúng tạo lúc chụp. Khi ảnh chính bị sửa, thumbnail có thể giữ nguyên.", parameters: "So sánh: SSIM, Tương quan histogram, Hash pixel, Nguồn: EXIF APP1", accuracy: "Trung bình-Cao — 75-90%", source: "Kee & Farid (2011), SPIE Electronic Imaging", useCase: "Phát hiện chỉnh sửa ảnh qua so sánh thumbnail gốc với ảnh chính", strengths: "• Phân tích đơn giản và nhanh\\n• Độ tin cậy cao khi thumbnail khác\\n• Kiểm tra metadata không xâm lấn\\n• Hoạt động trên mọi JPEG có thumbnail nhúng", limitations: "• Nhiều ảnh không có thumbnail nhúng\\n• Một số trình sửa cập nhật thumbnail\\n• Ảnh AI có thể không có thumbnail\\n• Giới hạn định dạng JPEG" }
    },
    {
        id: "perceptual_hash", cat: "statistical",
        en: { name: "Perceptual Hash Analysis", description: "Uses perceptual hashing algorithms to detect near-duplicate images and identify localized manipulations.", algorithm: "Multi-Scale Perceptual Hashing with DCT and Gradient Features", mechanism: "Computes compact perceptual hash fingerprints (pHash, dHash) that capture the essential visual structure of an image. Comparing hash distances between image regions reveals localized edits.", parameters: "Hash types: pHash (DCT-based), dHash (gradient), aHash (average), Hash size: 64-bit, Block: 8×8", accuracy: "Medium — 70-85%", source: "Zauner, C. (2010) — Implementation and Benchmarking of Perceptual Image Hash Functions, Master Thesis, TU Graz", useCase: "Near-duplicate detection and localized manipulation identification through hash comparison", strengths: "• Very fast computation\\n• Rotation and scale tolerant\\n• Compact representation\\n• Good for batch comparison", limitations: "• Limited sensitivity to subtle changes\\n• Cannot localize specific manipulations\\n• Hash collisions possible\\n• Not suitable for fine-grained analysis" },
        vi: { name: "Phân tích hash nhận thức", description: "Sử dụng thuật toán hash nhận thức để phát hiện ảnh gần giống và xác định chỉnh sửa cục bộ.", algorithm: "Hash nhận thức đa tỷ lệ với DCT và gradient", mechanism: "Tính vân tay hash nhận thức (pHash, dHash) nắm bắt cấu trúc thị giác thiết yếu.", parameters: "Loại hash: pHash (DCT), dHash (gradient), aHash (trung bình), Kích thước: 64-bit", accuracy: "Trung bình — 70-85%", source: "Zauner (2010), Luận văn thạc sĩ, TU Graz", useCase: "Phát hiện ảnh gần giống và xác định chỉnh sửa cục bộ", strengths: "• Tính toán rất nhanh\\n• Chịu xoay và co giãn\\n• Biểu diễn gọn nhẹ\\n• Tốt cho so sánh hàng loạt", limitations: "• Nhạy cảm hạn chế với thay đổi tinh tế\\n• Không định vị thao tác cụ thể\\n• Có thể xảy ra va chạm hash\\n• Không phù hợp phân tích chi tiết" }
    },
    {
        id: "illuminant_map", cat: "pixel",
        en: { name: "Illuminant Map Analysis", description: "Detects inconsistent illumination sources across image regions by estimating local color temperature maps.", algorithm: "Physics-Based Illuminant Estimation for Forgery Detection", mechanism: "Estimates local illuminant color using inverse-intensity chromaticity and generalized grayworld algorithms. Spliced regions from different lighting show inconsistent illuminant estimates.", parameters: "Estimation: IIC + GGW, Superpixel: SLIC (k=200), Distance: angular, Clustering: k-means", accuracy: "Medium-High — 75-88%", source: "Riess, C. & Angelopoulou, E. (2010) — Scene Illumination as an Indicator of Image Manipulation, IEEE WIFS", useCase: "Detecting spliced regions by identifying inconsistent lighting conditions within a single image", strengths: "• Physics-based approach\\n• Detects cross-image splicing\\n• Visualizable as color map\\n• Complementary to other methods", limitations: "• Assumes single illuminant per region\\n• Fails on complex multi-light scenes\\n• Requires sufficient color variance\\n• Sensitive to specular highlights" },
        vi: { name: "Phân tích bản đồ chiếu sáng", description: "Phát hiện nguồn chiếu sáng không nhất quán giữa các vùng ảnh qua ước lượng bản đồ nhiệt độ màu.", algorithm: "Ước lượng nguồn sáng dựa vật lý cho phát hiện giả mạo", mechanism: "Ước lượng màu nguồn sáng cục bộ sử dụng IIC và thuật toán grayworld tổng quát.", parameters: "Ước lượng: IIC + GGW, Siêu pixel: SLIC (k=200), Khoảng cách: góc", accuracy: "Trung bình-Cao — 75-88%", source: "Riess & Angelopoulou (2010), IEEE WIFS", useCase: "Phát hiện vùng ghép qua điều kiện chiếu sáng không nhất quán", strengths: "• Tiếp cận dựa vật lý\\n• Phát hiện ghép ảnh chéo\\n• Trực quan hóa bằng bản đồ màu\\n• Bổ sung cho các phương pháp khác", limitations: "• Giả định một nguồn sáng mỗi vùng\\n• Thất bại trên cảnh đa nguồn sáng\\n• Cần phương sai màu đủ\\n• Nhạy cảm với phản xạ gương" }
    },
    {
        id: "radon_transform", cat: "frequency",
        en: { name: "Radon Transform Analysis", description: "Uses the Radon transform to detect directional artifacts and periodic patterns indicating image manipulation.", algorithm: "Radon Domain Feature Extraction for Forgery Detection", mechanism: "Projects image content along multiple angles using the Radon transform, creating a sinogram representation. Manipulated regions produce anomalous directional patterns in the Radon domain.", parameters: "Angles: 0-179° (1° step), Projection: line integral, Domain: spatial→Radon, Feature: sinogram variance", accuracy: "Medium-High — 76-88%", source: "Mahdian, B. & Saic, S. (2008) — Blind Authentication Using Periodic Properties of Interpolation, IEEE TIFS", useCase: "Detecting geometric manipulation and resampling through directional artifact analysis", strengths: "• Detects directional manipulation artifacts\\n• Robust to noise\\n• Complements frequency domain methods\\n• Can reveal hidden periodicity", limitations: "• Computationally expensive for large images\\n• Limited to directional artifacts\\n• Requires careful parameter tuning\\n• May miss non-directional forgeries" },
        vi: { name: "Phân tích biến đổi Radon", description: "Dùng biến đổi Radon để phát hiện hiện vật hướng và mẫu tuần hoàn chỉ ra thao túng ảnh.", algorithm: "Trích xuất đặc trưng miền Radon cho phát hiện giả mạo", mechanism: "Chiếu nội dung ảnh theo nhiều góc sử dụng biến đổi Radon, tạo biểu diễn sinogram.", parameters: "Góc: 0-179° (bước 1°), Chiếu: tích phân đường, Đặc trưng: phương sai sinogram", accuracy: "Trung bình-Cao — 76-88%", source: "Mahdian & Saic (2008), IEEE TIFS", useCase: "Phát hiện thao túng hình học và tái lấy mẫu qua phân tích hiện vật hướng", strengths: "• Phát hiện hiện vật thao túng hướng\\n• Bền với nhiễu\\n• Bổ sung phương pháp miền tần số\\n• Có thể phát hiện tuần hoàn ẩn", limitations: "• Tốn tài nguyên cho ảnh lớn\\n• Giới hạn ở hiện vật hướng\\n• Cần tinh chỉnh tham số\\n• Có thể bỏ sót giả mạo không hướng" }
    },
    {
        id: "zernike_moments", cat: "statistical",
        en: { name: "Zernike Moment Analysis", description: "Uses rotation-invariant Zernike moments as descriptors for detecting duplicated and manipulated image regions.", algorithm: "Zernike Moment-Based Block Matching for Copy-Move Detection", mechanism: "Computes complex Zernike moments for image blocks, providing rotation-invariant descriptors. Matching blocks with similar moment vectors identifies duplicated regions even after geometric transformations.", parameters: "Order: up to 12, Block size: 16×16, Matching: Euclidean distance, Threshold: adaptive", accuracy: "High — 82-93%", source: "Ryu, S.J. et al. (2013) — Rotation Invariant Localization of Duplicated Image Regions Based on Zernike Moments, IEEE TIFS", useCase: "Detecting copy-move forgeries robust to rotation and scaling transformations", strengths: "• Rotation invariant detection\\n• Handles scaled copies\\n• Mathematically rigorous descriptors\\n• Works on complex textures", limitations: "• Computationally expensive moment calculation\\n• High-order moments sensitive to noise\\n• Block size affects sensitivity\\n• Memory intensive for large images" },
        vi: { name: "Phân tích moment Zernike", description: "Sử dụng moment Zernike bất biến xoay làm mô tả để phát hiện vùng ảnh trùng lặp và bị thao túng.", algorithm: "Khớp khối dựa moment Zernike cho phát hiện sao chép-di chuyển", mechanism: "Tính moment Zernike phức cho các khối ảnh, cung cấp mô tả bất biến xoay.", parameters: "Bậc: đến 12, Khối: 16×16, Khớp: khoảng cách Euclid, Ngưỡng: thích ứng", accuracy: "Cao — 82-93%", source: "Ryu et al. (2013), IEEE TIFS", useCase: "Phát hiện giả mạo sao chép-di chuyển bền với biến đổi xoay và co giãn", strengths: "• Phát hiện bất biến xoay\\n• Xử lý bản sao co giãn\\n• Mô tả chặt chẽ toán học\\n• Hoạt động trên kết cấu phức tạp", limitations: "• Tốn tài nguyên tính moment\\n• Moment bậc cao nhạy nhiễu\\n• Kích thước khối ảnh hưởng độ nhạy\\n• Tốn bộ nhớ cho ảnh lớn" }
    },
    {
        id: "camera_model", cat: "sensor",
        en: { name: "Camera Model Identification", description: "Identifies the source camera model through sensor noise patterns and processing pipeline fingerprints.", algorithm: "Sensor-Based Camera Source Identification via Processing Pipeline Analysis", mechanism: "Each camera model has a unique processing pipeline including CFA interpolation, white balancing, color correction, and JPEG compression. This method extracts features from these processing steps to identify the source camera.", parameters: "Features: color processing, CFA interpolation, JPEG tables, Classifier: SVM/RF, Training: per-model", accuracy: "High — 85-96%", source: "Lukas, J. et al. (2006) — Digital Camera Identification from Sensor Pattern Noise, IEEE TIFS", useCase: "Verifying the claimed source camera and detecting images from unknown or AI sources", strengths: "• High accuracy camera identification\\n• Based on physical sensor properties\\n• Difficult to spoof\\n• Works across camera brands", limitations: "• Requires reference images from known cameras\\n• Performance varies by camera model\\n• Social media compression reduces accuracy\\n• Cannot identify specific camera instance" },
        vi: { name: "Nhận dạng mẫu camera", description: "Nhận dạng mẫu camera nguồn qua mẫu nhiễu cảm biến và vân tay pipeline xử lý.", algorithm: "Nhận dạng nguồn camera dựa cảm biến qua phân tích pipeline xử lý", mechanism: "Mỗi mẫu camera có pipeline xử lý riêng biệt. Phương pháp này trích xuất đặc trưng để nhận dạng mẫu camera.", parameters: "Đặc trưng: xử lý màu, nội suy CFA, bảng JPEG, Phân loại: SVM/RF", accuracy: "Cao — 85-96%", source: "Lukas et al. (2006), IEEE TIFS", useCase: "Xác minh camera nguồn và phát hiện ảnh từ nguồn AI không xác định", strengths: "• Nhận dạng camera độ chính xác cao\\n• Dựa trên thuộc tính cảm biến vật lý\\n• Khó giả mạo\\n• Hoạt động qua nhiều hãng camera", limitations: "• Cần ảnh tham chiếu từ camera đã biết\\n• Hiệu suất khác nhau theo mẫu camera\\n• Nén mạng xã hội giảm độ chính xác\\n• Không nhận dạng camera cụ thể" }
    },
    {
        id: "image_phylogeny", cat: "statistical",
        en: { name: "Image Phylogeny Analysis", description: "Tracks the manipulation history and ancestry of images through transformation chain analysis.", algorithm: "Image Phylogeny Tree Reconstruction via Pairwise Dissimilarity", mechanism: "Estimates the transformation history of an image by analyzing degradation patterns. Each edit operation leaves cumulative traces that can be ordered into a phylogeny tree.", parameters: "Dissimilarity: SSIM-based, Tree: minimum spanning, Features: compression artifacts, Transform: chain", accuracy: "Medium — 70-85%", source: "Dias, Z. et al. (2012) — Image Phylogeny by Minimal Spanning Trees, IEEE TIFS", useCase: "Reconstructing the editing history of potentially manipulated images", strengths: "• Reveals manipulation chain\\n• Estimates editing order\\n• Works with multiple transformations\\n• Useful for provenance tracking", limitations: "• Requires multiple image versions\\n• Cannot detect single-step edits\\n• Tree reconstruction may be ambiguous\\n• Computationally intensive pairwise comparison" },
        vi: { name: "Phân tích phả hệ ảnh", description: "Theo dõi lịch sử thao túng và nguồn gốc của ảnh qua phân tích chuỗi biến đổi.", algorithm: "Tái tạo cây phả hệ ảnh qua độ khác biệt cặp", mechanism: "Ước lượng lịch sử biến đổi bằng phân tích mẫu suy giảm. Mỗi thao tác để lại dấu vết tích lũy.", parameters: "Độ khác biệt: dựa SSIM, Cây: bao trùm tối thiểu, Đặc trưng: hiện vật nén", accuracy: "Trung bình — 70-85%", source: "Dias et al. (2012), IEEE TIFS", useCase: "Tái tạo lịch sử chỉnh sửa của ảnh có khả năng bị thao túng", strengths: "• Phát hiện chuỗi thao túng\\n• Ước lượng thứ tự chỉnh sửa\\n• Hoạt động với nhiều biến đổi\\n• Hữu ích cho theo dõi nguồn gốc", limitations: "• Cần nhiều phiên bản ảnh\\n• Không phát hiện sửa một bước\\n• Tái tạo cây có thể mơ hồ\\n• Tốn tài nguyên so sánh cặp" }
    },
    {
        id: "blocking_artifact", cat: "frequency",
        en: { name: "Blocking Artifact Grid Analysis", description: "Analyzes JPEG block boundary artifacts to detect inconsistent compression grids indicating tampering.", algorithm: "Block Artifact Grid (BAG) Extraction and Consistency Analysis", mechanism: "JPEG compression creates an 8×8 block grid. When a region is spliced from a differently compressed source, the block grid alignment becomes inconsistent.", parameters: "Block size: 8×8, Grid detection: cross-boundary gradient, Alignment: phase analysis, Map: block visibility", accuracy: "High — 80-92%", source: "Fan, Z. & de Queiroz, R. (2003) — Identification of Bitmap Compression History, IEEE TIP", useCase: "Detecting spliced regions by finding JPEG compression grid inconsistencies", strengths: "• Directly linked to JPEG compression\\n• Can localize tampered regions\\n• Well-understood theoretical basis\\n• Effective on single-compressed images", limitations: "• Only works on JPEG images\\n• Double compression can mask artifacts\\n• Requires sufficient image quality\\n• May miss small tampered regions" },
        vi: { name: "Phân tích lưới hiện vật khối", description: "Phân tích hiện vật ranh giới khối JPEG để phát hiện lưới nén không nhất quán.", algorithm: "Trích xuất và phân tích nhất quán lưới hiện vật khối (BAG)", mechanism: "Nén JPEG tạo lưới khối 8×8. Khi vùng ghép từ nguồn nén khác, căn chỉnh lưới trở nên không nhất quán.", parameters: "Khối: 8×8, Phát hiện lưới: gradient xuyên biên, Căn chỉnh: phân tích pha", accuracy: "Cao — 80-92%", source: "Fan & de Queiroz (2003), IEEE TIP", useCase: "Phát hiện vùng ghép qua không nhất quán lưới nén JPEG", strengths: "• Liên kết trực tiếp với nén JPEG\\n• Có thể định vị vùng bị sửa\\n• Nền tảng lý thuyết rõ ràng\\n• Hiệu quả trên ảnh nén đơn", limitations: "• Chỉ hoạt động trên ảnh JPEG\\n• Nén kép có thể che hiện vật\\n• Cần chất lượng ảnh đủ\\n• Có thể bỏ sót vùng sửa nhỏ" }
    },
    {
        id: "efficientnet_detection", cat: "sensor",
        en: { name: "EfficientNet Feature Detection", description: "Uses EfficientNet deep features to detect AI-generated and manipulated images through learned representations.", algorithm: "Transfer Learning with EfficientNet-B0 for Synthetic Image Detection", mechanism: "Extracts deep feature representations using a pre-trained EfficientNet backbone. The learned features capture subtle statistical regularities specific to different image generation methods.", parameters: "Architecture: EfficientNet-B0, Input: 224×224, Features: 1280-dim, Pooling: global average, Classifier: FC", accuracy: "Very High — 90-98%", source: "Bonettini, N. et al. (2021) — Video Face Manipulation Detection Through Ensemble of CNNs, ICPR", useCase: "High-accuracy detection of AI-generated images using deep neural network features", strengths: "• State-of-the-art detection accuracy\\n• Learns complex manipulation patterns\\n• Transfer learning reduces training needs\\n• Ensemble-friendly architecture", limitations: "• Requires GPU for efficient inference\\n• May not generalize to unseen generators\\n• Black-box decision making\\n• Large model size" },
        vi: { name: "Phát hiện đặc trưng EfficientNet", description: "Sử dụng đặc trưng sâu EfficientNet để phát hiện ảnh AI qua biểu diễn học được.", algorithm: "Học chuyển giao với EfficientNet-B0 cho phát hiện ảnh tổng hợp", mechanism: "Trích xuất biểu diễn đặc trưng sâu sử dụng backbone EfficientNet huấn luyện sẵn.", parameters: "Kiến trúc: EfficientNet-B0, Đầu vào: 224×224, Đặc trưng: 1280 chiều", accuracy: "Rất cao — 90-98%", source: "Bonettini et al. (2021), ICPR", useCase: "Phát hiện ảnh AI độ chính xác cao sử dụng đặc trưng mạng nơ-ron sâu", strengths: "• Độ chính xác phát hiện tiên tiến\\n• Học mẫu thao túng phức tạp\\n• Học chuyển giao giảm nhu cầu huấn luyện\\n• Kiến trúc thân thiện ensemble", limitations: "• Cần GPU cho suy luận hiệu quả\\n• Có thể không tổng quát hóa cho bộ tạo mới\\n• Quyết định hộp đen\\n• Kích thước mô hình lớn" }
    },
    {
        id: "attention_consistency", cat: "sensor",
        en: { name: "Attention Map Consistency", description: "Analyzes spatial attention patterns to detect inconsistencies typical of AI-generated images.", algorithm: "Self-Attention Consistency Analysis for Synthetic Image Detection", mechanism: "AI-generated images often exhibit unnatural attention patterns where different regions show inconsistent levels of detail. This method analyzes local contrast, detail density, and sharpness distribution maps.", parameters: "Attention map: gradient-weighted, Scales: 3 (fine/medium/coarse), Consistency: cross-scale correlation", accuracy: "Medium-High — 78-90%", source: "Zhao, T. et al. (2023) — Multi-Attentional Deepfake Detection, CVPR", useCase: "Detecting AI-generated images by identifying unnatural spatial attention distributions", strengths: "• Captures high-level semantic artifacts\\n• Works across generation methods\\n• Multi-scale analysis\\n• Interpretable attention maps", limitations: "• Requires sufficient image complexity\\n• May struggle with simple scenes\\n• Attention patterns vary by content\\n• Training-dependent performance" },
        vi: { name: "Nhất quán bản đồ chú ý", description: "Phân tích mẫu chú ý không gian để phát hiện không nhất quán đặc trưng ảnh AI.", algorithm: "Phân tích nhất quán tự chú ý cho phát hiện ảnh tổng hợp", mechanism: "Ảnh AI thường thể hiện mẫu chú ý không tự nhiên với mức chi tiết không nhất quán.", parameters: "Bản đồ: có trọng số gradient, Tỷ lệ: 3, Nhất quán: tương quan đa tỷ lệ", accuracy: "Trung bình-Cao — 78-90%", source: "Zhao et al. (2023), CVPR", useCase: "Phát hiện ảnh AI qua phân bố chú ý không gian bất thường", strengths: "• Nắm bắt hiện vật ngữ nghĩa cao\\n• Hoạt động qua các phương pháp tạo\\n• Phân tích đa tỷ lệ\\n• Bản đồ chú ý có thể diễn giải", limitations: "• Cần độ phức tạp ảnh đủ\\n• Khó khăn với cảnh đơn giản\\n• Mẫu chú ý thay đổi theo nội dung\\n• Hiệu suất phụ thuộc huấn luyện" }
    },
    {
        id: "style_transfer", cat: "sensor",
        en: { name: "Style Transfer Detection", description: "Detects artifacts from neural style transfer operations applied to images.", algorithm: "Neural Style Transfer Artifact Detection via Gram Matrix Divergence", mechanism: "Neural style transfer creates characteristic artifacts in texture statistics. This method compares local Gram matrix features across patches to detect unnaturally uniform texture statistics.", parameters: "Feature layers: VGG conv1-5, Gram matrix: per-patch, Divergence: KL, Patch: 64×64 sliding window", accuracy: "Medium-High — 76-88%", source: "Wang, S.Y. et al. (2020) — CNN-Generated Images are Surprisingly Easy to Spot... for Now, CVPR", useCase: "Identifying images that have undergone neural style transfer processing", strengths: "• Detects NST-specific artifacts\\n• Works across different style models\\n• Gram matrix features are discriminative\\n• Can detect partial style transfer", limitations: "• May miss subtle style transfers\\n• Confusion with artistic filters\\n• Dependent on style transfer method\\n• Requires reference style knowledge" },
        vi: { name: "Phát hiện chuyển phong cách", description: "Phát hiện hiện vật từ thao tác chuyển phong cách nơ-ron được áp dụng lên ảnh.", algorithm: "Phát hiện hiện vật chuyển phong cách qua phân kỳ ma trận Gram", mechanism: "Chuyển phong cách nơ-ron tạo hiện vật đặc trưng trong thống kê kết cấu.", parameters: "Lớp đặc trưng: VGG conv1-5, Ma trận Gram: theo mảnh, Phân kỳ: KL, Mảnh: 64×64", accuracy: "Trung bình-Cao — 76-88%", source: "Wang et al. (2020), CVPR", useCase: "Nhận dạng ảnh đã trải qua xử lý chuyển phong cách nơ-ron", strengths: "• Phát hiện hiện vật đặc trưng NST\\n• Hoạt động với nhiều mô hình phong cách\\n• Đặc trưng ma trận Gram phân biệt\\n• Phát hiện chuyển phong cách một phần", limitations: "• Có thể bỏ sót chuyển phong cách tinh tế\\n• Nhầm lẫn với bộ lọc nghệ thuật\\n• Phụ thuộc phương pháp chuyển\\n• Cần kiến thức phong cách tham chiếu" }
    },
    {
        id: "color_temperature", cat: "pixel",
        en: { name: "Color Temperature Consistency", description: "Analyzes local color temperature variations to detect composited regions with mismatched white balance.", algorithm: "Regional Color Temperature Estimation and Consistency Check", mechanism: "Estimates local color temperature (Kelvin) across image patches by analyzing the ratio of warm to cool spectral components. Spliced or AI-generated regions may exhibit inconsistent values.", parameters: "Estimation: Planckian locus fitting, Patches: 32×32, Color space: CIE xy, Temperature range: 2000-10000K", accuracy: "Medium — 72-85%", source: "Hsu, Y.F. & Chang, S.F. (2010) — Image Splicing Detection Using Camera Response Function Consistency, IEEE ICME", useCase: "Detecting composited regions by identifying mismatched white balance settings", strengths: "• Physics-based color analysis\\n• Detects white balance mismatches\\n• Complementary to illuminant map\\n• Works across different scenes", limitations: "• Assumes consistent ambient lighting\\n• Mixed lighting complicates analysis\\n• Color temperature varies naturally\\n• Sensitive to noise in dark regions" },
        vi: { name: "Nhất quán nhiệt độ màu", description: "Phân tích biến đổi nhiệt độ màu cục bộ để phát hiện vùng ghép có cân bằng trắng không khớp.", algorithm: "Ước lượng nhiệt độ màu vùng và kiểm tra nhất quán", mechanism: "Ước lượng nhiệt độ màu cục bộ (Kelvin) qua phân tích tỷ lệ thành phần phổ nóng/lạnh.", parameters: "Ước lượng: khớp quỹ tích Planck, Mảnh: 32×32, Không gian: CIE xy, Phạm vi: 2000-10000K", accuracy: "Trung bình — 72-85%", source: "Hsu & Chang (2010), IEEE ICME", useCase: "Phát hiện vùng ghép qua cài đặt cân bằng trắng không khớp", strengths: "• Phân tích màu dựa vật lý\\n• Phát hiện lệch cân bằng trắng\\n• Bổ sung cho bản đồ chiếu sáng\\n• Hoạt động qua nhiều cảnh", limitations: "• Giả định chiếu sáng môi trường nhất quán\\n• Chiếu sáng hỗn hợp phức tạp hóa\\n• Nhiệt độ màu thay đổi tự nhiên\\n• Nhạy cảm nhiễu trong vùng tối" }
    },
    {
        id: "sift_forensics", cat: "pixel",
        en: { name: "SIFT Keypoint Forensics", description: "Uses Scale-Invariant Feature Transform keypoints to detect duplicated and manipulated image regions.", algorithm: "SIFT-Based Copy-Move Forgery Detection with Geometric Verification", mechanism: "Extracts SIFT keypoints and descriptors from the image, then matches them to find duplicated regions. Geometric verification using RANSAC eliminates false matches.", parameters: "Octaves: 4, Scales: 5, Descriptor: 128-dim, Matching: ratio test (0.6), Verification: RANSAC", accuracy: "High — 85-95%", source: "Amerini, I. et al. (2011) — A SIFT-Based Forensic Method for Copy-Move Attack Detection, IEEE TIFS", useCase: "Robust copy-move forgery detection invariant to scaling, rotation, and illumination changes", strengths: "• Scale and rotation invariant\\n• Geometric verification reduces false matches\\n• Well-proven in computer vision\\n• Handles partial occlusion", limitations: "• Computationally expensive\\n• Struggles with smooth/textureless regions\\n• Memory intensive for many keypoints\\n• Parameter sensitivity" },
        vi: { name: "Pháp y điểm khóa SIFT", description: "Sử dụng điểm khóa SIFT để phát hiện vùng ảnh trùng lặp và bị thao túng.", algorithm: "Phát hiện giả mạo sao chép dựa SIFT với xác minh hình học", mechanism: "Trích xuất điểm khóa và mô tả SIFT, rồi khớp để tìm vùng trùng lặp.", parameters: "Octave: 4, Tỷ lệ: 5, Mô tả: 128 chiều, Khớp: ratio test (0.6), Xác minh: RANSAC", accuracy: "Cao — 85-95%", source: "Amerini et al. (2011), IEEE TIFS", useCase: "Phát hiện giả mạo sao chép bền với co giãn, xoay và thay đổi chiếu sáng", strengths: "• Bất biến tỷ lệ và xoay\\n• Xác minh hình học giảm khớp sai\\n• Đã chứng minh trong thị giác máy tính\\n• Xử lý che phủ một phần", limitations: "• Tốn tài nguyên tính toán\\n• Khó khăn với vùng mịn/không kết cấu\\n• Tốn bộ nhớ cho nhiều điểm khóa\\n• Nhạy cảm tham số" }
    },
    {
        id: "neural_compression", cat: "sensor",
        en: { name: "Neural Compression Artifact Detection", description: "Detects compression artifacts specific to neural network-based image generation pipelines.", algorithm: "Neural Network Quantization and Compression Fingerprint Analysis", mechanism: "AI image generators use architectures with specific quantization levels, activation functions, and upsampling operations. These leave characteristic fingerprints including checkerboard patterns and periodic micro-artifacts.", parameters: "Analysis: frequency spectrum, Checkerboard: 2×2/4×4 periodic, Quantization: 8/16-bit, Activation: ReLU boundary", accuracy: "High — 82-92%", source: "Frank, J. et al. (2020) — Leveraging Frequency Analysis for Deep Fake Image Recognition, ICML", useCase: "Identifying images produced by neural network generation pipelines through compression signatures", strengths: "• Targets neural network-specific artifacts\\n• Works across generator architectures\\n• Frequency analysis is robust\\n• Detects checkerboard patterns", limitations: "• May not detect latest generators\\n• Post-processing can reduce artifacts\\n• Requires frequency domain expertise\\n• Adversarial attacks can evade" },
        vi: { name: "Phát hiện hiện vật nén nơ-ron", description: "Phát hiện hiện vật nén đặc trưng của pipeline tạo ảnh bằng mạng nơ-ron.", algorithm: "Phân tích vân tay lượng tử hóa và nén mạng nơ-ron", mechanism: "Bộ tạo ảnh AI sử dụng kiến trúc với mức lượng tử cụ thể. Chúng để lại vân tay nén đặc trưng.", parameters: "Phân tích: phổ tần số, Bàn cờ: tuần hoàn 2×2/4×4, Lượng tử: 8/16-bit", accuracy: "Cao — 82-92%", source: "Frank et al. (2020), ICML", useCase: "Nhận dạng ảnh từ pipeline tạo mạng nơ-ron qua chữ ký nén", strengths: "• Nhắm vào hiện vật đặc trưng mạng nơ-ron\\n• Hoạt động qua nhiều kiến trúc\\n• Phân tích tần số robust\\n• Phát hiện mẫu bàn cờ", limitations: "• Có thể không phát hiện bộ tạo mới nhất\\n• Hậu xử lý có thể giảm hiện vật\\n• Cần chuyên môn miền tần số\\n• Tấn công đối nghịch có thể tránh" }
    }
];

// Generate files
for (const m of methods) {
    const dir = path.join(base, m.id, 'i18n');
    fs.mkdirSync(dir, { recursive: true });

    // Build full JSON with references
    const makeJson = (data, isEn) => {
        const ref = [{ title: data.source, url: "" }];
        const obj = { name: data.name, description: data.description, algorithm: data.algorithm, mechanism: data.mechanism, parameters: data.parameters, accuracy: data.accuracy, source: data.source, useCase: data.useCase, references: ref };
        if (data.strengths) { obj.strengths = data.strengths; obj.limitations = data.limitations; }
        return JSON.stringify(obj, null, 4);
    };

    const enJson = makeJson(m.en, true);
    const viJson = makeJson(m.vi, false);

    fs.writeFileSync(path.join(dir, 'en.json'), enJson, 'utf8');
    fs.writeFileSync(path.join(dir, 'vi.json'), viJson, 'utf8');
    // Other languages copy en
    for (const lang of ['zh', 'ja', 'ko', 'es']) {
        fs.writeFileSync(path.join(dir, `${lang}.json`), enJson, 'utf8');
    }

    // page.tsx
    const pageTsx = `"use client";
import MethodDetail from "../_components/MethodDetail";
import en from "./i18n/en.json";
import vi from "./i18n/vi.json";
import zh from "./i18n/zh.json";
import ja from "./i18n/ja.json";
import ko from "./i18n/ko.json";
import es from "./i18n/es.json";

const i18n = { en, vi, zh, ja, ko, es };

export default function Page() {
    return <MethodDetail methodId="${m.id}" translations={i18n} />;
}
`;
    fs.writeFileSync(path.join(base, m.id, 'page.tsx'), pageTsx, 'utf8');
    console.log('Created:', m.id);
}
console.log('Done! Created', methods.length, 'methods');
