const fs = require('fs'), p = require('path'), dir = p.join(__dirname, '..', 'src', 'lib', 'methods', 'text');
const M = [
    ['acronymUsage', 'analyzeAcronymUsage', 'Acronym Usage', 'signal.acronymUsage', '📌', `const acronyms=(text.match(/\\b[A-Z]{2,6}\\b/g)||[]).length;const words=text.split(/\\s+/).length;const ratio=words>0?acronyms/words:0;`, `if(ratio<0.005)score=60;else if(ratio<0.02)score=46;else if(ratio>0.06)score=35;else score=44;`, `\`Acronyms: \${acronyms}, Ratio: \${ratio.toFixed(4)}\``],
    ['questionMarkDensity', 'analyzeQuestionMarkDensity', 'Question Density', 'signal.questionDensity', '❓', `const questions=(text.match(/\\?/g)||[]).length;const sents=text.split(/[.!?]+/).filter(s=>s.trim().length>0).length;const ratio=sents>0?questions/sents:0;`, `if(ratio<0.02)score=62;else if(ratio<0.1)score=46;else if(ratio>0.3)score=35;else score=44;`, `\`Questions: \${questions}, Ratio: \${ratio.toFixed(3)}\``],
    ['sentenceStartVariety', 'analyzeSentenceStartVariety', 'Sentence Start Variety', 'signal.sentStartVariety', '🔤', `const sents=text.split(/[.!?]+/).filter(s=>s.trim().length>0);const starts=new Map();for(const s of sents){const w=s.trim().split(/\\s+/)[0]?.toLowerCase();if(w)starts.set(w,(starts.get(w)||0)+1);}let repeated=0;for(const v of starts.values())if(v>=3)repeated++;const ratio=sents.length>0?repeated/starts.size:0;`, `if(ratio>0.3)score=68;else if(ratio>0.1)score=52;else if(ratio<0.02)score=32;else score=44;`, `\`Repeated starts: \${repeated}, Unique: \${starts.size}\``],
    ['verbTenseConsistency', 'analyzeVerbTenseConsistency', 'Verb Tense', 'signal.verbTense', '⏰', `const past=(text.match(/\\b\\w+ed\\b/gi)||[]).length;const present=(text.match(/\\b(is|are|am|has|have|do|does|goes|comes|makes|takes|gets)\\b/gi)||[]).length;const future=(text.match(/\\b(will|shall|going to)\\b/gi)||[]).length;const total=past+present+future;const dominant=Math.max(past,present,future);const ratio=total>0?dominant/total:0;`, `if(ratio>0.85)score=64;else if(ratio>0.6)score=48;else if(ratio<0.4)score=34;else score=44;`, `\`Past:\${past} Present:\${present} Future:\${future}\``],
    ['commaFrequency', 'analyzeCommaFrequency', 'Comma Frequency', 'signal.commaFreq', '📝', `const commas=(text.match(/,/g)||[]).length;const words=text.split(/\\s+/).length;const ratio=words>0?commas/words:0;`, `if(ratio<0.02)score=62;else if(ratio<0.06)score=46;else if(ratio>0.12)score=35;else score=44;`, `\`Commas: \${commas}, Ratio: \${ratio.toFixed(4)}\``],
    ['semicolonUsage', 'analyzeSemicolonUsage', 'Semicolon Usage', 'signal.semicolonUsage', '✒️', `const semi=(text.match(/;/g)||[]).length;const sents=text.split(/[.!?]+/).filter(s=>s.trim().length>0).length;const ratio=sents>0?semi/sents:0;`, `if(ratio<0.005)score=60;else if(ratio<0.05)score=46;else if(ratio>0.15)score=38;else score=44;`, `\`Semicolons: \${semi}, Ratio: \${ratio.toFixed(4)}\``],
    ['superlativeUsage', 'analyzeSuperlativeUsage', 'Superlative Usage', 'signal.superlativeUsage', '🏆', `const supers=(text.match(/\\b(most|best|worst|largest|smallest|greatest|least|highest|lowest|fastest|newest|oldest|biggest|strongest|weakest)\\b/gi)||[]).length;const words=text.split(/\\s+/).length;const ratio=words>0?supers/words:0;`, `if(ratio>0.02)score=64;else if(ratio>0.008)score=50;else if(ratio<0.001)score=35;else score=44;`, `\`Superlatives: \${supers}, Ratio: \${ratio.toFixed(4)}\``],
    ['contractionDetect', 'analyzeContractionDetect', 'Contraction Detect', 'signal.contractionDetect', '🔗', `const contractions=(text.match(/\\b\\w+'(t|re|ve|ll|d|s|m)\\b/gi)||[]).length;const words=text.split(/\\s+/).length;const ratio=words>0?contractions/words:0;`, `if(ratio<0.005)score=64;else if(ratio<0.02)score=48;else if(ratio>0.06)score=32;else score=44;`, `\`Contractions: \${contractions}, Ratio: \${ratio.toFixed(4)}\``],
    ['averageWordLength', 'analyzeAverageWordLength', 'Avg Word Length', 'signal.avgWordLength', '📏', `const words=text.split(/\\s+/).filter(w=>w.length>0);const totalLen=words.reduce((a,w)=>a+w.length,0);const avg=words.length>0?totalLen/words.length:0;`, `if(avg>6)score=64;else if(avg>5)score=50;else if(avg<4)score=35;else score=44;`, `\`Avg word length: \${avg.toFixed(2)}\``],
    ['emphasisPattern', 'analyzeEmphasisPattern', 'Emphasis Pattern', 'signal.emphasisPattern', '💪', `const caps=(text.match(/\\b[A-Z]{2,}\\b/g)||[]).length;const bold=(text.match(/\\*\\*[^*]+\\*\\*/g)||[]).length;const italic=(text.match(/\\*[^*]+\\*/g)||[]).length;const emDash=(text.match(/—/g)||[]).length;const total=caps+bold+italic+emDash;const sents=text.split(/[.!?]+/).filter(s=>s.trim().length>0).length;const ratio=sents>0?total/sents:0;`, `if(ratio<0.01)score=62;else if(ratio<0.08)score=48;else if(ratio>0.2)score=35;else score=44;`, `\`Emphasis: \${total}, Ratio: \${ratio.toFixed(3)}\``],
    ['definiteArticle', 'analyzeDefiniteArticle', 'Definite Article', 'signal.definiteArticle', '📌', `const theCount=(text.match(/\\bthe\\b/gi)||[]).length;const aCount=(text.match(/\\b(a|an)\\b/gi)||[]).length;const words=text.split(/\\s+/).length;const theR=words>0?theCount/words:0;const ratio=aCount>0?theCount/aCount:theCount;`, `if(theR>0.08)score=64;else if(theR>0.05)score=48;else if(theR<0.02)score=35;else score=44;`, `\`The:\${theCount}, A/An:\${aCount}, Ratio:\${theR.toFixed(4)}\``],
    ['numberUsage', 'analyzeNumberUsage', 'Number Usage', 'signal.numberUsage', '🔢', `const numbers=(text.match(/\\b\\d+\\.?\\d*\\b/g)||[]).length;const words=text.split(/\\s+/).length;const ratio=words>0?numbers/words:0;`, `if(ratio<0.005)score=60;else if(ratio<0.03)score=46;else if(ratio>0.08)score=38;else score=44;`, `\`Numbers: \${numbers}, Ratio: \${ratio.toFixed(4)}\``],
    ['qualifierDensity', 'analyzeQualifierDensity', 'Qualifier Density', 'signal.qualifierDensity', '📋', `const quals=(text.match(/\\b(very|quite|rather|somewhat|fairly|extremely|incredibly|remarkably|particularly|especially|significantly|substantially|considerably|noticeably)\\b/gi)||[]).length;const words=text.split(/\\s+/).length;const ratio=words>0?quals/words:0;`, `if(ratio>0.03)score=66;else if(ratio>0.01)score=50;else if(ratio<0.003)score=35;else score=44;`, `\`Qualifiers: \${quals}, Ratio: \${ratio.toFixed(4)}\``],
    ['passiveActiveMix', 'analyzePassiveActiveMix', 'Passive-Active Mix', 'signal.passiveActiveMix', '🔀', `const passive=(text.match(/\\b(was|were|is|are|been|being)\\s+(\\w+ed|\\w+en)\\b/gi)||[]).length;const sents=text.split(/[.!?]+/).filter(s=>s.trim().length>0).length;const ratio=sents>0?passive/sents:0;`, `if(ratio>0.3)score=66;else if(ratio>0.1)score=50;else if(ratio<0.02)score=34;else score=44;`, `\`Passive: \${passive}, Ratio: \${ratio.toFixed(3)}\``],
    ['quotationUsage', 'analyzeQuotationUsage', 'Quotation Usage', 'signal.quotationUsage', '💬', `const doubleQ=(text.match(/"/g)||[]).length/2;const singleQ=(text.match(/'/g)||[]).length/2;const total=Math.floor(doubleQ+singleQ);const sents=text.split(/[.!?]+/).filter(s=>s.trim().length>0).length;const ratio=sents>0?total/sents:0;`, `if(ratio<0.01)score=60;else if(ratio<0.08)score=46;else if(ratio>0.2)score=35;else score=44;`, `\`Quotes: \${total}, Ratio: \${ratio.toFixed(3)}\``],
    ['analogySimile', 'analyzeAnalogySimile', 'Analogy Simile', 'signal.analogySimile', '🔗', `const similes=(text.match(/\\b(like|as if|as though|resembles|similar to|just as|compared to)\\b/gi)||[]).length;const metaphors=(text.match(/\\b(is a|was a|are the|were the|becomes|became)\\s+\\w+/gi)||[]).length;const total=similes+metaphors;const sents=text.split(/[.!?]+/).filter(s=>s.trim().length>0).length;const ratio=sents>0?total/sents:0;`, `if(ratio<0.01)score=62;else if(ratio<0.06)score=48;else if(ratio>0.15)score=35;else score=44;`, `\`Similes:\${similes}, Metaphors:\${metaphors}\``],
    ['conjunctionPair', 'analyzeConjunctionPair', 'Conjunction Pair', 'signal.conjunctionPair', '🔗', `const pairs=(text.match(/\\b(either\\s*\\.{3}\\s*or|neither\\s*\\.{3}\\s*nor|both\\s*\\.{3}\\s*and|not only\\s*\\.{3}\\s*but also|whether\\s*\\.{3}\\s*or)\\b/gi)||[]).length;const simpleConj=(text.match(/\\b(and|but|or|nor|yet|so)\\b/gi)||[]).length;const words=text.split(/\\s+/).length;const ratio=words>0?simpleConj/words:0;`, `if(ratio>0.04)score=64;else if(ratio>0.02)score=48;else if(ratio<0.01)score=35;else score=44;`, `\`Pairs:\${pairs}, Simple:\${simpleConj}\``],
    ['abstractnessIndex', 'analyzeAbstractnessIndex', 'Abstractness', 'signal.abstractness', '💭', `const abstracts=new Set(['concept','idea','theory','belief','freedom','justice','truth','beauty','knowledge','wisdom','love','peace','power','time','nature','reality','existence','consciousness','thought','mind','soul','spirit','emotion','reason','logic','meaning','purpose','value','principle','ethics']);const words=text.split(/\\s+/).filter(w=>w.length>0);let count=0;for(const w of words)if(abstracts.has(w.toLowerCase()))count++;const ratio=words.length>0?count/words.length:0;`, `if(ratio>0.02)score=64;else if(ratio>0.008)score=50;else if(ratio<0.002)score=35;else score=44;`, `\`Abstract words: \${count}, Ratio: \${ratio.toFixed(4)}\``],
    ['instructionalTone', 'analyzeInstructionalTone', 'Instructional Tone', 'signal.instructionalTone', '📢', `const imperative=(text.match(/^\\s*(note|remember|consider|ensure|make sure|keep in mind|be aware|please|try|avoid|use|follow|check|verify|create|add|remove|update|install)/gmi)||[]).length;const sents=text.split(/[.!?]+/).filter(s=>s.trim().length>0).length;const ratio=sents>0?imperative/sents:0;`, `if(ratio>0.2)score=68;else if(ratio>0.08)score=52;else if(ratio<0.02)score=32;else score=44;`, `\`Imperative: \${imperative}, Ratio: \${ratio.toFixed(3)}\``],
    ['transitionSmooth', 'analyzeTransitionSmooth', 'Transition Smooth', 'signal.transitionSmooth', '🔄', `const trans=(text.match(/\\b(however|therefore|furthermore|moreover|consequently|nevertheless|meanwhile|subsequently|accordingly|additionally|alternatively|conversely|similarly|likewise|in contrast|on the contrary|as a result|in addition|for instance|for example|in conclusion|to summarize)\\b/gi)||[]).length;const sents=text.split(/[.!?]+/).filter(s=>s.trim().length>0).length;const ratio=sents>0?trans/sents:0;`, `if(ratio>0.15)score=68;else if(ratio>0.06)score=52;else if(ratio<0.01)score=32;else score=44;`, `\`Transitions: \${trans}, Ratio: \${ratio.toFixed(3)}\``],
    ['definitionPattern', 'analyzeDefinitionPattern', 'Definition Pattern', 'signal.definitionPattern', '📖', `const defs=(text.match(/\\b(is defined as|refers to|means|is known as|is called|is described as|is characterized by|consists of|is the process of|is a type of)\\b/gi)||[]).length;const sents=text.split(/[.!?]+/).filter(s=>s.trim().length>0).length;const ratio=sents>0?defs/sents:0;`, `if(ratio>0.1)score=70;else if(ratio>0.03)score=55;else if(ratio<0.005)score=32;else score=44;`, `\`Definitions: \${defs}, Ratio: \${ratio.toFixed(3)}\``],
    ['conditionalUsage', 'analyzeConditionalUsage', 'Conditional Usage', 'signal.conditionalUsage', '🔀', `const conds=(text.match(/\\b(if|unless|provided that|assuming|given that|in case|suppose|whether|when|whenever|as long as)\\b/gi)||[]).length;const sents=text.split(/[.!?]+/).filter(s=>s.trim().length>0).length;const ratio=sents>0?conds/sents:0;`, `if(ratio<0.02)score=62;else if(ratio<0.1)score=48;else if(ratio>0.25)score=35;else score=44;`, `\`Conditionals: \${conds}, Ratio: \${ratio.toFixed(3)}\``],
    ['repetitivePhrase', 'analyzeRepetitivePhrase', 'Repetitive Phrase', 'signal.repetitivePhrase', '🔁', `const words=text.toLowerCase().split(/\\s+/);const trigrams=new Map();for(let i=0;i<words.length-2;i++){const tri=words.slice(i,i+3).join(' ');trigrams.set(tri,(trigrams.get(tri)||0)+1);}let repeated=0;for(const v of trigrams.values())if(v>=3)repeated++;const ratio=trigrams.size>0?repeated/trigrams.size:0;`, `if(ratio>0.05)score=68;else if(ratio>0.02)score=52;else if(ratio<0.005)score=32;else score=44;`, `\`Repeated trigrams: \${repeated}, Ratio: \${ratio.toFixed(4)}\``],
    ['conclusionIndicator', 'analyzeConclusionIndicator', 'Conclusion Indicator', 'signal.conclusionIndicator', '🏁', `const indicators=(text.match(/\\b(in conclusion|to conclude|to summarize|in summary|overall|all in all|to sum up|in short|the bottom line|ultimately|finally|in essence|in brief|taking everything into account)\\b/gi)||[]).length;const paras=text.split(/\\n\\n+/).length;const ratio=paras>0?indicators/paras:0;`, `if(ratio>0.3)score=68;else if(ratio>0.1)score=52;else if(indicators===0)score=38;else score=44;`, `\`Conclusions: \${indicators}, Ratio: \${ratio.toFixed(3)}\``],
];
for (const [file, fn, name, key, icon, logic, scoring, det] of M) {
    const code = `/**\n * ${name}\n * AI text detection method\n */\nimport type { AnalysisMethod } from "../../types";\n\nexport function ${fn}(text: string): AnalysisMethod {\n    if (text.length < 100) {\n        return { name: "${name}", nameKey: "${key}", category: "statistical", score: 50, weight: 0.2, description: "Text too short", descriptionKey: "${key}.error", icon: "${icon}" };\n    }\n    ${logic}\n    let score: number;\n    ${scoring}\n    return {\n        name: "${name}", nameKey: "${key}", category: "statistical", score, weight: 0.2,\n        description: score > 55 ? "${name} pattern suggests AI generation" : "Natural ${name.toLowerCase()} — consistent with human writing",\n        descriptionKey: score > 55 ? "${key}.ai" : "${key}.real", icon: "${icon}",\n        details: ${det},\n    };\n}\n`;
    fs.writeFileSync(p.join(dir, file + '.ts'), code);
}
console.log('Created', M.length, 'text methods');
