const fs = require('fs'), p = require('path');
const imgF = ['richardsonLucy', 'wienerResidual', 'secondOrderGrad', 'dctEnergyCompact', 'spatialRichModel', 'midFreqEnergy', 'laplacianVariance', 'sobelMagnitude', 'cannyDensity', 'coocEntropy', 'boxFilterResidual', 'maximalGradFlow', 'differenceHistogram', 'subBandDev', 'gradOrientHist', 'kirschEdge', 'lawsTextureE', 'gaborEnergy', 'scharrGradient', 'structuralComplexity'];
const imgFn = ['analyzeRichardsonLucy', 'analyzeWienerResidual', 'analyzeSecondOrderGrad', 'analyzeDctEnergyCompact', 'analyzeSpatialRichModel', 'analyzeMidFreqEnergy', 'analyzeLaplacianVariance', 'analyzeSobelMagnitude', 'analyzeCannyDensity', 'analyzeCoocEntropy', 'analyzeBoxFilterResidual', 'analyzeMaximalGradFlow', 'analyzeDifferenceHistogram', 'analyzeSubBandDev', 'analyzeGradOrientHist', 'analyzeKirschEdge', 'analyzeLawsTextureE', 'analyzeGaborEnergy', 'analyzeScharrGradient', 'analyzeStructuralComplexity'];
const imgK = ['signal.richardsonLucy', 'signal.wienerResidual', 'signal.secondOrderGrad', 'signal.dctEnergyCompact', 'signal.spatialRichModel', 'signal.midFreqEnergy', 'signal.laplacianVar', 'signal.sobelMagDist', 'signal.cannyDensity', 'signal.coocEntropy', 'signal.boxFilterResid', 'signal.maxGradFlow', 'signal.diffHistogram', 'signal.subBandDev', 'signal.gradOrientHist', 'signal.kirschEdge', 'signal.lawsTextureE', 'signal.gaborEnergy', 'signal.scharrGrad', 'signal.structComplexity'];
const imgId = ['richardson_lucy', 'wiener_residual', 'second_order_grad', 'dct_energy_compact', 'spatial_rich_model', 'mid_freq_energy', 'laplacian_variance', 'sobel_magnitude', 'canny_density', 'cooc_entropy', 'box_filter_residual', 'maximal_grad_flow', 'difference_histogram', 'sub_band_dev', 'grad_orient_hist', 'kirsch_edge', 'laws_texture_e', 'gabor_energy', 'scharr_gradient', 'structural_complexity'];
const imgCat = ['frequency', 'frequency', 'pixel', 'frequency', 'statistical', 'frequency', 'pixel', 'pixel', 'pixel', 'statistical', 'frequency', 'pixel', 'statistical', 'frequency', 'pixel', 'pixel', 'pixel', 'frequency', 'pixel', 'statistical'];
const vidF = ['faceXray', 'faceBlendBound', 'colorHistShift', 'faceSkinSmoothV', 'specularHighlight', 'contourContinuity', 'skinMicroMotion', 'backgroundFreqMap', 'interFrameBlend', 'edgeSharpnessVar', 'nostrildarkness', 'earDetailConsistency', 'clothingEdgeBlend', 'temporalJitter', 'skinPoreSimulation'];
const vidFn = ['analyzeFaceXray', 'analyzeFaceBlendBound', 'analyzeColorHistShift', 'analyzeFaceSkinSmoothV', 'analyzeSpecularHighlight', 'analyzeContourContinuity', 'analyzeSkinMicroMotion', 'analyzeBGFreqMap', 'analyzeInterFrameBlend', 'analyzeEdgeSharpnessVar', 'analyzeNostrilDarkness', 'analyzeEarDetailConsistency', 'analyzeClothingEdgeBlend', 'analyzeTemporalJitter', 'analyzeSkinPoreSimulation'];
const vidK = ['signal.faceXray', 'signal.faceBlendBound', 'signal.colorHistShift', 'signal.faceSkinSmoothV', 'signal.specularHighlight', 'signal.contourContinuity', 'signal.skinMicroMotion', 'signal.bgFreqMap', 'signal.interFrameBlend', 'signal.edgeSharpnessVar', 'signal.nostrilDarkness', 'signal.earDetail', 'signal.clothingEdgeBlend', 'signal.temporalJitter', 'signal.skinPoreSim'];
const vidId = ['face_xray', 'face_blend_bound', 'color_hist_shift', 'face_skin_smooth_v', 'specular_highlight', 'contour_continuity', 'skin_micro_motion', 'bg_freq_map', 'inter_frame_blend', 'edge_sharpness_var', 'nostril_darkness', 'ear_detail', 'clothing_edge_blend', 'temporal_jitter', 'skin_pore_sim'];
const vidCat = ['sensor', 'sensor', 'statistical', 'sensor', 'sensor', 'pixel', 'sensor', 'frequency', 'frequency', 'pixel', 'sensor', 'sensor', 'pixel', 'frequency', 'sensor'];
const txtF = ['zipfDeviation', 'tokenPredictability', 'logLikelihoodRank', 'entropyPerWord', 'curieDetect', 'vocabularyRichness', 'meanDepParse', 'wordRarityScore', 'clauseBalance', 'textRepetitionMicro', 'textDNAWatermark', 'intrinsicDimension', 'sentenceEntropy', 'lexicalDensity', 'textBurstiness2'];
const txtFn = ['analyzeZipfDeviation', 'analyzeTokenPredictability', 'analyzeLogLikelihoodRank', 'analyzeEntropyPerWord', 'analyzeCurieDetect', 'analyzeVocabularyRichness', 'analyzeMeanDepParse', 'analyzeWordRarityScore', 'analyzeClauseBalance', 'analyzeTextRepetitionMicro', 'analyzeTextDNAWatermark', 'analyzeIntrinsicDimension', 'analyzeSentenceEntropy', 'analyzeLexicalDensity', 'analyzeTextBurstiness2'];
const txtK = ['signal.zipfDeviation', 'signal.tokenPredict', 'signal.logLikelihood', 'signal.entropyPerWord', 'signal.curieDetect', 'signal.vocabRichness', 'signal.meanDepParse', 'signal.wordRarity', 'signal.clauseBalance', 'signal.microRepetition', 'signal.textDNA', 'signal.intrinsicDim', 'signal.sentenceEntropy', 'signal.lexicalDensity', 'signal.textBurstiness2'];
const txtId = ['zipf_deviation', 'token_predictability', 'log_likelihood_rank', 'entropy_per_word', 'curie_detect', 'vocabulary_richness', 'mean_dep_parse', 'word_rarity', 'clause_balance', 'micro_repetition', 'text_dna', 'intrinsic_dimension', 'sentence_entropy', 'lexical_density', 'text_burstiness2'];

const idxPath = p.join(__dirname, '..', 'src', 'lib', 'methods', 'index.ts');
let idx = fs.readFileSync(idxPath, 'utf8');
let exp = '\n// Image v13\n' + imgFn.map((fn, i) => `export { ${fn} } from "./image/${imgF[i]}";`).join('\n');
exp += '\n// Video v6\n' + vidFn.map((fn, i) => `export { ${fn} } from "./video/${vidF[i]}";`).join('\n');
exp += '\n// Text v6\n' + txtFn.map((fn, i) => `export { ${fn} } from "./text/${txtF[i]}";`).join('\n');
idx = idx.trimEnd() + '\n' + exp + '\n';
fs.writeFileSync(idxPath, idx);

const aPath = p.join(__dirname, '..', 'src', 'lib', 'analyzer.ts');
let a = fs.readFileSync(aPath, 'utf8');
const imp = '    // v13\n    ' + imgFn.join(', ') + ',\n    ' + vidFn.join(', ') + ',\n    ' + txtFn.join(',\n    ') + ',';
a = a.replace('} from "./methods";', imp + '\n} from "./methods";');
const imgC = '        // Image v13\n' + imgFn.map(fn => `        ${fn}(pixels, w, h),`).join('\n');
a = a.replace('analyzeGradientMagnitudeHist(pixels, w, h),\n    ];\n\n    // Filter methods based on enabled set', 'analyzeGradientMagnitudeHist(pixels, w, h),\n' + imgC + '\n    ];\n\n    // Filter methods based on enabled set');
const vidC = '                    // Video v6\n' + vidFn.map(fn => `                    ${fn}(pixels, w, h),`).join('\n');
a = a.replace('analyzeVideoFreqSpectrum(pixels, w, h),\n                ];\n\n                const methods = allMethods.filter', 'analyzeVideoFreqSpectrum(pixels, w, h),\n' + vidC + '\n                ];\n\n                const methods = allMethods.filter');
const txtC = '        // Text v6\n' + txtFn.map(fn => `        ${fn}(text),`).join('\n');
a = a.replace('analyzeConclusionIndicator(text),\n    ];\n\n    const methods = allMethods.filter(s => {\n        const ids = TEXT_NAMEKEY_TO_IDS', 'analyzeConclusionIndicator(text),\n' + txtC + '\n    ];\n\n    const methods = allMethods.filter(s => {\n        const ids = TEXT_NAMEKEY_TO_IDS');
const imgM = '    // Image v13\n' + imgId.map((id, i) => `    ${id}: "${imgK[i]}",`).join('\n');
a = a.replace('gradient_magnitude: "signal.gradientMagHist",\n};', 'gradient_magnitude: "signal.gradientMagHist",\n' + imgM + '\n};');
const vidM = '    // Video v6\n' + vidId.map((id, i) => `    ${id}: "${vidK[i]}",`).join('\n');
a = a.replace('video_freq_spectrum: "signal.videoFreqSpectrum",\n};', 'video_freq_spectrum: "signal.videoFreqSpectrum",\n' + vidM + '\n};');
const txtM = '    // Text v6\n' + txtId.map((id, i) => `    ${id}: "${txtK[i]}",`).join('\n');
a = a.replace('conclusion_indicator: "signal.conclusionIndicator",\n};', 'conclusion_indicator: "signal.conclusionIndicator",\n' + txtM + '\n};');
fs.writeFileSync(aPath, a);

const dPath = p.join(__dirname, '..', 'src', 'app', 'methods', 'data.ts');
let d = fs.readFileSync(dPath, 'utf8');
let e2 = '    // Image v13\n';
imgId.forEach((id, i) => { e2 += `    { id: "${id}", category: "${imgCat[i]}" as Category, mediaType: "image" as MediaType, weight: 0.02, year: 2020 },\n`; });
e2 += '    // Video v6\n';
vidId.forEach((id, i) => { e2 += `    { id: "${id}", category: "${vidCat[i]}" as Category, mediaType: "video" as MediaType, weight: 0.02, year: 2021 },\n`; });
e2 += '    // Text v6\n';
txtId.forEach(id => { e2 += `    { id: "${id}", category: "statistical" as Category, mediaType: "text" as MediaType, weight: 0.02, year: 2023 },\n`; });
d = d.replace('];', e2 + '];');
fs.writeFileSync(dPath, d);
console.log('DONE! Registered', imgFn.length + vidFn.length + txtFn.length, 'methods');
